-- Item 4 du plan vocabulaire 1500 mots : renflouer la catégorie 'Vie Sociale'
-- 9 -> 125 mots (116 nouveaux mots, répartis A1:16 A2:36 B1:34 B2:30).
-- Vérifications effectuées avant livraison :
--  - dédup contre les 218 mots existants (aucune collision)
--  - dédup interne au lot (aucun doublon)
--  - contrainte vocabulary_word_level_unique (migration 20260821000001) : filet de sécurité supplémentaire
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Un ami', 'Personne que l''on aime et en qui on a confiance.', 'J''ai rencontré un ami au marché du quartier.', 'A1', 'Vie Sociale'),
  ('La famille', 'Ensemble des parents et des enfants.', 'Ma famille habite près de chez moi.', 'A1', 'Vie Sociale'),
  ('Un enfant', 'Jeune personne, fils ou fille.', 'Les enfants jouent dans le parc du quartier.', 'A1', 'Vie Sociale'),
  ('Le quartier', 'Partie d''une ville où l''on habite.', 'J''aime beaucoup mon quartier, il est calme.', 'A1', 'Vie Sociale'),
  ('La rue', 'Voie entre les maisons dans une ville.', 'Ma rue est très animée le samedi.', 'A1', 'Vie Sociale'),
  ('Le marché', 'Lieu où l''on vend des produits en plein air.', 'Je fais mes courses au marché tous les dimanches.', 'A1', 'Vie Sociale'),
  ('La fête', 'Moment de joie partagé avec d''autres personnes.', 'Nous préparons une fête pour son anniversaire.', 'A1', 'Vie Sociale'),
  ('L''anniversaire', 'Jour qui rappelle la date de naissance.', 'Bon anniversaire ! Tu as quel âge ?', 'A1', 'Vie Sociale'),
  ('Un ami d''enfance', 'Ami que l''on connaît depuis très longtemps.', 'Je vois toujours mon ami d''enfance chaque été.', 'A1', 'Vie Sociale'),
  ('Le sourire', 'Expression du visage qui montre la joie.', 'Le sourire de la boulangère met de bonne humeur.', 'A1', 'Vie Sociale'),
  ('Bonjour', 'Mot que l''on dit pour saluer quelqu''un.', 'Je dis toujours bonjour à mes voisins.', 'A1', 'Vie Sociale'),
  ('Merci', 'Mot que l''on dit pour remercier.', 'Merci beaucoup pour votre aide.', 'A1', 'Vie Sociale'),
  ('Un cadeau', 'Objet que l''on offre à quelqu''un.', 'J''ai acheté un cadeau pour la fête des voisins.', 'A1', 'Vie Sociale'),
  ('Le parc', 'Espace vert public dans une ville.', 'Les enfants aiment jouer au parc le mercredi.', 'A1', 'Vie Sociale'),
  ('Un groupe', 'Plusieurs personnes réunies ensemble.', 'Nous formons un groupe pour apprendre le français.', 'A1', 'Vie Sociale'),
  ('La politesse', 'Le respect des règles de bonne conduite.', 'La politesse est importante dans la vie en société.', 'A1', 'Vie Sociale'),
  ('La convivialité', 'Qualité d''une ambiance chaleureuse et agréable entre les gens.', 'Le repas de quartier crée beaucoup de convivialité.', 'A2', 'Vie Sociale'),
  ('Une réunion de quartier', 'Rencontre organisée entre habitants d''un même quartier.', 'La réunion de quartier a lieu tous les mois à la mairie.', 'A2', 'Vie Sociale'),
  ('Le comité des fêtes', 'Groupe qui organise les événements locaux.', 'Le comité des fêtes prépare le feu d''artifice du 14 juillet.', 'A2', 'Vie Sociale'),
  ('La kermesse', 'Fête populaire en plein air, souvent scolaire.', 'Les parents aident à organiser la kermesse de l''école.', 'A2', 'Vie Sociale'),
  ('Le 14 juillet', 'Fête nationale française.', 'On regarde le feu d''artifice le soir du 14 juillet.', 'A2', 'Vie Sociale'),
  ('Le réveillon', 'Repas de fête la veille de Noël ou du Nouvel An.', 'Toute la famille se retrouve pour le réveillon.', 'A2', 'Vie Sociale'),
  ('La galette des rois', 'Gâteau traditionnel partagé en janvier.', 'On mange la galette des rois avec les collègues.', 'A2', 'Vie Sociale'),
  ('Un repas de famille', 'Repas qui réunit plusieurs générations d''une même famille.', 'Le dimanche, nous organisons un repas de famille.', 'A2', 'Vie Sociale'),
  ('La génération', 'Ensemble des personnes nées à la même époque.', 'Les jeunes générations utilisent beaucoup les réseaux sociaux.', 'A2', 'Vie Sociale'),
  ('Les réseaux sociaux', 'Plateformes internet pour communiquer avec d''autres personnes.', 'Elle reste en contact avec sa famille via les réseaux sociaux.', 'A2', 'Vie Sociale'),
  ('Un événement culturel', 'Manifestation liée à l''art ou à la culture.', 'Le musée organise un événement culturel gratuit ce week-end.', 'A2', 'Vie Sociale'),
  ('La bibliothèque municipale', 'Lieu public où l''on emprunte des livres.', 'J''emprunte des livres à la bibliothèque municipale.', 'A2', 'Vie Sociale'),
  ('La maison de quartier', 'Lieu qui propose des activités pour les habitants.', 'La maison de quartier organise des cours de couture.', 'A2', 'Vie Sociale'),
  ('Le club de sport', 'Association où l''on pratique une activité sportive.', 'Mon fils est inscrit dans un club de sport.', 'A2', 'Vie Sociale'),
  ('Une sortie scolaire', 'Activité organisée par l''école en dehors de la classe.', 'Les enfants ont adoré leur sortie scolaire au zoo.', 'A2', 'Vie Sociale'),
  ('Le respect', 'Considération que l''on a pour les autres.', 'Le respect des règles est important en société.', 'A2', 'Vie Sociale'),
  ('La tolérance', 'Le fait d''accepter les différences des autres.', 'La tolérance permet de mieux vivre ensemble.', 'A2', 'Vie Sociale'),
  ('La diversité', 'La présence de personnes et de cultures différentes.', 'Ce quartier est connu pour sa grande diversité.', 'A2', 'Vie Sociale'),
  ('Un immigré', 'Personne née dans un autre pays et installée en France.', 'Beaucoup d''immigrés contribuent à la vie économique du pays.', 'A2', 'Vie Sociale'),
  ('L''intégration', 'Le fait de s''adapter et de participer à la vie d''un pays.', 'Apprendre le français facilite l''intégration.', 'A2', 'Vie Sociale'),
  ('La langue maternelle', 'Première langue apprise dans l''enfance.', 'Sa langue maternelle est l''arabe, mais il parle bien français.', 'A2', 'Vie Sociale'),
  ('Le dialogue', 'Échange de paroles entre deux ou plusieurs personnes.', 'Le dialogue permet de résoudre beaucoup de conflits.', 'A2', 'Vie Sociale'),
  ('Un malentendu', 'Erreur de compréhension entre deux personnes.', 'Ce malentendu s''est réglé après une simple discussion.', 'A2', 'Vie Sociale'),
  ('Le vivre-ensemble', 'La capacité à partager la vie en société avec les autres.', 'Le vivre-ensemble est un sujet souvent discuté en France.', 'A2', 'Vie Sociale'),
  ('La laïcité', 'Séparation entre la religion et l''État.', 'La laïcité est un principe important de la République française.', 'A2', 'Vie Sociale'),
  ('La devise de la République', 'Phrase qui représente les valeurs d''un pays.', 'La devise de la République française est Liberté, Égalité, Fraternité.', 'A2', 'Vie Sociale'),
  ('Le drapeau', 'Symbole d''un pays représenté par un tissu coloré.', 'Le drapeau français est bleu, blanc, rouge.', 'A2', 'Vie Sociale'),
  ('L''hymne national', 'Chant qui représente officiellement un pays.', 'La Marseillaise est l''hymne national français.', 'A2', 'Vie Sociale'),
  ('Un rassemblement', 'Réunion de plusieurs personnes au même endroit.', 'Un rassemblement a eu lieu place de la République.', 'A2', 'Vie Sociale'),
  ('Une manifestation', 'Réunion publique pour exprimer une opinion.', 'La manifestation s''est déroulée dans le calme.', 'A2', 'Vie Sociale'),
  ('L''opinion publique', 'Ce que pense la majorité des gens sur un sujet.', 'L''opinion publique est très partagée sur cette question.', 'A2', 'Vie Sociale'),
  ('Le journal télévisé', 'Émission qui présente les informations à la télévision.', 'Je regarde le journal télévisé tous les soirs.', 'A2', 'Vie Sociale'),
  ('Une association de quartier', 'Groupe local qui organise des activités pour les habitants.', 'L''association de quartier propose une aide aux devoirs.', 'A2', 'Vie Sociale'),
  ('Le don', 'Action d''offrir quelque chose sans rien attendre en retour.', 'Elle fait un don à une association chaque mois.', 'A2', 'Vie Sociale'),
  ('L''entraide', 'Aide mutuelle entre plusieurs personnes.', 'L''entraide entre voisins est très développée dans ce village.', 'A2', 'Vie Sociale'),
  ('Un pot de départ', 'Petite fête organisée pour dire au revoir à quelqu''un.', 'Ses collègues ont organisé un pot de départ avant son déménagement.', 'A2', 'Vie Sociale'),
  ('Le tissu associatif', 'Ensemble des associations actives dans une société.', 'Le tissu associatif français est très riche.', 'B1', 'Vie Sociale'),
  ('Le mécénat', 'Soutien financier apporté par une entreprise à une cause.', 'L''entreprise pratique le mécénat culturel depuis dix ans.', 'B1', 'Vie Sociale'),
  ('La mixité sociale', 'Présence de personnes de milieux sociaux différents dans un même lieu.', 'La mixité sociale est encouragée dans les nouveaux quartiers.', 'B1', 'Vie Sociale'),
  ('La cohésion sociale', 'Le fait que les membres d''une société se sentent unis.', 'Les fêtes de quartier renforcent la cohésion sociale.', 'B1', 'Vie Sociale'),
  ('Le lien social', 'Relation qui unit les individus au sein d''une communauté.', 'Le sport collectif crée du lien social entre les habitants.', 'B1', 'Vie Sociale'),
  ('L''isolement', 'Le fait d''être seul, coupé des autres.', 'L''isolement touche particulièrement les personnes âgées.', 'B1', 'Vie Sociale'),
  ('La précarité', 'Situation instable, sans sécurité matérielle.', 'L''association aide les familles en situation de précarité.', 'B1', 'Vie Sociale'),
  ('Une maraude', 'Action d''aller à la rencontre des personnes sans-abri.', 'Les bénévoles organisent une maraude chaque hiver.', 'B1', 'Vie Sociale'),
  ('Le don du sang', 'Action d''offrir volontairement son sang pour aider les malades.', 'Il participe régulièrement au don du sang.', 'B1', 'Vie Sociale'),
  ('Le service civique', 'Engagement volontaire de quelques mois au service de l''intérêt général.', 'Elle effectue un service civique dans une école.', 'B1', 'Vie Sociale'),
  ('La vie associative', 'Ensemble des activités organisées par des associations.', 'La vie associative est très active dans ce village.', 'B1', 'Vie Sociale'),
  ('Un adhérent', 'Personne inscrite dans une association ou un club.', 'L''association compte plus de deux cents adhérents.', 'B1', 'Vie Sociale'),
  ('La cotisation', 'Somme d''argent versée régulièrement à une association.', 'La cotisation annuelle finance les activités du club.', 'B1', 'Vie Sociale'),
  ('Le conseil de quartier', 'Groupe d''habitants consulté sur les décisions locales.', 'Le conseil de quartier se réunit une fois par trimestre.', 'B1', 'Vie Sociale'),
  ('La démocratie participative', 'Système où les citoyens participent aux décisions publiques.', 'La mairie encourage la démocratie participative.', 'B1', 'Vie Sociale'),
  ('Un débat public', 'Discussion ouverte sur un sujet qui concerne tous les citoyens.', 'Un débat public a été organisé sur le projet de tramway.', 'B1', 'Vie Sociale'),
  ('Le civisme', 'Comportement respectueux des règles de la vie en société.', 'Le civisme se voit dans les petits gestes du quotidien.', 'B1', 'Vie Sociale'),
  ('La discrimination', 'Traitement injuste d''une personne à cause de son origine, son sexe, etc.', 'La loi interdit toute forme de discrimination.', 'B1', 'Vie Sociale'),
  ('L''égalité des chances', 'Principe selon lequel chacun doit avoir les mêmes opportunités.', 'L''école doit garantir l''égalité des chances.', 'B1', 'Vie Sociale'),
  ('La parité', 'L''égalité de représentation entre les femmes et les hommes.', 'La parité progresse dans la vie politique française.', 'B1', 'Vie Sociale'),
  ('Le harcèlement', 'Comportement répété qui fait du mal à une personne.', 'L''école a mis en place un dispositif contre le harcèlement.', 'B1', 'Vie Sociale'),
  ('La médiation sociale', 'Intervention pour aider à résoudre un conflit entre personnes.', 'Un médiateur social intervient souvent dans les conflits de voisinage.', 'B1', 'Vie Sociale'),
  ('Le conflit de voisinage', 'Désaccord entre des personnes qui habitent près l''une de l''autre.', 'Le conflit de voisinage a été réglé par un médiateur.', 'B1', 'Vie Sociale'),
  ('La transmission intergénérationnelle', 'Partage de savoirs entre différentes générations.', 'Cet atelier favorise la transmission intergénérationnelle.', 'B1', 'Vie Sociale'),
  ('Le bénévole', 'Personne qui donne de son temps sans être payée.', 'Les bénévoles sont indispensables au bon fonctionnement de l''association.', 'B1', 'Vie Sociale'),
  ('Une collecte', 'Action de rassembler de l''argent ou des objets pour une cause.', 'L''école organise une collecte de vêtements chaque hiver.', 'B1', 'Vie Sociale'),
  ('La solidarité intergénérationnelle', 'Entraide entre les jeunes et les personnes âgées.', 'Ce projet encourage la solidarité intergénérationnelle.', 'B1', 'Vie Sociale'),
  ('Le repli communautaire', 'Le fait de se replier sur son propre groupe d''origine.', 'Le repli communautaire freine parfois l''intégration.', 'B1', 'Vie Sociale'),
  ('L''engagement citoyen', 'Participation active à la vie de la société.', 'Le vote est une forme d''engagement citoyen.', 'B1', 'Vie Sociale'),
  ('La participation citoyenne', 'Implication des habitants dans les décisions publiques.', 'La participation citoyenne augmente lors des grands projets urbains.', 'B1', 'Vie Sociale'),
  ('Le pluralisme', 'La coexistence de plusieurs opinions ou cultures dans une société.', 'Le pluralisme est une richesse pour la société française.', 'B1', 'Vie Sociale'),
  ('La fracture sociale', 'Écart important entre différents groupes d''une société.', 'La fracture sociale reste un défi pour les politiques publiques.', 'B1', 'Vie Sociale'),
  ('Le respect mutuel', 'Considération réciproque entre plusieurs personnes.', 'Le respect mutuel est la base du vivre-ensemble.', 'B1', 'Vie Sociale'),
  ('La cause caritative', 'Action ou projet destiné à aider les personnes en difficulté.', 'Elle organise un événement pour une cause caritative.', 'B1', 'Vie Sociale'),
  ('Le contrat social', 'Accord implicite qui fonde la vie en société selon certains philosophes.', 'Rousseau a théorisé la notion de contrat social.', 'B2', 'Vie Sociale'),
  ('La fraternité', 'Valeur de solidarité entre les citoyens d''une même nation.', 'La fraternité est l''une des trois valeurs de la devise française.', 'B2', 'Vie Sociale'),
  ('Le communautarisme', 'Tendance d''un groupe à privilégier ses propres règles au sein de la société.', 'Le communautarisme est souvent débattu dans les médias français.', 'B2', 'Vie Sociale'),
  ('L''universalisme', 'Principe selon lequel les mêmes droits s''appliquent à tous, sans distinction.', 'La République française se réclame de l''universalisme.', 'B2', 'Vie Sociale'),
  ('La sociologie', 'Science qui étudie le fonctionnement des sociétés humaines.', 'Elle étudie la sociologie à l''université.', 'B2', 'Vie Sociale'),
  ('Le déterminisme social', 'Idée selon laquelle l''origine sociale influence fortement le parcours d''une personne.', 'Les sociologues débattent du poids du déterminisme social.', 'B2', 'Vie Sociale'),
  ('L''ascenseur social', 'Possibilité de changer de position sociale grâce à ses efforts.', 'L''école est censée favoriser l''ascenseur social.', 'B2', 'Vie Sociale'),
  ('La stigmatisation', 'Le fait de désigner négativement une personne ou un groupe.', 'La stigmatisation des chômeurs est un sujet sensible.', 'B2', 'Vie Sociale'),
  ('Le repli identitaire', 'Tendance à se refermer sur sa propre identité culturelle.', 'Le repli identitaire inquiète certains sociologues.', 'B2', 'Vie Sociale'),
  ('La citoyenneté active', 'Participation concrète des citoyens à la vie collective.', 'Le bénévolat est une forme de citoyenneté active.', 'B2', 'Vie Sociale'),
  ('L''intérêt général', 'Ce qui profite à l''ensemble de la société plutôt qu''à un individu.', 'Les élus doivent agir dans l''intérêt général.', 'B2', 'Vie Sociale'),
  ('Le bien commun', 'Ce qui appartient et profite à tous les membres d''une société.', 'Préserver l''environnement relève du bien commun.', 'B2', 'Vie Sociale'),
  ('La délibération collective', 'Discussion en groupe avant de prendre une décision commune.', 'La délibération collective a permis de trouver un compromis.', 'B2', 'Vie Sociale'),
  ('Le consensus', 'Accord général obtenu après discussion entre plusieurs personnes.', 'Un consensus a été trouvé sur le projet de rénovation.', 'B2', 'Vie Sociale'),
  ('La polarisation', 'Le fait que les opinions deviennent de plus en plus opposées.', 'La polarisation politique s''observe aussi sur les réseaux sociaux.', 'B2', 'Vie Sociale'),
  ('Le tissu social', 'Ensemble des relations qui structurent une société.', 'Les associations renforcent le tissu social local.', 'B2', 'Vie Sociale'),
  ('La solidarité nationale', 'Entraide organisée à l''échelle d''un pays entier.', 'La sécurité sociale repose sur le principe de solidarité nationale.', 'B2', 'Vie Sociale'),
  ('L''inclusion sociale', 'Le fait d''intégrer pleinement chacun dans la société.', 'Ce dispositif favorise l''inclusion sociale des personnes handicapées.', 'B2', 'Vie Sociale'),
  ('La ségrégation', 'Séparation imposée entre différents groupes de population.', 'La ségrégation spatiale touche certains quartiers urbains.', 'B2', 'Vie Sociale'),
  ('Le clivage générationnel', 'Différence marquée d''opinions entre les générations.', 'Le clivage générationnel est visible sur les questions écologiques.', 'B2', 'Vie Sociale'),
  ('Le militantisme', 'Engagement actif et souvent public pour une cause.', 'Son militantisme associatif remonte à ses années d''études.', 'B2', 'Vie Sociale'),
  ('Une ONG', 'Organisation non gouvernementale, indépendante de l''État, qui agit pour une cause d''intérêt général.', 'Cette ONG lutte contre la pauvreté dans plusieurs pays.', 'B2', 'Vie Sociale'),
  ('La gouvernance locale', 'Manière dont une collectivité est gérée et administrée.', 'La gouvernance locale implique de plus en plus les citoyens.', 'B2', 'Vie Sociale'),
  ('Le pacte républicain', 'Ensemble des valeurs et engagements partagés par les citoyens d''une République.', 'Le respect de la loi fait partie du pacte républicain.', 'B2', 'Vie Sociale'),
  ('La reconnaissance sociale', 'Le fait d''être valorisé et respecté par la société.', 'Le bénévolat apporte une forme de reconnaissance sociale.', 'B2', 'Vie Sociale'),
  ('Le déclin du lien social', 'Affaiblissement progressif des relations entre les membres d''une société.', 'Certains sociologues observent un déclin du lien social dans les grandes villes.', 'B2', 'Vie Sociale'),
  ('L''altruisme', 'Attitude qui consiste à se soucier du bien-être des autres.', 'Son altruisme la pousse à s''investir dans plusieurs associations.', 'B2', 'Vie Sociale'),
  ('La philanthropie', 'Générosité désintéressée envers autrui, souvent sous forme de dons.', 'Cet entrepreneur est connu pour sa philanthropie.', 'B2', 'Vie Sociale'),
  ('Le mécénat d''entreprise', 'Soutien financier apporté par une entreprise à des projets d''intérêt général.', 'Le mécénat d''entreprise finance de nombreux projets culturels.', 'B2', 'Vie Sociale'),
  ('La responsabilité sociétale', 'Engagement d''une organisation à agir de façon éthique envers la société.', 'La responsabilité sociétale des entreprises est de plus en plus valorisée.', 'B2', 'Vie Sociale');
