-- Item 6.2 du plan vocabulaire 1500 mots : nouvelle catégorie 'Alimentation & Restauration'
-- 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 750 mots déjà en base : aucune collision
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Le pain', 'Aliment de base fait de farine et d''eau.', 'J''achète du pain frais chaque matin.', 'A1', 'Alimentation & Restauration'),
  ('Le lait', 'Boisson blanche provenant des vaches.', 'Je bois du lait au petit-déjeuner.', 'A1', 'Alimentation & Restauration'),
  ('L''eau', 'Boisson essentielle et transparente.', 'Buvez de l''eau régulièrement.', 'A1', 'Alimentation & Restauration'),
  ('Le fromage', 'Aliment fabriqué à partir de lait.', 'La France est connue pour ses fromages.', 'A1', 'Alimentation & Restauration'),
  ('La viande', 'Chair d''un animal consommée comme aliment.', 'Je ne mange pas de viande le vendredi.', 'A1', 'Alimentation & Restauration'),
  ('Le poisson', 'Animal aquatique consommé comme aliment.', 'Le poisson est riche en protéines.', 'A1', 'Alimentation & Restauration'),
  ('Les légumes', 'Plantes consommées comme aliment.', 'Mangez des légumes à chaque repas.', 'A1', 'Alimentation & Restauration'),
  ('Les fruits', 'Produits sucrés des plantes consommés comme aliment.', 'Les enfants adorent les fruits d''été.', 'A1', 'Alimentation & Restauration'),
  ('Le petit-déjeuner', 'Premier repas de la journée.', 'Je prends toujours un petit-déjeuner copieux.', 'A1', 'Alimentation & Restauration'),
  ('Le déjeuner', 'Repas du milieu de journée.', 'Le déjeuner est à midi.', 'A1', 'Alimentation & Restauration'),
  ('Le dîner', 'Repas du soir.', 'Nous dînons vers vingt heures.', 'A1', 'Alimentation & Restauration'),
  ('Un restaurant', 'Lieu où l''on mange en payant.', 'Nous allons au restaurant ce soir.', 'A1', 'Alimentation & Restauration'),
  ('Un menu', 'Liste des plats proposés dans un restaurant.', 'Le menu du jour coûte quinze euros.', 'A1', 'Alimentation & Restauration'),
  ('Une assiette', 'Objet dans lequel on sert la nourriture.', 'Finis ton assiette avant le dessert.', 'A1', 'Alimentation & Restauration'),
  ('Un verre', 'Récipient pour boire.', 'Remplis mon verre d''eau, s''il te plaît.', 'A1', 'Alimentation & Restauration'),
  ('Une fourchette', 'Ustensile pour piquer les aliments.', 'Utilise ta fourchette pour manger.', 'A1', 'Alimentation & Restauration'),
  ('Un couteau', 'Ustensile pour couper les aliments.', 'Attention en utilisant le couteau.', 'A1', 'Alimentation & Restauration'),
  ('Une cuillère', 'Ustensile pour manger les aliments liquides.', 'Prends une cuillère pour la soupe.', 'A1', 'Alimentation & Restauration'),
  ('La faim', 'Sensation qui pousse à manger.', 'J''ai faim, allons manger.', 'A1', 'Alimentation & Restauration'),
  ('Une entrée', 'Premier plat d''un repas au restaurant.', 'J''ai pris une salade en entrée.', 'A2', 'Alimentation & Restauration'),
  ('Un plat principal', 'Plat central d''un repas.', 'Le plat principal était délicieux.', 'A2', 'Alimentation & Restauration'),
  ('Un dessert', 'Plat sucré servi à la fin du repas.', 'Nous avons pris une tarte en dessert.', 'A2', 'Alimentation & Restauration'),
  ('L''addition', 'Facture à payer à la fin d''un repas au restaurant.', 'Pouvez-vous m''apporter l''addition ?', 'A2', 'Alimentation & Restauration'),
  ('Un pourboire', 'Somme donnée en plus pour remercier le service.', 'Le pourboire n''est pas obligatoire en France.', 'A2', 'Alimentation & Restauration'),
  ('Un serveur', 'Personne qui sert les clients dans un restaurant.', 'Le serveur nous a recommandé le poisson du jour.', 'A2', 'Alimentation & Restauration'),
  ('La carte des vins', 'Liste des vins proposés dans un restaurant.', 'Le sommelier nous a présenté la carte des vins.', 'A2', 'Alimentation & Restauration'),
  ('Une réservation', 'Action de réserver une table à l''avance.', 'J''ai fait une réservation pour deux personnes.', 'A2', 'Alimentation & Restauration'),
  ('Un plat végétarien', 'Plat sans viande ni poisson.', 'Le restaurant propose un plat végétarien.', 'A2', 'Alimentation & Restauration'),
  ('Un régime alimentaire', 'Ensemble des habitudes de consommation d''une personne.', 'Elle suit un régime alimentaire sans gluten.', 'A2', 'Alimentation & Restauration'),
  ('Une recette', 'Instructions pour préparer un plat.', 'J''ai suivi une recette de gâteau au chocolat.', 'A2', 'Alimentation & Restauration'),
  ('Un ingrédient', 'Élément utilisé dans la préparation d''un plat.', 'La farine est l''ingrédient principal de ce gâteau.', 'A2', 'Alimentation & Restauration'),
  ('Cuire', 'Préparer un aliment à la chaleur.', 'Il faut cuire le poulet vingt minutes.', 'A2', 'Alimentation & Restauration'),
  ('Bouillir', 'Chauffer un liquide jusqu''à ébullition.', 'Faites bouillir l''eau avant d''ajouter les pâtes.', 'A2', 'Alimentation & Restauration'),
  ('Griller', 'Cuire un aliment directement sur une source de chaleur.', 'Nous allons griller de la viande ce soir.', 'A2', 'Alimentation & Restauration'),
  ('Une poêle', 'Ustensile de cuisine pour faire frire ou sauter.', 'J''ai fait cuire les œufs dans une poêle.', 'A2', 'Alimentation & Restauration'),
  ('Une casserole', 'Ustensile de cuisine pour faire cuire des liquides.', 'Mets de l''eau à bouillir dans une casserole.', 'A2', 'Alimentation & Restauration'),
  ('Le four', 'Appareil pour cuire les aliments par chaleur.', 'Le gâteau est au four depuis vingt minutes.', 'A2', 'Alimentation & Restauration'),
  ('Le réfrigérateur', 'Appareil qui garde les aliments au froid.', 'Mets le lait au réfrigérateur.', 'A2', 'Alimentation & Restauration'),
  ('Le congélateur', 'Appareil qui conserve les aliments à très basse température.', 'J''ai des légumes surgelés dans le congélateur.', 'A2', 'Alimentation & Restauration'),
  ('Une épicerie', 'Petit magasin vendant des produits alimentaires.', 'J''achète mon pain à l''épicerie du quartier.', 'A2', 'Alimentation & Restauration'),
  ('La boulangerie', 'Magasin où l''on achète du pain.', 'La boulangerie ouvre à sept heures.', 'A2', 'Alimentation & Restauration'),
  ('La boucherie', 'Magasin où l''on achète de la viande.', 'Il achète sa viande à la boucherie.', 'A2', 'Alimentation & Restauration'),
  ('La poissonnerie', 'Magasin où l''on achète du poisson.', 'La poissonnerie propose du poisson frais chaque jour.', 'A2', 'Alimentation & Restauration'),
  ('Un aliment transformé', 'Aliment ayant subi une préparation industrielle.', 'Il vaut mieux limiter les aliments transformés.', 'A2', 'Alimentation & Restauration'),
  ('Une portion', 'Quantité de nourriture servie à une personne.', 'Les portions sont généreuses dans ce restaurant.', 'A2', 'Alimentation & Restauration'),
  ('Une allergie alimentaire', 'Réaction anormale du corps à un aliment.', 'Signalez toute allergie alimentaire au serveur.', 'A2', 'Alimentation & Restauration'),
  ('Un plat à emporter', 'Repas préparé pour être consommé ailleurs.', 'Nous avons commandé un plat à emporter.', 'A2', 'Alimentation & Restauration'),
  ('La livraison de repas', 'Service qui apporte un repas préparé chez le client.', 'La livraison de repas a mis trente minutes.', 'A2', 'Alimentation & Restauration'),
  ('Un fast-food', 'Restaurant de restauration rapide.', 'Les fast-foods sont très fréquentés le midi.', 'A2', 'Alimentation & Restauration'),
  ('Une cantine scolaire', 'Restaurant collectif dans une école.', 'Mon fils mange à la cantine scolaire.', 'A2', 'Alimentation & Restauration'),
  ('Un repas équilibré', 'Repas contenant les nutriments nécessaires en quantité adaptée.', 'Un repas équilibré comprend des légumes et des protéines.', 'A2', 'Alimentation & Restauration'),
  ('La cuisine française', 'Ensemble des traditions culinaires françaises.', 'La cuisine française est reconnue dans le monde entier.', 'A2', 'Alimentation & Restauration'),
  ('Un plat traditionnel', 'Plat typique d''une région ou d''un pays.', 'Le cassoulet est un plat traditionnel du sud-ouest.', 'A2', 'Alimentation & Restauration'),
  ('Une spécialité régionale', 'Plat typique d''une région précise.', 'Chaque région française a ses spécialités régionales.', 'A2', 'Alimentation & Restauration'),
  ('Le goût', 'Sensation perçue par la langue lors de la dégustation.', 'Ce plat a un goût très épicé.', 'A2', 'Alimentation & Restauration'),
  ('Une odeur de cuisine', 'Arôme dégagé par un plat en préparation.', 'Une bonne odeur de cuisine venait de la maison.', 'A2', 'Alimentation & Restauration'),
  ('L''intolérance au gluten', 'Incapacité à digérer le gluten présent dans certaines céréales.', 'Elle souffre d''une intolérance au gluten.', 'B1', 'Alimentation & Restauration'),
  ('Le végétalisme', 'Régime excluant tous les produits d''origine animale.', 'Le végétalisme se développe de plus en plus en France.', 'B1', 'Alimentation & Restauration'),
  ('Le flexitarisme', 'Régime alimentaire limitant la consommation de viande sans l''exclure totalement.', 'Le flexitarisme séduit de nombreux consommateurs.', 'B1', 'Alimentation & Restauration'),
  ('Les additifs alimentaires', 'Substances ajoutées aux aliments pour les conserver ou les améliorer.', 'Certains additifs alimentaires sont controversés.', 'B1', 'Alimentation & Restauration'),
  ('La conservation des aliments', 'Ensemble des méthodes pour éviter la détérioration des aliments.', 'La chaîne du froid est essentielle à la conservation des aliments.', 'B1', 'Alimentation & Restauration'),
  ('La chaîne du froid', 'Ensemble des étapes maintenant un aliment à basse température.', 'Une rupture de la chaîne du froid peut rendre un aliment dangereux.', 'B1', 'Alimentation & Restauration'),
  ('La sécurité alimentaire', 'Ensemble des mesures garantissant la salubrité des aliments.', 'La sécurité alimentaire est contrôlée par des organismes officiels.', 'B1', 'Alimentation & Restauration'),
  ('L''hygiène alimentaire', 'Ensemble des pratiques qui évitent la contamination des aliments.', 'Les restaurants doivent respecter des règles strictes d''hygiène alimentaire.', 'B1', 'Alimentation & Restauration'),
  ('Une intoxication alimentaire', 'Malaise causé par la consommation d''un aliment contaminé.', 'Ils ont eu une intoxication alimentaire après ce repas.', 'B1', 'Alimentation & Restauration'),
  ('Un label AOC/AOP', 'Signe officiel garantissant l''origine géographique d''un produit.', 'Ce fromage porte un label AOP.', 'B1', 'Alimentation & Restauration'),
  ('L''appellation d''origine contrôlée', 'Certification garantissant qu''un produit provient d''une zone géographique précise selon des méthodes définies.', 'Le champagne bénéficie d''une appellation d''origine contrôlée.', 'B1', 'Alimentation & Restauration'),
  ('Un terroir', 'Ensemble des caractéristiques naturelles influençant un produit alimentaire.', 'Ce vin exprime bien le terroir de la région.', 'B1', 'Alimentation & Restauration'),
  ('La gastronomie', 'Art de bien manger et de préparer des mets raffinés.', 'La gastronomie française est célèbre dans le monde entier.', 'B1', 'Alimentation & Restauration'),
  ('Un chef cuisinier', 'Professionnel responsable de la préparation des plats dans un restaurant.', 'Le chef cuisinier a créé un nouveau menu.', 'B1', 'Alimentation & Restauration'),
  ('Une brigade de cuisine', 'Équipe organisée travaillant dans les cuisines d''un restaurant.', 'La brigade de cuisine travaille sous pression le soir.', 'B1', 'Alimentation & Restauration'),
  ('Un guide gastronomique', 'Publication qui évalue et recommande des restaurants.', 'Ce restaurant a été récompensé par un guide gastronomique.', 'B1', 'Alimentation & Restauration'),
  ('Une étoile Michelin', 'Distinction attribuée aux meilleurs restaurants par le guide Michelin.', 'Ce chef a obtenu sa première étoile Michelin.', 'B1', 'Alimentation & Restauration'),
  ('Un menu dégustation', 'Ensemble de plats variés servis en petites portions.', 'Nous avons choisi le menu dégustation.', 'B1', 'Alimentation & Restauration'),
  ('L''accord mets-vins', 'Association réfléchie entre un plat et un vin.', 'Le sommelier conseille un bon accord mets-vins.', 'B1', 'Alimentation & Restauration'),
  ('Un producteur local', 'Personne qui cultive ou élève des produits près du lieu de vente.', 'Ce restaurant travaille avec des producteurs locaux.', 'B1', 'Alimentation & Restauration'),
  ('L''agriculture biologique', 'Méthode de production sans produits chimiques de synthèse.', 'L''agriculture biologique respecte davantage l''environnement.', 'B1', 'Alimentation & Restauration'),
  ('Les circuits courts alimentaires', 'Système limitant les intermédiaires entre producteur et consommateur.', 'Les circuits courts alimentaires soutiennent les agriculteurs locaux.', 'B1', 'Alimentation & Restauration'),
  ('La saisonnalité', 'Fait de consommer des produits en fonction de la saison.', 'Respecter la saisonnalité réduit l''impact environnemental.', 'B1', 'Alimentation & Restauration'),
  ('Un produit de saison', 'Aliment récolté durant sa période naturelle de production.', 'Les fraises sont un produit de saison en été.', 'B1', 'Alimentation & Restauration'),
  ('La provenance des aliments', 'Origine géographique d''un produit alimentaire.', 'L''étiquette indique la provenance des aliments.', 'B1', 'Alimentation & Restauration'),
  ('Un régime hyperprotéiné', 'Alimentation riche en protéines.', 'Ce sportif suit un régime hyperprotéiné.', 'B1', 'Alimentation & Restauration'),
  ('La malbouffe', 'Alimentation de mauvaise qualité nutritionnelle.', 'La malbouffe favorise certaines maladies.', 'B1', 'Alimentation & Restauration'),
  ('L''obésité', 'Excès important de masse corporelle lié à une mauvaise alimentation.', 'L''obésité est un enjeu majeur de santé publique.', 'B1', 'Alimentation & Restauration'),
  ('La dénutrition', 'Manque d''apports nutritionnels suffisants.', 'La dénutrition touche particulièrement les personnes âgées isolées.', 'B1', 'Alimentation & Restauration'),
  ('Un nutritionniste', 'Professionnel spécialisé dans l''équilibre alimentaire.', 'Elle consulte un nutritionniste pour perdre du poids.', 'B1', 'Alimentation & Restauration'),
  ('Les apports nutritionnels', 'Éléments nutritifs fournis par l''alimentation.', 'Les apports nutritionnels doivent être adaptés à chaque personne.', 'B1', 'Alimentation & Restauration'),
  ('Une carence alimentaire', 'Manque d''un ou plusieurs éléments nutritifs essentiels.', 'Une carence alimentaire peut provoquer de la fatigue.', 'B1', 'Alimentation & Restauration'),
  ('Le jeûne', 'Fait de se priver volontairement de nourriture pendant une période.', 'Certaines personnes pratiquent le jeûne intermittent.', 'B1', 'Alimentation & Restauration'),
  ('Une denrée alimentaire', 'Produit destiné à la consommation humaine.', 'Les denrées alimentaires périssables doivent être conservées au frais.', 'B1', 'Alimentation & Restauration'),
  ('L''agroalimentaire', 'Secteur économique lié à la transformation des produits agricoles.', 'L''agroalimentaire emploie de nombreux salariés en France.', 'B1', 'Alimentation & Restauration'),
  ('La restauration collective', 'Ensemble des services de repas servis dans les cantines, hôpitaux, etc.', 'La restauration collective doit respecter des normes strictes.', 'B1', 'Alimentation & Restauration'),
  ('Un traiteur', 'Professionnel qui prépare des repas pour des événements.', 'Nous avons fait appel à un traiteur pour le mariage.', 'B1', 'Alimentation & Restauration'),
  ('La souveraineté alimentaire', 'Capacité d''un pays à assurer son propre approvisionnement alimentaire.', 'La souveraineté alimentaire est un enjeu géopolitique majeur.', 'B2', 'Alimentation & Restauration'),
  ('La sécurité sanitaire des aliments', 'Ensemble des garanties contre les risques alimentaires.', 'L''ANSES veille à la sécurité sanitaire des aliments en France.', 'B2', 'Alimentation & Restauration'),
  ('Le principe de précaution', 'Obligation d''agir prudemment face à un risque incertain.', 'Le principe de précaution s''applique à certains additifs alimentaires.', 'B2', 'Alimentation & Restauration'),
  ('La traçabilité alimentaire', 'Capacité à retracer le parcours d''un aliment depuis sa production.', 'La traçabilité alimentaire permet de réagir vite en cas de crise sanitaire.', 'B2', 'Alimentation & Restauration'),
  ('Un rappel de produit', 'Retrait d''un aliment du marché en raison d''un danger.', 'Un rappel de produit a été lancé après la découverte d''une bactérie.', 'B2', 'Alimentation & Restauration'),
  ('La contamination croisée', 'Transfert de micro-organismes d''un aliment à un autre.', 'La contamination croisée est une cause fréquente de toxi-infection.', 'B2', 'Alimentation & Restauration'),
  ('Une toxi-infection alimentaire collective', 'Ensemble de cas de maladie liés à un même repas contaminé.', 'Une toxi-infection alimentaire collective a touché plusieurs élèves.', 'B2', 'Alimentation & Restauration'),
  ('Les organismes génétiquement modifiés', 'Organismes dont le patrimoine génétique a été modifié artificiellement.', 'La vente d''organismes génétiquement modifiés est très réglementée en Europe.', 'B2', 'Alimentation & Restauration'),
  ('L''étiquetage nutritionnel', 'Informations obligatoires sur la composition nutritionnelle d''un produit.', 'L''étiquetage nutritionnel Nutri-Score aide à comparer les produits.', 'B2', 'Alimentation & Restauration'),
  ('Le Nutri-Score', 'Système de notation indiquant la qualité nutritionnelle d''un produit.', 'Le Nutri-Score s''affiche désormais sur de nombreux emballages.', 'B2', 'Alimentation & Restauration'),
  ('La spéculation sur les matières premières', 'Achat et vente de denrées agricoles dans un but purement financier.', 'La spéculation sur les matières premières influence le prix du blé.', 'B2', 'Alimentation & Restauration'),
  ('La crise alimentaire', 'Situation de pénurie ou de forte hausse des prix des denrées.', 'La guerre a provoqué une crise alimentaire mondiale.', 'B2', 'Alimentation & Restauration'),
  ('L''insécurité alimentaire', 'Situation où une population n''a pas un accès suffisant à la nourriture.', 'L''insécurité alimentaire touche encore des millions de personnes.', 'B2', 'Alimentation & Restauration'),
  ('L''aide alimentaire', 'Distribution de nourriture aux personnes en difficulté.', 'Les Restos du Cœur distribuent une aide alimentaire chaque hiver.', 'B2', 'Alimentation & Restauration'),
  ('Une banque alimentaire', 'Organisme qui collecte et redistribue des denrées aux plus démunis.', 'La banque alimentaire dépend beaucoup des dons.', 'B2', 'Alimentation & Restauration'),
  ('Le gaspillage alimentaire industriel', 'Perte de nourriture à grande échelle liée à la production ou distribution.', 'La loi française oblige les supermarchés à limiter le gaspillage alimentaire industriel.', 'B2', 'Alimentation & Restauration'),
  ('L''agriculture intensive', 'Mode de production agricole visant un rendement maximal.', 'L''agriculture intensive est critiquée pour son impact environnemental.', 'B2', 'Alimentation & Restauration'),
  ('L''agroécologie', 'Approche agricole combinant productivité et respect de l''environnement.', 'L''agroécologie propose des alternatives aux pesticides.', 'B2', 'Alimentation & Restauration'),
  ('Les pesticides', 'Produits chimiques utilisés pour protéger les cultures.', 'L''usage des pesticides est encadré par la réglementation européenne.', 'B2', 'Alimentation & Restauration'),
  ('Le bien-être animal', 'Ensemble des conditions garantissant une vie digne aux animaux d''élevage.', 'Le bien-être animal devient un critère d''achat pour les consommateurs.', 'B2', 'Alimentation & Restauration'),
  ('L''élevage intensif', 'Méthode d''élevage visant une production maximale dans un espace réduit.', 'L''élevage intensif est de plus en plus contesté.', 'B2', 'Alimentation & Restauration'),
  ('Les protéines alternatives', 'Sources de protéines autres que la viande, comme les insectes ou les légumineuses.', 'Les protéines alternatives se développent face aux enjeux environnementaux.', 'B2', 'Alimentation & Restauration'),
  ('La néophobie alimentaire', 'Peur ou réticence à goûter de nouveaux aliments.', 'La néophobie alimentaire est fréquente chez les jeunes enfants.', 'B2', 'Alimentation & Restauration'),
  ('Les troubles du comportement alimentaire', 'Ensemble de pathologies liées à un rapport perturbé à la nourriture.', 'Les troubles du comportement alimentaire nécessitent souvent un suivi médical.', 'B2', 'Alimentation & Restauration'),
  ('L''anorexie', 'Trouble caractérisé par une restriction alimentaire extrême.', 'L''anorexie touche majoritairement les adolescentes.', 'B2', 'Alimentation & Restauration'),
  ('La boulimie', 'Trouble caractérisé par des crises de suralimentation suivies de compensation.', 'La boulimie peut avoir de graves conséquences sur la santé.', 'B2', 'Alimentation & Restauration'),
  ('Le microbiote intestinal', 'Ensemble des micro-organismes présents dans l''intestin, influencé par l''alimentation.', 'Une alimentation variée favorise un microbiote intestinal équilibré.', 'B2', 'Alimentation & Restauration'),
  ('La fermentation', 'Processus biologique utilisé pour transformer certains aliments.', 'Le pain et le fromage nécessitent une fermentation.', 'B2', 'Alimentation & Restauration'),
  ('Les probiotiques', 'Micro-organismes bénéfiques pour la santé intestinale.', 'Le yaourt contient naturellement des probiotiques.', 'B2', 'Alimentation & Restauration'),
  ('L''index glycémique', 'Mesure de l''impact d''un aliment sur le taux de sucre dans le sang.', 'Les aliments à faible index glycémique sont recommandés aux diabétiques.', 'B2', 'Alimentation & Restauration'),
  ('La désinformation alimentaire', 'Diffusion d''informations fausses ou trompeuses sur l''alimentation.', 'La désinformation alimentaire se répand facilement sur les réseaux sociaux.', 'B2', 'Alimentation & Restauration'),
  ('L''économie de la restauration', 'Secteur économique regroupant les activités liées à la restauration.', 'L''économie de la restauration a été fortement affectée par la crise sanitaire.', 'B2', 'Alimentation & Restauration');
