-- Réécriture du contenu CO/CE de l'Examen Blanc 1.
-- Le contenu précédent était factice : transcriptions "simulées",
-- et seulement 5 textes CE recyclés en boucle sur 20 questions.
-- EE et EO ne sont pas touchés (contenu déjà conforme au format officiel).

DO $$
DECLARE
  v_exam_id uuid;
BEGIN
  SELECT id INTO v_exam_id FROM public.exams WHERE slug = 'exam-1';

  IF v_exam_id IS NULL THEN
    RAISE EXCEPTION 'Exam with slug exam-1 not found';
  END IF;

  DELETE FROM public.exam_questions WHERE exam_id = v_exam_id AND section IN ('CO', 'CE');

  -- ===================== CO — 20 questions (order_index 0-19) =====================
  -- 0-9 : niveau A2, écoutées 2 fois. 10-19 : niveau B1, écoutées 1 fois (info implicite).
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, transcription, question, options, correct_answer, audio_url, max_plays)
  VALUES
  (v_exam_id, 'CO', 0, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Mesdames et messieurs, en raison d''un incident technique, le train à destination de Lyon partira avec vingt minutes de retard, quai 4.',
    'Quel est le problème annoncé ?',
    ARRAY['A) Un retard de train','B) Une grève','C) Un changement de quai','D) Une annulation'], 'A', '/mock/audio-co-1.mp3', 2),
  (v_exam_id, 'CO', 1, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Bonjour, pour renouveler votre carte d''identité, vous devez prendre rendez-vous en ligne et apporter un justificatif de domicile récent.',
    'Que doit apporter la personne ?',
    ARRAY['A) Une photo','B) Un justificatif de domicile','C) Un acte de naissance','D) Un timbre fiscal'], 'B', '/mock/audio-co-2.mp3', 2),
  (v_exam_id, 'CO', 2, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le cabinet du docteur Lambert est fermé aujourd''hui. En cas d''urgence, appelez le 15.',
    'Que faire en cas d''urgence ?',
    ARRAY['A) Se présenter au cabinet','B) Rappeler demain','C) Appeler le 15','D) Envoyer un message'], 'C', '/mock/audio-co-3.mp3', 2),
  (v_exam_id, 'CO', 3, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Chers clients, notre magasin ferme exceptionnellement à 19h ce soir pour inventaire.',
    'Pourquoi le magasin ferme-t-il plus tôt ?',
    ARRAY['A) Jour férié','B) Inventaire','C) Panne électrique','D) Grève du personnel'], 'B', '/mock/audio-co-4.mp3', 2),
  (v_exam_id, 'CO', 4, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Pour ouvrir un compte, il vous faut une pièce d''identité, un justificatif de domicile et un premier versement de 10 euros.',
    'Combien faut-il verser à l''ouverture du compte ?',
    ARRAY['A) 100 euros','B) 10 euros','C) 50 euros','D) Rien'], 'B', '/mock/audio-co-5.mp3', 2),
  (v_exam_id, 'CO', 5, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Bonjour, la réunion de parents d''élèves est reportée au vendredi 14 à 18 heures, salle B.',
    'Quand a lieu la réunion désormais ?',
    ARRAY['A) Jeudi 14 à 18h','B) Vendredi 14 à 18h','C) Vendredi 4 à 8h','D) Samedi 14 à 18h'], 'B', '/mock/audio-co-6.mp3', 2),
  (v_exam_id, 'CO', 6, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Attention, en raison de travaux, la ligne 3 du tramway est interrompue entre les stations Gare et Centre. Un bus de remplacement est mis en place.',
    'Comment les voyageurs peuvent-ils continuer leur trajet ?',
    ARRAY['A) À pied','B) En bus de remplacement','C) En taxi gratuit','D) Le trajet est annulé'], 'B', '/mock/audio-co-7.mp3', 2),
  (v_exam_id, 'CO', 7, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Tu peux m''envoyer le rapport avant midi ? Le client attend une réponse cet après-midi.',
    'Pourquoi le rapport est-il urgent ?',
    ARRAY['A) Le client attend une réponse','B) La réunion commence','C) L''ordinateur est en panne','D) Le collègue part en vacances'], 'A', '/mock/audio-co-8.mp3', 2),
  (v_exam_id, 'CO', 8, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Aujourd''hui, temps nuageux avec des averses en fin de journée. Pensez à prendre un parapluie.',
    'Que conseille l''animateur ?',
    ARRAY['A) Mettre de la crème solaire','B) Prendre un parapluie','C) Rester chez soi','D) Porter un manteau chaud'], 'B', '/mock/audio-co-9.mp3', 2),
  (v_exam_id, 'CO', 9, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'La pharmacie du centre est fermée le dimanche. La pharmacie de garde se trouve rue de la République.',
    'Où trouver une pharmacie ouverte le dimanche ?',
    ARRAY['A) Rue de la République','B) Fermé partout','C) À l''hôpital','D) Au centre commercial'], 'A', '/mock/audio-co-10.mp3', 2),
  (v_exam_id, 'CO', 10, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'L''appartement est disponible mais le loyer n''inclut pas les charges, qui s''élèvent à 50 euros par mois.',
    'Que faut-il comprendre sur le loyer ?',
    ARRAY['A) Les charges sont incluses','B) Les charges sont en plus','C) Il n''y a pas de charges','D) Le loyer est négociable'], 'B', '/mock/audio-co-11.mp3', 1),
  (v_exam_id, 'CO', 11, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Marc n''est pas encore arrivé, il a dû prendre le mauvais bus ce matin.',
    'Que sous-entend la phrase ?',
    ARRAY['A) Marc est en retard à cause du bus','B) Marc est malade','C) Marc a démissionné','D) Marc travaille à distance'], 'A', '/mock/audio-co-12.mp3', 1),
  (v_exam_id, 'CO', 12, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Votre dossier est incomplet. Merci de nous faire parvenir une copie de votre passeport avant le 15 du mois.',
    'Quelle est la conséquence si le document n''est pas envoyé ?',
    ARRAY['A) Le dossier reste incomplet','B) Le dossier est automatiquement validé','C) Un remboursement sera effectué','D) Rien ne se passe'], 'A', '/mock/audio-co-13.mp3', 1),
  (v_exam_id, 'CO', 13, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le poste m''intéresse, mais le salaire proposé est un peu bas pour l''expérience demandée.',
    'Quelle réserve exprime la personne ?',
    ARRAY['A) Le lieu de travail est trop loin','B) Le salaire est trop bas','C) Les horaires sont mauvais','D) Le poste ne l''intéresse pas'], 'B', '/mock/audio-co-14.mp3', 1),
  (v_exam_id, 'CO', 14, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Les passagers du vol AF204 sont invités à se présenter immédiatement à la porte 12, l''embarquement est sur le point de se terminer.',
    'Que doivent faire les passagers concernés ?',
    ARRAY['A) Attendre le prochain vol','B) Se présenter immédiatement à la porte','C) Récupérer leurs bagages','D) Aller au comptoir d''enregistrement'], 'B', '/mock/audio-co-15.mp3', 1),
  (v_exam_id, 'CO', 15, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Je tousse depuis trois jours et j''ai un peu de fièvre le soir. — Je vais vous prescrire un sirop et du repos, revenez si ça ne s''améliore pas.',
    'Que doit faire le patient si son état ne s''améliore pas ?',
    ARRAY['A) Prendre plus de sirop','B) Revenir voir le médecin','C) Aller à l''hôpital immédiatement','D) Arrêter le traitement'], 'B', '/mock/audio-co-16.mp3', 1),
  (v_exam_id, 'CO', 16, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'On va devoir revoir le planning, deux personnes de l''équipe sont en congé la semaine prochaine.',
    'Pourquoi faut-il revoir le planning ?',
    ARRAY['A) Deux employés seront absents','B) Le budget a changé','C) Le bureau déménage','D) Un nouveau projet commence'], 'A', '/mock/audio-co-17.mp3', 1),
  (v_exam_id, 'CO', 17, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Suite à de nombreuses demandes, les horaires d''ouverture du service état civil seront étendus le mercredi jusqu''à 18 heures à partir du mois prochain.',
    'Que va-t-il changer le mercredi ?',
    ARRAY['A) Le service sera fermé','B) Les horaires seront prolongés','C) Le service déménage','D) Il faudra prendre rendez-vous'], 'B', '/mock/audio-co-18.mp3', 1),
  (v_exam_id, 'CO', 18, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'J''ai postulé pour la formation, mais on m''a dit qu''il n''y avait plus de place cette session.',
    'Quel est le résultat de la candidature ?',
    ARRAY['A) Elle a été acceptée','B) Elle est en attente','C) Il n''y avait plus de place','D) Elle a été refusée pour un autre motif'], 'C', '/mock/audio-co-19.mp3', 1),
  (v_exam_id, 'CO', 19, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Je peux vous proposer un rendez-vous jeudi matin, mais si c''est urgent, il y a peut-être une place demain en fin d''après-midi.',
    'Quelle est la meilleure option si la personne est pressée ?',
    ARRAY['A) Jeudi matin','B) Demain en fin d''après-midi','C) Attendre la semaine prochaine','D) Aucun rendez-vous disponible'], 'B', '/mock/audio-co-20.mp3', 1);

  -- ===================== CE — 20 questions (order_index 20-39) =====================
  -- 10 textes distincts, 2 questions par texte, difficulté progressive.
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, texte, question, options, correct_answer)
  VALUES
  (v_exam_id, 'CE', 20, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La mairie informe les habitants que les demandes de carte d''identité et de passeport se font désormais uniquement sur rendez-vous, à prendre en ligne sur le site de la ville.',
    'Comment faut-il effectuer la demande ?',
    ARRAY['A) Sur rendez-vous en ligne','B) Sans rendez-vous','C) Par courrier','D) Par téléphone uniquement'], 'A'),
  (v_exam_id, 'CE', 21, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La mairie informe les habitants que les demandes de carte d''identité et de passeport se font désormais uniquement sur rendez-vous, à prendre en ligne sur le site de la ville.',
    'Quels documents concerne cet avis ?',
    ARRAY['A) Carte d''identité et passeport','B) Permis de conduire','C) Acte de mariage','D) Carte grise'], 'A'),
  (v_exam_id, 'CE', 22, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'En raison de travaux de rénovation, la bibliothèque municipale ouvrira exceptionnellement à 10h au lieu de 8h durant tout le mois de mars. Les horaires de fermeture restent inchangés.',
    'À quelle heure ouvrira la bibliothèque en mars ?',
    ARRAY['A) 8h','B) 9h','C) 10h','D) 11h'], 'C'),
  (v_exam_id, 'CE', 23, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'En raison de travaux de rénovation, la bibliothèque municipale ouvrira exceptionnellement à 10h au lieu de 8h durant tout le mois de mars. Les horaires de fermeture restent inchangés.',
    'Qu''est-ce qui explique ce changement ?',
    ARRAY['A) Un jour férié','B) Des travaux de rénovation','C) Un manque de personnel','D) Une grève'], 'B'),
  (v_exam_id, 'CE', 24, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'L''association Cœur Solidaire recherche des bénévoles disponibles le samedi matin pour accompagner des personnes âgées lors de leurs courses. Aucune expérience n''est requise.',
    'Quand les bénévoles sont-ils recherchés ?',
    ARRAY['A) Le samedi matin','B) Le dimanche soir','C) Tous les jours','D) Le vendredi après-midi'], 'A'),
  (v_exam_id, 'CE', 25, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'L''association Cœur Solidaire recherche des bénévoles disponibles le samedi matin pour accompagner des personnes âgées lors de leurs courses. Aucune expérience n''est requise.',
    'Quelle condition est demandée aux candidats ?',
    ARRAY['A) Avoir de l''expérience','B) Avoir un véhicule','C) Aucune expérience requise','D) Être disponible à temps plein'], 'C'),
  (v_exam_id, 'CE', 26, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Les voyageurs sont invités à vérifier les horaires de leurs trains avant leur départ en raison d''un mouvement social prévu ce jeudi. Certains trains pourront être supprimés ou retardés.',
    'Pourquoi faut-il vérifier les horaires ?',
    ARRAY['A) À cause d''un mouvement social','B) À cause de la météo','C) À cause de travaux','D) À cause d''un jour férié'], 'A'),
  (v_exam_id, 'CE', 27, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Les voyageurs sont invités à vérifier les horaires de leurs trains avant leur départ en raison d''un mouvement social prévu ce jeudi. Certains trains pourront être supprimés ou retardés.',
    'Quel jour est concerné ?',
    ARRAY['A) Mercredi','B) Jeudi','C) Vendredi','D) Samedi'], 'B'),
  (v_exam_id, 'CE', 28, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Restaurant Le Provençal recherche un(e) serveur/serveuse à temps partiel, disponible les week-ends. Expérience souhaitée mais débutants acceptés. Envoyer CV à contact@leprovencal.fr.',
    'Quel type de contrat est proposé ?',
    ARRAY['A) Temps plein','B) Temps partiel','C) Stage','D) Contrat d''apprentissage'], 'B'),
  (v_exam_id, 'CE', 29, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Restaurant Le Provençal recherche un(e) serveur/serveuse à temps partiel, disponible les week-ends. Expérience souhaitée mais débutants acceptés. Envoyer CV à contact@leprovencal.fr.',
    'Les débutants peuvent-ils postuler ?',
    ARRAY['A) Non, expérience obligatoire','B) Oui, ils sont acceptés','C) Seulement les étudiants','D) Seulement les plus de 25 ans'], 'B'),
  (v_exam_id, 'CE', 30, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le cabinet du docteur Fabre sera fermé pour congés du 5 au 20 août inclus. Pendant cette période, merci de contacter le docteur Nguyen au 04 91 22 33 44 pour toute urgence.',
    'Que faire en cas d''urgence pendant la fermeture ?',
    ARRAY['A) Attendre le retour du docteur Fabre','B) Contacter le docteur Nguyen','C) Aller directement à l''hôpital','D) Appeler le cabinet quand même'], 'B'),
  (v_exam_id, 'CE', 31, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le cabinet du docteur Fabre sera fermé pour congés du 5 au 20 août inclus. Pendant cette période, merci de contacter le docteur Nguyen au 04 91 22 33 44 pour toute urgence.',
    'Jusqu''à quelle date le cabinet est-il fermé ?',
    ARRAY['A) Le 5 août','B) Le 15 août','C) Le 20 août','D) Toute l''année'], 'C'),
  (v_exam_id, 'CE', 32, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le syndic rappelle aux résidents que les containers à ordures doivent être sortis la veille au soir et rentrés le lendemain matin, sous peine d''amende infligée par la mairie.',
    'Que risquent les résidents qui ne respectent pas la règle ?',
    ARRAY['A) Rien','B) Une amende','C) L''exclusion de l''immeuble','D) Une réunion obligatoire'], 'B'),
  (v_exam_id, 'CE', 33, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le syndic rappelle aux résidents que les containers à ordures doivent être sortis la veille au soir et rentrés le lendemain matin, sous peine d''amende infligée par la mairie.',
    'Quand faut-il sortir les containers ?',
    ARRAY['A) Le matin même','B) La veille au soir','C) Le jour même à midi','D) Une fois par semaine'], 'B'),
  (v_exam_id, 'CE', 34, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le centre de formation Avenir Langues propose des cours de français financés par le CPF, sous réserve d''un nombre d''heures suffisant sur le compte du candidat. Les inscriptions se font uniquement en ligne, deux semaines avant le début de la session.',
    'Quelle condition est nécessaire pour bénéficier du financement ?',
    ARRAY['A) Être inscrit à Pôle emploi','B) Avoir un nombre d''heures suffisant sur le CPF','C) Avoir moins de 25 ans','D) Payer un acompte'], 'B'),
  (v_exam_id, 'CE', 35, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le centre de formation Avenir Langues propose des cours de français financés par le CPF, sous réserve d''un nombre d''heures suffisant sur le compte du candidat. Les inscriptions se font uniquement en ligne, deux semaines avant le début de la session.',
    'Comment s''inscrire à la formation ?',
    ARRAY['A) Par téléphone','B) En agence','C) En ligne uniquement','D) Par courrier'], 'C'),
  (v_exam_id, 'CE', 36, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Selon une étude récente, de plus en plus de Français choisissent de se déplacer à vélo pour se rendre au travail, notamment grâce au développement des pistes cyclables dans les grandes villes.',
    'Quel facteur favorise l''usage du vélo selon l''article ?',
    ARRAY['A) Le prix de l''essence','B) Le développement des pistes cyclables','C) Une nouvelle loi','D) La météo favorable'], 'B'),
  (v_exam_id, 'CE', 37, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Selon une étude récente, de plus en plus de Français choisissent de se déplacer à vélo pour se rendre au travail, notamment grâce au développement des pistes cyclables dans les grandes villes.',
    'Qui utilise de plus en plus le vélo selon l''article ?',
    ARRAY['A) Les touristes','B) Les Français pour aller travailler','C) Les enfants pour aller à l''école','D) Les personnes âgées uniquement'], 'B'),
  (v_exam_id, 'CE', 38, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le locataire est informé que le bail ne sera pas renouvelé automatiquement à son terme ; un préavis de trois mois doit être respecté par les deux parties souhaitant y mettre fin.',
    'Que doit faire une personne qui souhaite ne pas renouveler le bail ?',
    ARRAY['A) Rien, c''est automatique','B) Respecter un préavis de trois mois','C) Payer une pénalité','D) Attendre l''accord du voisinage'], 'B'),
  (v_exam_id, 'CE', 39, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le locataire est informé que le bail ne sera pas renouvelé automatiquement à son terme ; un préavis de trois mois doit être respecté par les deux parties souhaitant y mettre fin.',
    'Le renouvellement du bail est-il automatique ?',
    ARRAY['A) Oui, toujours','B) Non','C) Seulement pour le propriétaire','D) Seulement la première année'], 'B');

END $$;
