-- Examen Blanc 3 : thème "Vie sociale, santé, logement", niveau B1-B2.
-- Contenu 100% neuf.

DO $$
DECLARE
  v_exam_id uuid;
BEGIN
  INSERT INTO public.exams (label, slug, is_active, duration_co, duration_ce, duration_ee, duration_eo)
  VALUES ('Examen Blanc 3', 'exam-3', false, 20, 30, 30, 10)
  RETURNING id INTO v_exam_id;

  -- ===================== CO — 20 questions (order_index 0-19) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, transcription, question, options, correct_answer, audio_url, max_plays)
  VALUES
  (v_exam_id, 'CO', 0, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le cabinet médical vous informe que le docteur Rousseau ne pourra pas assurer les consultations cette semaine. Merci de contacter le secrétariat pour un report.',
    'Que faut-il faire ?',
    ARRAY['A) Contacter le secrétariat','B) Attendre son retour','C) Aller directement au cabinet','D) Annuler définitivement'], 'A', '/mock/audio-co-41.mp3', 2),
  (v_exam_id, 'CO', 1, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Bonjour, je vous confirme la visite de l''appartement rue des Lilas ce samedi à 11 heures.',
    'Quand a lieu la visite ?',
    ARRAY['A) Samedi à 11h','B) Vendredi à 11h','C) Samedi à 15h','D) Dimanche matin'], 'A', '/mock/audio-co-42.mp3', 2),
  (v_exam_id, 'CO', 2, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Excusez-moi de vous déranger, pourriez-vous baisser un peu la musique ce soir, mon bébé dort.',
    'Que demande la personne ?',
    ARRAY['A) D''arrêter la musique','B) De baisser la musique','C) De déménager','D) D''appeler la police'], 'B', '/mock/audio-co-43.mp3', 2),
  (v_exam_id, 'CO', 3, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Pour vous inscrire au club de tennis, il faut fournir un certificat médical et régler la cotisation annuelle de 80 euros.',
    'Que faut-il fournir pour l''inscription ?',
    ARRAY['A) Une photo uniquement','B) Un certificat médical','C) Un justificatif de domicile','D) Rien de particulier'], 'B', '/mock/audio-co-44.mp3', 2),
  (v_exam_id, 'CO', 4, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Votre ordonnance est prête, vous pouvez venir la chercher à la pharmacie avant 19 heures.',
    'Jusqu''à quelle heure peut-on récupérer l''ordonnance ?',
    ARRAY['A) 17 heures','B) 18 heures','C) 19 heures','D) 20 heures'], 'C', '/mock/audio-co-45.mp3', 2),
  (v_exam_id, 'CO', 5, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'L''association du quartier organise une fête des voisins samedi prochain à partir de 18 heures, chacun apporte un plat à partager.',
    'Que doit apporter chaque participant ?',
    ARRAY['A) Une boisson','B) Un plat à partager','C) De l''argent','D) Rien'], 'B', '/mock/audio-co-46.mp3', 2),
  (v_exam_id, 'CO', 6, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Nous emménageons au troisième étage la semaine prochaine, n''hésitez pas à venir vous présenter.',
    'Que propose la personne ?',
    ARRAY['A) De se présenter aux nouveaux voisins','B) D''organiser une fête','C) De vendre des meubles','D) De louer son appartement'], 'A', '/mock/audio-co-47.mp3', 2),
  (v_exam_id, 'CO', 7, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'La salle de sport sera fermée exceptionnellement dimanche pour désinfection, réouverture lundi comme d''habitude.',
    'Pourquoi la salle est-elle fermée ?',
    ARRAY['A) Travaux','B) Désinfection','C) Jour férié','D) Manque de personnel'], 'B', '/mock/audio-co-48.mp3', 2),
  (v_exam_id, 'CO', 8, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Vos résultats d''analyses sont normaux, il n''y a pas lieu de s''inquiéter, on se revoit dans six mois pour un contrôle.',
    'Quand doit avoir lieu le prochain contrôle ?',
    ARRAY['A) Dans un mois','B) Dans six mois','C) Dans un an','D) Il n''y en a pas'], 'B', '/mock/audio-co-49.mp3', 2),
  (v_exam_id, 'CO', 9, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le plombier passera demain matin entre 8 et 10 heures pour réparer la fuite d''eau signalée.',
    'Que va faire le plombier ?',
    ARRAY['A) Installer une nouvelle cuisine','B) Réparer une fuite d''eau','C) Changer les fenêtres','D) Repeindre la salle de bain'], 'B', '/mock/audio-co-50.mp3', 2),
  (v_exam_id, 'CO', 10, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Vos douleurs peuvent être liées au stress, mais je préfère vous prescrire des examens complémentaires pour écarter d''autres causes.',
    'Pourquoi le médecin prescrit-il des examens ?',
    ARRAY['A) Pour confirmer le diagnostic de stress','B) Pour écarter d''autres causes possibles','C) Parce que c''est obligatoire','D) Parce que le patient l''a demandé'], 'B', '/mock/audio-co-51.mp3', 1),
  (v_exam_id, 'CO', 11, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'On a bien reçu votre lettre concernant le bruit, mais sachez que les travaux devraient se terminer d''ici la fin du mois.',
    'Que peut-on comprendre de cette réponse ?',
    ARRAY['A) Les travaux sont terminés','B) Les travaux vont bientôt se terminer','C) Les travaux ne s''arrêteront jamais','D) Il n''y a pas eu de travaux'], 'B', '/mock/audio-co-52.mp3', 1),
  (v_exam_id, 'CO', 12, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'L''appartement vous plaît, mais sachez que le propriétaire a déjà reçu plusieurs autres dossiers de candidature.',
    'Que sous-entend l''agent ?',
    ARRAY['A) Le logement est déjà loué','B) D''autres candidats sont aussi intéressés','C) Le loyer va augmenter','D) La visite est annulée'], 'B', '/mock/audio-co-53.mp3', 1),
  (v_exam_id, 'CO', 13, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Suite à votre consultation, je vous invite à consulter un spécialiste si les symptômes persistent au-delà d''une semaine.',
    'Que doit faire le patient si les symptômes continuent ?',
    ARRAY['A) Attendre encore un mois','B) Consulter un spécialiste','C) Changer de traitement seul','D) Ne rien faire'], 'B', '/mock/audio-co-54.mp3', 1),
  (v_exam_id, 'CO', 14, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'On a besoin de bénévoles supplémentaires, mais uniquement ceux qui peuvent s''engager sur plusieurs mois.',
    'Quelle condition est demandée aux nouveaux bénévoles ?',
    ARRAY['A) Avoir de l''expérience','B) S''engager sur plusieurs mois','C) Être disponible tous les jours','D) Payer une cotisation'], 'B', '/mock/audio-co-55.mp3', 1),
  (v_exam_id, 'CO', 15, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le syndic informe que les travaux de ravalement débuteront en septembre, ce qui pourra occasionner un peu de bruit en journée.',
    'Que faut-il anticiper à partir de septembre ?',
    ARRAY['A) Une coupure d''eau','B) Du bruit en journée','C) La fermeture de l''immeuble','D) Une augmentation des charges'], 'B', '/mock/audio-co-56.mp3', 1),
  (v_exam_id, 'CO', 16, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le traitement fonctionne bien, mais il est important de ne pas arrêter avant la fin de la prescription, même si vous vous sentez mieux.',
    'Que recommande le médecin ?',
    ARRAY['A) D''arrêter dès que possible','B) De continuer le traitement jusqu''au bout','C) De doubler la dose','D) De changer de médicament'], 'B', '/mock/audio-co-57.mp3', 1),
  (v_exam_id, 'CO', 17, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le dossier est complet, mais le propriétaire souhaite rencontrer les candidats avant de donner sa réponse définitive.',
    'Que va-t-il se passer avant la décision finale ?',
    ARRAY['A) Une rencontre avec le propriétaire','B) La signature immédiate du bail','C) Un refus automatique','D) Une nouvelle visite du logement'], 'A', '/mock/audio-co-58.mp3', 1),
  (v_exam_id, 'CO', 18, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Votre demande est en cours de traitement, mais le délai peut être plus long que d''habitude en raison du nombre de dossiers reçus.',
    'Pourquoi le délai est-il plus long que prévu ?',
    ARRAY['A) Un problème administratif','B) Le nombre important de dossiers','C) Un manque de personnel','D) La demande a été refusée'], 'B', '/mock/audio-co-59.mp3', 1),
  (v_exam_id, 'CO', 19, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Les nouveaux horaires du marché seront affichés bientôt, mais il est probable que le jour change aussi.',
    'Que pourrait changer concernant le marché ?',
    ARRAY['A) Seulement les horaires','B) Les horaires et probablement le jour','C) Rien ne va changer','D) Le marché va fermer définitivement'], 'B', '/mock/audio-co-60.mp3', 1);

  -- ===================== CE — 20 questions (order_index 20-39) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, texte, question, options, correct_answer)
  VALUES
  (v_exam_id, 'CE', 20, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La résidence Les Tilleuls informe ses locataires que la piscine commune sera fermée pour entretien du 5 au 12 juillet.',
    'Que va-t-il se passer avec la piscine ?',
    ARRAY['A) Elle sera fermée pour entretien','B) Elle sera définitivement fermée','C) Elle sera agrandie','D) Elle change d''horaires'], 'A'),
  (v_exam_id, 'CE', 21, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La résidence Les Tilleuls informe ses locataires que la piscine commune sera fermée pour entretien du 5 au 12 juillet.',
    'Pendant combien de jours la piscine sera-t-elle fermée ?',
    ARRAY['A) 3 jours','B) 7 jours','C) 12 jours','D) 1 mois'], 'B'),
  (v_exam_id, 'CE', 22, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le centre médical propose désormais la prise de rendez-vous en ligne, disponible 24h/24, en plus de l''accueil téléphonique habituel.',
    'Quelle nouveauté propose le centre médical ?',
    ARRAY['A) Des consultations gratuites','B) La prise de rendez-vous en ligne','C) Un nouveau médecin','D) Des horaires étendus'], 'B'),
  (v_exam_id, 'CE', 23, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le centre médical propose désormais la prise de rendez-vous en ligne, disponible 24h/24, en plus de l''accueil téléphonique habituel.',
    'Quand ce service en ligne est-il disponible ?',
    ARRAY['A) Uniquement le matin','B) 24h/24','C) Seulement le week-end','D) Sur rendez-vous téléphonique'], 'B'),
  (v_exam_id, 'CE', 24, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'L''association d''aide au logement propose un accompagnement gratuit pour les démarches administratives liées à la recherche d''un appartement.',
    'Que propose l''association ?',
    ARRAY['A) Des logements gratuits','B) Un accompagnement pour les démarches','C) Des prêts bancaires','D) Des meubles gratuits'], 'B'),
  (v_exam_id, 'CE', 25, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'L''association d''aide au logement propose un accompagnement gratuit pour les démarches administratives liées à la recherche d''un appartement.',
    'Ce service est-il payant ?',
    ARRAY['A) Oui, cher','B) Oui, un peu','C) Non, il est gratuit','D) Cela dépend des revenus'], 'C'),
  (v_exam_id, 'CE', 26, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le syndic de copropriété rappelle que les animaux domestiques sont autorisés dans l''immeuble, à condition qu''ils ne causent pas de nuisances sonores.',
    'Les animaux sont-ils autorisés dans l''immeuble ?',
    ARRAY['A) Non, interdits','B) Oui, sous condition','C) Oui, sans condition','D) Seulement les chats'], 'B'),
  (v_exam_id, 'CE', 27, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le syndic de copropriété rappelle que les animaux domestiques sont autorisés dans l''immeuble, à condition qu''ils ne causent pas de nuisances sonores.',
    'Quelle condition est posée ?',
    ARRAY['A) Payer une taxe','B) Ne pas causer de nuisances sonores','C) Avoir moins de deux animaux','D) Les déclarer au syndic'], 'B'),
  (v_exam_id, 'CE', 28, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La mutuelle informe ses adhérents que le remboursement des lunettes est désormais plafonné à 150 euros tous les deux ans.',
    'À combien est plafonné le remboursement des lunettes ?',
    ARRAY['A) 100 euros','B) 150 euros','C) 200 euros','D) Illimité'], 'B'),
  (v_exam_id, 'CE', 29, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La mutuelle informe ses adhérents que le remboursement des lunettes est désormais plafonné à 150 euros tous les deux ans.',
    'À quelle fréquence ce remboursement est-il possible ?',
    ARRAY['A) Chaque année','B) Tous les deux ans','C) Une seule fois','D) Tous les mois'], 'B'),
  (v_exam_id, 'CE', 30, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le centre social organise des cours de français gratuits pour les nouveaux arrivants, tous les mardis et jeudis matin.',
    'À qui s''adressent ces cours ?',
    ARRAY['A) Aux enfants uniquement','B) Aux nouveaux arrivants','C) Aux personnes âgées','D) Aux étudiants uniquement'], 'B'),
  (v_exam_id, 'CE', 31, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le centre social organise des cours de français gratuits pour les nouveaux arrivants, tous les mardis et jeudis matin.',
    'Quels jours ont lieu les cours ?',
    ARRAY['A) Lundi et mercredi','B) Mardi et jeudi matin','C) Le week-end','D) Tous les jours'], 'B'),
  (v_exam_id, 'CE', 32, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le bailleur social informe que la liste d''attente pour un logement social de type T3 dans le quartier est actuellement d''environ dix-huit mois.',
    'Quel type de logement est concerné ?',
    ARRAY['A) T1','B) T2','C) T3','D) T4'], 'C'),
  (v_exam_id, 'CE', 33, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le bailleur social informe que la liste d''attente pour un logement social de type T3 dans le quartier est actuellement d''environ dix-huit mois.',
    'Quelle est la durée d''attente estimée ?',
    ARRAY['A) 6 mois','B) 12 mois','C) 18 mois','D) 24 mois'], 'C'),
  (v_exam_id, 'CE', 34, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'L''hôpital rappelle aux patients que les urgences ne doivent être utilisées qu''en cas de réelle urgence médicale, sous peine d''attente prolongée pour tous.',
    'Pourquoi cette recommandation est-elle faite ?',
    ARRAY['A) Pour réduire les coûts','B) Pour éviter une attente prolongée pour tous','C) Pour fermer les urgences','D) Pour former le personnel'], 'B'),
  (v_exam_id, 'CE', 35, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'L''hôpital rappelle aux patients que les urgences ne doivent être utilisées qu''en cas de réelle urgence médicale, sous peine d''attente prolongée pour tous.',
    'Quand faut-il aller aux urgences selon le texte ?',
    ARRAY['A) Pour tout problème de santé','B) Seulement en cas de réelle urgence','C) Jamais','D) Uniquement la nuit'], 'B'),
  (v_exam_id, 'CE', 36, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Une étude montre que le nombre de personnes vivant seules dans les grandes villes a fortement augmenté ces dernières années, un phénomène lié notamment à l''évolution des modes de vie.',
    'Quel phénomène est décrit dans le texte ?',
    ARRAY['A) La baisse de la population urbaine','B) L''augmentation des personnes vivant seules','C) La hausse du chômage','D) Le vieillissement de la population'], 'B'),
  (v_exam_id, 'CE', 37, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Une étude montre que le nombre de personnes vivant seules dans les grandes villes a fortement augmenté ces dernières années, un phénomène lié notamment à l''évolution des modes de vie.',
    'À quoi ce phénomène est-il lié selon le texte ?',
    ARRAY['A) Au prix des logements','B) À l''évolution des modes de vie','C) Aux politiques publiques','D) À la météo'], 'B'),
  (v_exam_id, 'CE', 38, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le bailleur informe le locataire que le dépôt de garantie ne sera restitué qu''après un état des lieux de sortie sans réserve, dans un délai maximal de deux mois.',
    'Quand le dépôt de garantie sera-t-il restitué ?',
    ARRAY['A) Immédiatement','B) Après un état des lieux sans réserve, sous deux mois','C) Jamais','D) Uniquement si le locataire le demande'], 'B'),
  (v_exam_id, 'CE', 39, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le bailleur informe le locataire que le dépôt de garantie ne sera restitué qu''après un état des lieux de sortie sans réserve, dans un délai maximal de deux mois.',
    'Que faut-il pour récupérer le dépôt sans délai supplémentaire ?',
    ARRAY['A) Un état des lieux sans réserve','B) Payer une pénalité','C) Signer un nouveau bail','D) Rien de particulier'], 'A');

  -- ===================== EE — 2 questions (order_index 40-41) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, prompt, min_words, max_time)
  VALUES
  (v_exam_id, 'EE', 40, 'writing', 'Section A : Rédiger un message simple et clair.',
    'Vous avez un problème de plomberie dans votre logement. Écrivez un message à votre propriétaire pour décrire le problème et demander une intervention rapide. (40 mots minimum)',
    40, 10),
  (v_exam_id, 'EE', 41, 'writing', 'Section B : Présenter et justifier votre engagement.',
    'Vous souhaitez rejoindre une association de quartier. Écrivez un message au responsable pour vous présenter et expliquer les raisons de votre engagement. (100 mots minimum)',
    100, 20);

  -- ===================== EO — 2 questions (order_index 42-43) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, prompt, prep_time, speak_time)
  VALUES
  (v_exam_id, 'EO', 42, 'speaking', 'Section A : Poser des questions pour obtenir des informations.',
    'Vous appelez votre médecin pour prendre un rendez-vous et expliquer brièvement vos symptômes.',
    1, 5),
  (v_exam_id, 'EO', 43, 'speaking', 'Section B : Exprimer et défendre un point de vue.',
    'Un ami hésite à s''installer dans votre quartier. Convainquez-le en présentant les avantages d''y habiter.',
    1, 5);

END $$;
