-- Item 7quater du plan vocabulaire 1500 mots : compléter la catégorie 'Travail'
-- 56 -> 125 mots (69 nouveaux mots, répartis A1:10 A2:19 B1:21 B2:19).
-- Dernière des 5 catégories existantes à être complétée à 125 mots.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 556 mots déjà en base (218 originaux + 116 Vie Sociale + 72 Administration + 75 Logement + 75 Santé)
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Une réunion', 'Rencontre professionnelle pour échanger sur un sujet.', 'J''ai une réunion à 14h avec mon équipe.', 'A1', 'Travail'),
  ('Un ordinateur', 'Appareil utilisé pour travailler et communiquer.', 'Mon ordinateur est en panne aujourd''hui.', 'A1', 'Travail'),
  ('Un e-mail', 'Message envoyé par internet.', 'Je vous envoie le document par e-mail.', 'A1', 'Travail'),
  ('Une pause', 'Court moment de repos pendant le travail.', 'Nous prenons une pause à midi.', 'A1', 'Travail'),
  ('Un salaire', 'Somme d''argent versée en échange d''un travail.', 'Mon salaire est versé le 30 de chaque mois.', 'A1', 'Travail'),
  ('Une équipe', 'Groupe de personnes qui travaillent ensemble.', 'Notre équipe compte huit personnes.', 'A1', 'Travail'),
  ('Un uniforme', 'Vêtement de travail identique pour tous les employés.', 'Les cuisiniers portent un uniforme blanc.', 'A1', 'Travail'),
  ('Un badge', 'Carte permettant d''entrer dans un lieu de travail.', 'N''oubliez pas votre badge pour entrer dans les locaux.', 'A1', 'Travail'),
  ('Un client', 'Personne qui achète un produit ou un service.', 'Ce client vient chaque semaine à la boutique.', 'A1', 'Travail'),
  ('Un magasin', 'Lieu où l''on vend des produits.', 'Elle travaille dans un magasin de vêtements.', 'A1', 'Travail'),
  ('Le planning', 'Emploi du temps qui organise les tâches et horaires.', 'Consultez le planning affiché dans la salle de pause.', 'A2', 'Travail'),
  ('Une astreinte', 'Période où l''on doit rester disponible en dehors des heures normales.', 'Il est d''astreinte ce week-end.', 'A2', 'Travail'),
  ('La formation professionnelle', 'Ensemble des cours suivis pour développer ses compétences.', 'L''entreprise propose une formation professionnelle chaque année.', 'A2', 'Travail'),
  ('Un tuteur', 'Personne qui accompagne un nouvel employé ou un apprenti.', 'Mon tuteur m''aide à comprendre les procédures.', 'A2', 'Travail'),
  ('Un poste', 'Emploi précis occupé dans une entreprise.', 'Ce poste demande deux ans d''expérience.', 'A2', 'Travail'),
  ('La hiérarchie', 'Organisation des niveaux de responsabilité dans une entreprise.', 'Il faut respecter la hiérarchie pour valider ce projet.', 'A2', 'Travail'),
  ('Un supérieur hiérarchique', 'Personne qui dirige directement un salarié.', 'Mon supérieur hiérarchique valide mes congés.', 'A2', 'Travail'),
  ('Un objectif professionnel', 'But fixé à atteindre dans le cadre du travail.', 'Mon objectif professionnel est d''obtenir une promotion.', 'A2', 'Travail'),
  ('Un entretien annuel', 'Rendez-vous annuel pour évaluer le travail d''un salarié.', 'L''entretien annuel a lieu chaque mois de janvier.', 'A2', 'Travail'),
  ('La productivité', 'Quantité de travail réalisée dans un temps donné.', 'La nouvelle organisation a amélioré la productivité.', 'A2', 'Travail'),
  ('Le secteur d''activité', 'Domaine économique dans lequel une entreprise travaille.', 'Elle travaille dans le secteur de la santé.', 'A2', 'Travail'),
  ('Une compétence', 'Capacité à réaliser une tâche précise.', 'La maîtrise du français est une compétence recherchée.', 'A2', 'Travail'),
  ('Un CV en ligne', 'Curriculum vitae publié sur un site internet.', 'Beaucoup de recruteurs consultent les CV en ligne.', 'A2', 'Travail'),
  ('Un job d''été', 'Emploi temporaire pendant les vacances scolaires.', 'Elle a trouvé un job d''été dans un camping.', 'A2', 'Travail'),
  ('Un emploi saisonnier', 'Emploi limité à une période de l''année.', 'La récolte du raisin est un emploi saisonnier.', 'A2', 'Travail'),
  ('Le marché du travail', 'Ensemble des offres et demandes d''emploi.', 'Le marché du travail est difficile dans certaines régions.', 'A2', 'Travail'),
  ('Un réseau professionnel', 'Ensemble de contacts utiles dans son domaine.', 'LinkedIn permet de développer son réseau professionnel.', 'A2', 'Travail'),
  ('Un accident du travail', 'Blessure survenue pendant l''exercice du travail.', 'Il a eu un accident du travail sur le chantier.', 'A2', 'Travail'),
  ('Les conditions de travail', 'Ensemble des éléments qui définissent l''environnement professionnel.', 'Les conditions de travail se sont améliorées cette année.', 'A2', 'Travail'),
  ('Le contrat aidé', 'Contrat de travail bénéficiant d''une aide financière de l''État.', 'Elle a été embauchée en contrat aidé.', 'B1', 'Travail'),
  ('Le CDI intérimaire', 'Contrat à durée indéterminée pour des missions d''intérim successives.', 'Le CDI intérimaire lui garantit un revenu stable.', 'B1', 'Travail'),
  ('L''intérim', 'Travail temporaire effectué via une agence spécialisée.', 'Il travaille en intérim depuis six mois.', 'B1', 'Travail'),
  ('Une agence d''intérim', 'Entreprise qui propose des missions temporaires.', 'L''agence d''intérim m''a trouvé une mission dès la semaine prochaine.', 'B1', 'Travail'),
  ('Le portage salarial', 'Statut permettant d''exercer une activité indépendante tout en étant salarié.', 'Le portage salarial combine liberté et protection sociale.', 'B1', 'Travail'),
  ('Le statut d''auto-entrepreneur', 'Régime simplifié pour exercer une activité indépendante.', 'Elle a créé son activité sous le statut d''auto-entrepreneur.', 'B1', 'Travail'),
  ('Le chiffre d''affaires', 'Montant total des ventes réalisées par une entreprise.', 'Le chiffre d''affaires a augmenté de 10% cette année.', 'B1', 'Travail'),
  ('La reconversion professionnelle', 'Changement de métier ou de secteur d''activité.', 'Il envisage une reconversion professionnelle dans l''informatique.', 'B1', 'Travail'),
  ('Le compte personnel de formation', 'Dispositif permettant de financer des formations tout au long de la carrière.', 'Elle utilise son compte personnel de formation pour apprendre l''anglais.', 'B1', 'Travail'),
  ('La validation des acquis de l''expérience', 'Procédure permettant d''obtenir un diplôme grâce à son expérience professionnelle.', 'La validation des acquis de l''expérience lui a permis d''obtenir son diplôme.', 'B1', 'Travail'),
  ('Le harcèlement au travail', 'Comportements répétés qui nuisent à un salarié sur son lieu de travail.', 'L''entreprise a mis en place une procédure contre le harcèlement au travail.', 'B1', 'Travail'),
  ('Les risques professionnels', 'Dangers liés à l''exercice d''un métier.', 'La formation sécurité présente les risques professionnels du poste.', 'B1', 'Travail'),
  ('L''égalité salariale', 'Principe selon lequel hommes et femmes doivent recevoir le même salaire pour le même travail.', 'L''égalité salariale reste un enjeu important en France.', 'B1', 'Travail'),
  ('Le comité d''entreprise', 'Ancienne instance représentant les salariés, remplacée par le CSE.', 'Le comité d''entreprise organisait des activités pour les salariés.', 'B1', 'Travail'),
  ('Le délégué syndical', 'Représentant d''un syndicat au sein d''une entreprise.', 'Le délégué syndical défend les intérêts des salariés.', 'B1', 'Travail'),
  ('La négociation collective', 'Discussion entre employeurs et syndicats pour fixer des règles communes.', 'La négociation collective a permis une augmentation des salaires.', 'B1', 'Travail'),
  ('L''accord d''entreprise', 'Accord négocié spécifiquement au sein d''une entreprise.', 'L''accord d''entreprise fixe les règles du télétravail.', 'B1', 'Travail'),
  ('La rémunération variable', 'Partie du salaire qui dépend des résultats obtenus.', 'Sa rémunération variable dépend des ventes réalisées.', 'B1', 'Travail'),
  ('Un avantage en nature', 'Bien ou service fourni par l''employeur en plus du salaire.', 'La voiture de fonction est un avantage en nature.', 'B1', 'Travail'),
  ('La mutuelle d''entreprise', 'Complémentaire santé proposée par l''employeur.', 'La mutuelle d''entreprise est obligatoire depuis 2016.', 'B1', 'Travail'),
  ('Le comité d''hygiène et de sécurité', 'Instance chargée de la prévention des risques au travail.', 'Le comité d''hygiène et de sécurité inspecte régulièrement l''atelier.', 'B1', 'Travail'),
  ('Le dialogue social', 'Ensemble des échanges entre employeurs, salariés et syndicats.', 'Le dialogue social permet d''anticiper les conflits.', 'B2', 'Travail'),
  ('La négociation annuelle obligatoire', 'Discussion annuelle obligatoire sur les salaires entre employeurs et syndicats.', 'La négociation annuelle obligatoire porte notamment sur les salaires.', 'B2', 'Travail'),
  ('Le plafond de verre', 'Obstacle invisible qui freine la progression des femmes dans la hiérarchie.', 'Le plafond de verre limite encore l''accès des femmes aux postes de direction.', 'B2', 'Travail'),
  ('La discrimination à l''embauche', 'Traitement inégal d''un candidat en raison de critères non professionnels.', 'La discrimination à l''embauche est punie par la loi.', 'B2', 'Travail'),
  ('L''index de l''égalité professionnelle', 'Outil mesurant les écarts salariaux entre femmes et hommes dans une entreprise.', 'L''index de l''égalité professionnelle doit être publié chaque année.', 'B2', 'Travail'),
  ('La responsabilité sociale de l''entreprise', 'Engagement d''une entreprise à agir de façon éthique.', 'La responsabilité sociale de l''entreprise inclut le respect de l''environnement.', 'B2', 'Travail'),
  ('Le management', 'Ensemble des méthodes utilisées pour diriger une équipe.', 'Le management participatif favorise l''implication des salariés.', 'B2', 'Travail'),
  ('Le turnover', 'Taux de renouvellement du personnel dans une entreprise.', 'Un turnover élevé peut révéler un problème d''organisation.', 'B2', 'Travail'),
  ('L''absentéisme', 'Fréquence des absences des salariés au travail.', 'L''absentéisme a augmenté depuis la mise en place du nouveau planning.', 'B2', 'Travail'),
  ('La qualité de vie au travail', 'Ensemble des conditions favorisant le bien-être des salariés.', 'L''entreprise a lancé un programme sur la qualité de vie au travail.', 'B2', 'Travail'),
  ('La flexibilité du travail', 'Capacité à adapter les horaires ou le lieu de travail.', 'La flexibilité du travail attire de plus en plus de candidats.', 'B2', 'Travail'),
  ('L''ubérisation', 'Transformation de certains secteurs par des plateformes numériques.', 'L''ubérisation a bouleversé le secteur des transports.', 'B2', 'Travail'),
  ('Le statut de travailleur indépendant', 'Situation d''une personne qui exerce une activité sans lien de subordination.', 'Les livreurs à vélo ont souvent le statut de travailleur indépendant.', 'B2', 'Travail'),
  ('La subordination juridique', 'Lien de dépendance caractérisant la relation entre salarié et employeur.', 'La subordination juridique distingue le salarié du travailleur indépendant.', 'B2', 'Travail'),
  ('Le prud''hommes', 'Tribunal chargé de juger les litiges entre employeurs et salariés.', 'Elle a saisi les prud''hommes après son licenciement.', 'B2', 'Travail'),
  ('La requalification du contrat', 'Décision judiciaire qui change la nature d''un contrat de travail.', 'Le tribunal a prononcé la requalification du contrat en CDI.', 'B2', 'Travail'),
  ('Le travail dissimulé', 'Emploi non déclaré aux autorités.', 'Le travail dissimulé est sanctionné pénalement.', 'B2', 'Travail'),
  ('L''économie numérique', 'Ensemble des activités économiques liées au numérique.', 'L''économie numérique crée de nouveaux types d''emplois.', 'B2', 'Travail'),
  ('La transition professionnelle', 'Changement d''orientation ou de statut dans sa carrière.', 'Il a bénéficié d''un accompagnement pour sa transition professionnelle.', 'B2', 'Travail');
