-- Item 7ter du plan vocabulaire 1500 mots : compléter la catégorie 'Santé'
-- 50 -> 125 mots (75 nouveaux mots, répartis A1:7 A2:20 B1:24 B2:24).
-- Vérifications effectuées avant livraison :
--  - dédup contre les 481 mots déjà en base (218 originaux + 116 Vie Sociale + 72 Administration + 75 Logement)
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('La tête', 'Partie supérieure du corps.', 'J''ai mal à la tête.', 'A1', 'Santé'),
  ('Le ventre', 'Partie du corps où se trouve l''estomac.', 'Il a mal au ventre depuis ce matin.', 'A1', 'Santé'),
  ('La gorge', 'Partie interne du cou.', 'J''ai mal à la gorge, je ne peux pas parler fort.', 'A1', 'Santé'),
  ('Le dos', 'Partie arrière du corps entre les épaules et les hanches.', 'J''ai mal au dos après le déménagement.', 'A1', 'Santé'),
  ('Un pansement', 'Bande utilisée pour couvrir une blessure.', 'Mets un pansement sur ta coupure.', 'A1', 'Santé'),
  ('La toux', 'Réflexe qui expulse l''air brusquement des poumons.', 'Sa toux dure depuis trois jours.', 'A1', 'Santé'),
  ('Le rhume', 'Infection légère du nez et de la gorge.', 'J''ai attrapé un rhume à cause du froid.', 'A1', 'Santé'),
  ('La grippe', 'Maladie virale contagieuse avec fièvre et fatigue.', 'La grippe touche beaucoup de monde en hiver.', 'A2', 'Santé'),
  ('La tension artérielle', 'Pression du sang dans les artères.', 'L''infirmière prend ma tension artérielle à chaque visite.', 'A2', 'Santé'),
  ('Le pouls', 'Battement du cœur perceptible sur le poignet.', 'Le médecin a pris mon pouls.', 'A2', 'Santé'),
  ('La cicatrice', 'Marque laissée sur la peau après une blessure.', 'Il a une cicatrice sur le bras.', 'A2', 'Santé'),
  ('Une entorse', 'Blessure d''une articulation sans fracture.', 'Elle s''est fait une entorse à la cheville.', 'A2', 'Santé'),
  ('Une fracture', 'Cassure d''un os.', 'Il a une fracture du poignet après sa chute.', 'A2', 'Santé'),
  ('Le pédiatre', 'Médecin spécialisé dans les soins des enfants.', 'Le pédiatre a examiné le bébé.', 'A2', 'Santé'),
  ('Le gynécologue', 'Médecin spécialisé dans la santé des femmes.', 'Elle a rendez-vous chez le gynécologue demain.', 'A2', 'Santé'),
  ('L''ophtalmologue', 'Médecin spécialisé dans les yeux.', 'L''ophtalmologue a prescrit de nouvelles lunettes.', 'A2', 'Santé'),
  ('Les lunettes', 'Objet porté pour corriger la vue.', 'Mes lunettes sont cassées, je dois en racheter.', 'A2', 'Santé'),
  ('Un appareil auditif', 'Dispositif qui aide à mieux entendre.', 'Mon grand-père porte un appareil auditif.', 'A2', 'Santé'),
  ('Le carnet de santé', 'Document qui suit la santé d''un enfant depuis sa naissance.', 'Le carnet de santé est demandé pour l''inscription à l''école.', 'A2', 'Santé'),
  ('Le carnet de vaccination', 'Document listant les vaccins reçus.', 'N''oubliez pas votre carnet de vaccination.', 'A2', 'Santé'),
  ('Une piqûre', 'Injection faite avec une aiguille.', 'L''infirmière m''a fait une piqûre pour le vaccin.', 'A2', 'Santé'),
  ('Une intolérance alimentaire', 'Difficulté à digérer certains aliments.', 'Il a une intolérance alimentaire au lactose.', 'A2', 'Santé'),
  ('Le stress', 'État de tension physique et mentale.', 'Le stress au travail peut affecter la santé.', 'A2', 'Santé'),
  ('La fatigue', 'Sensation de manque d''énergie.', 'La fatigue est un symptôme fréquent après une maladie.', 'A2', 'Santé'),
  ('Le sommeil', 'État de repos naturel du corps.', 'Le manque de sommeil fatigue beaucoup.', 'A2', 'Santé'),
  ('L''alimentation équilibrée', 'Régime alimentaire varié et sain.', 'Une alimentation équilibrée aide à rester en bonne santé.', 'A2', 'Santé'),
  ('L''activité physique', 'Exercice ou mouvement du corps.', 'L''activité physique régulière est recommandée par les médecins.', 'A2', 'Santé'),
  ('Le psychiatre', 'Médecin spécialisé en santé mentale.', 'Elle consulte un psychiatre depuis plusieurs mois.', 'B1', 'Santé'),
  ('Le psychologue', 'Professionnel qui aide à traiter les difficultés psychologiques.', 'Il voit un psychologue chaque semaine.', 'B1', 'Santé'),
  ('La dépression', 'Maladie caractérisée par une tristesse profonde et durable.', 'La dépression touche des millions de personnes en France.', 'B1', 'Santé'),
  ('L''anxiété', 'Sentiment d''inquiétude excessive.', 'L''anxiété peut provoquer des troubles du sommeil.', 'B1', 'Santé'),
  ('Le burn-out', 'Épuisement professionnel lié au stress prolongé.', 'Il a fait un burn-out après plusieurs années de surmenage.', 'B1', 'Santé'),
  ('La rééducation', 'Ensemble de soins pour retrouver ses capacités physiques.', 'La rééducation après l''opération dure trois mois.', 'B1', 'Santé'),
  ('Le suivi médical', 'Ensemble des consultations régulières pour surveiller la santé.', 'Le suivi médical de la grossesse est important.', 'B1', 'Santé'),
  ('La grossesse', 'Période pendant laquelle une femme porte un enfant.', 'Sa grossesse se déroule bien.', 'B1', 'Santé'),
  ('L''accouchement', 'Naissance d''un enfant.', 'L''accouchement a eu lieu à la maternité.', 'B1', 'Santé'),
  ('La maternité', 'Service hospitalier dédié aux naissances.', 'Elle a été transférée à la maternité hier soir.', 'B1', 'Santé'),
  ('Le congé maternité', 'Période d''absence du travail autour de la naissance d''un enfant.', 'Son congé maternité dure seize semaines.', 'B1', 'Santé'),
  ('Le certificat médical', 'Document rédigé par un médecin attestant un état de santé.', 'Un certificat médical est demandé pour l''inscription au sport.', 'B1', 'Santé'),
  ('L''inaptitude au travail', 'Impossibilité médicale d''exercer son emploi.', 'La médecine du travail a constaté son inaptitude au travail.', 'B1', 'Santé'),
  ('La médecine du travail', 'Service de santé chargé de suivre les salariés.', 'La médecine du travail organise une visite tous les deux ans.', 'B1', 'Santé'),
  ('Le handicap', 'Limitation durable d''une capacité physique, sensorielle ou mentale.', 'Le handicap ne l''empêche pas de travailler.', 'B1', 'Santé'),
  ('L''accessibilité', 'Capacité d''un lieu à être utilisé par les personnes handicapées.', 'L''accessibilité de ce bâtiment a été améliorée.', 'B1', 'Santé'),
  ('La maladie chronique', 'Maladie qui dure longtemps ou toute la vie.', 'Le diabète est une maladie chronique fréquente.', 'B1', 'Santé'),
  ('Les effets secondaires', 'Réactions indésirables provoquées par un médicament.', 'Ce médicament peut avoir des effets secondaires.', 'B1', 'Santé'),
  ('La posologie', 'Quantité et fréquence de prise d''un médicament.', 'Respectez la posologie indiquée sur l''ordonnance.', 'B1', 'Santé'),
  ('L''automédication', 'Fait de se soigner soi-même sans avis médical.', 'L''automédication comporte des risques.', 'B1', 'Santé'),
  ('La pharmacovigilance', 'Surveillance des effets indésirables des médicaments.', 'La pharmacovigilance permet de retirer certains médicaments dangereux.', 'B1', 'Santé'),
  ('Le don d''organes', 'Fait d''offrir un organe pour sauver une autre personne.', 'Il est inscrit sur la liste du don d''organes.', 'B1', 'Santé'),
  ('La liste d''attente', 'Classement des patients en attente d''un soin ou d''une greffe.', 'Elle est sur liste d''attente pour une greffe de rein.', 'B1', 'Santé'),
  ('La greffe', 'Transplantation d''un organe d''un donneur à un receveur.', 'La greffe a été réalisée avec succès.', 'B1', 'Santé'),
  ('L''épidémiologie', 'Science qui étudie la propagation des maladies dans une population.', 'L''épidémiologie permet de suivre l''évolution d''une épidémie.', 'B2', 'Santé'),
  ('La santé publique', 'Ensemble des politiques visant à protéger la santé de la population.', 'La santé publique inclut la prévention et l''accès aux soins.', 'B2', 'Santé'),
  ('Le dépistage', 'Détection précoce d''une maladie chez une personne sans symptôme.', 'Le dépistage du cancer du sein est recommandé après 50 ans.', 'B2', 'Santé'),
  ('La résistance aux antibiotiques', 'Capacité de certaines bactéries à ne plus réagir aux antibiotiques.', 'La résistance aux antibiotiques est un enjeu majeur de santé publique.', 'B2', 'Santé'),
  ('Le consentement éclairé', 'Accord donné par un patient après avoir été informé des risques.', 'Le consentement éclairé est obligatoire avant toute opération.', 'B2', 'Santé'),
  ('Le secret médical', 'Obligation pour les soignants de ne pas divulguer les informations d''un patient.', 'Le secret médical protège la confidentialité des patients.', 'B2', 'Santé'),
  ('La déontologie médicale', 'Ensemble des règles éthiques encadrant la pratique médicale.', 'La déontologie médicale impose le respect du patient.', 'B2', 'Santé'),
  ('L''éthique médicale', 'Réflexion sur les valeurs morales appliquées à la médecine.', 'L''éthique médicale guide les décisions en fin de vie.', 'B2', 'Santé'),
  ('Les soins palliatifs', 'Soins destinés à soulager la douleur des malades en phase terminale.', 'Les soins palliatifs améliorent la qualité de vie des patients.', 'B2', 'Santé'),
  ('La fin de vie', 'Période précédant le décès d''une personne malade.', 'La loi encadre les décisions médicales en fin de vie.', 'B2', 'Santé'),
  ('L''obstination déraisonnable', 'Poursuite de soins jugés disproportionnés par rapport au bénéfice attendu.', 'La loi interdit l''obstination déraisonnable en fin de vie.', 'B2', 'Santé'),
  ('La directive anticipée', 'Document exprimant les souhaits d''une personne sur sa fin de vie.', 'Il a rédigé ses directives anticipées avec son médecin.', 'B2', 'Santé'),
  ('La personne de confiance', 'Personne désignée pour être consultée si le patient ne peut pas s''exprimer.', 'Elle a désigné sa fille comme personne de confiance.', 'B2', 'Santé'),
  ('L''errance diagnostique', 'Longue période avant d''identifier la cause exacte d''une maladie.', 'Certains patients vivent une errance diagnostique de plusieurs années.', 'B2', 'Santé'),
  ('La maladie rare', 'Maladie touchant un très petit nombre de personnes.', 'Les maladies rares bénéficient de centres de référence spécialisés.', 'B2', 'Santé'),
  ('Le centre de référence', 'Établissement spécialisé dans le diagnostic de maladies complexes.', 'Il a été orienté vers un centre de référence pour maladies rares.', 'B2', 'Santé'),
  ('L''essai clinique', 'Étude scientifique testant un nouveau traitement sur des patients volontaires.', 'Elle participe à un essai clinique pour un nouveau médicament.', 'B2', 'Santé'),
  ('La pharmacocinétique', 'Étude du parcours d''un médicament dans l''organisme.', 'La pharmacocinétique détermine la fréquence des prises.', 'B2', 'Santé'),
  ('L''iatrogénie', 'Ensemble des effets indésirables causés par un traitement médical.', 'L''iatrogénie médicamenteuse touche surtout les personnes âgées.', 'B2', 'Santé'),
  ('La polymédication', 'Prise simultanée de plusieurs médicaments par un même patient.', 'La polymédication augmente le risque d''interactions.', 'B2', 'Santé'),
  ('L''interaction médicamenteuse', 'Effet produit par la prise simultanée de plusieurs médicaments.', 'Une interaction médicamenteuse peut réduire l''efficacité d''un traitement.', 'B2', 'Santé'),
  ('La prévention primaire', 'Ensemble d''actions visant à éviter l''apparition d''une maladie.', 'La vaccination fait partie de la prévention primaire.', 'B2', 'Santé'),
  ('La prévention secondaire', 'Actions visant à détecter une maladie à un stade précoce.', 'Le dépistage relève de la prévention secondaire.', 'B2', 'Santé'),
  ('L''observance thérapeutique', 'Respect par le patient du traitement prescrit.', 'Une bonne observance thérapeutique améliore l''efficacité du traitement.', 'B2', 'Santé');
