-- Item 6.5 du plan vocabulaire 1500 mots : nouvelle catégorie 'Loisirs, Culture & Médias'
-- 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 1125 mots déjà en base : aucune collision
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Un film', 'Œuvre visuelle racontant une histoire.', 'Nous avons regardé un film hier soir.', 'A1', 'Loisirs, Culture & Médias'),
  ('La musique', 'Art des sons organisés.', 'J''écoute de la musique tous les matins.', 'A1', 'Loisirs, Culture & Médias'),
  ('Une chanson', 'Morceau de musique chanté.', 'Cette chanson est très connue en France.', 'A1', 'Loisirs, Culture & Médias'),
  ('La télévision', 'Appareil pour regarder des programmes.', 'Nous regardons la télévision le soir.', 'A1', 'Loisirs, Culture & Médias'),
  ('Un jeu', 'Activité pratiquée pour se divertir.', 'Les enfants adorent ce jeu de société.', 'A1', 'Loisirs, Culture & Médias'),
  ('Le sport', 'Activité physique pratiquée pour le loisir ou la compétition.', 'Il fait du sport trois fois par semaine.', 'A1', 'Loisirs, Culture & Médias'),
  ('Le cinéma', 'Lieu où l''on regarde des films.', 'Nous allons au cinéma ce week-end.', 'A1', 'Loisirs, Culture & Médias'),
  ('Un musée', 'Lieu où l''on expose des œuvres d''art ou des objets historiques.', 'Le musée est gratuit le premier dimanche du mois.', 'A1', 'Loisirs, Culture & Médias'),
  ('Un concert', 'Spectacle musical en public.', 'J''ai assisté à un concert incroyable.', 'A1', 'Loisirs, Culture & Médias'),
  ('La danse', 'Art de bouger le corps en rythme.', 'Elle prend des cours de danse le mercredi.', 'A1', 'Loisirs, Culture & Médias'),
  ('La lecture', 'Activité de lire.', 'La lecture est mon passe-temps préféré.', 'A1', 'Loisirs, Culture & Médias'),
  ('La peinture', 'Art de peindre des images.', 'Il pratique la peinture depuis son enfance.', 'A1', 'Loisirs, Culture & Médias'),
  ('Le dessin', 'Art de représenter des formes sur une surface.', 'Mon fils adore le dessin.', 'A1', 'Loisirs, Culture & Médias'),
  ('Une photo', 'Image capturée par un appareil photo.', 'J''ai pris une photo du coucher de soleil.', 'A1', 'Loisirs, Culture & Médias'),
  ('Les vacances', 'Période de repos et de loisirs.', 'Nous partons en vacances en août.', 'A1', 'Loisirs, Culture & Médias'),
  ('Le week-end', 'Samedi et dimanche, jours de repos.', 'Que fais-tu ce week-end ?', 'A1', 'Loisirs, Culture & Médias'),
  ('Une fête', 'Événement festif organisé pour célébrer quelque chose.', 'Nous organisons une fête pour son anniversaire.', 'A1', 'Loisirs, Culture & Médias'),
  ('Un jeu vidéo', 'Jeu joué sur un écran électronique.', 'Mon fils joue à un jeu vidéo tous les soirs.', 'A1', 'Loisirs, Culture & Médias'),
  ('La radio', 'Appareil qui diffuse des programmes sonores.', 'J''écoute la radio en voiture.', 'A1', 'Loisirs, Culture & Médias'),
  ('Un roman', 'Œuvre littéraire racontant une histoire fictive.', 'J''ai lu un roman passionnant cet été.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une pièce de théâtre', 'Œuvre destinée à être jouée sur scène.', 'Nous avons vu une pièce de théâtre hier soir.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un acteur', 'Personne qui joue un rôle dans un film ou une pièce.', 'Cet acteur joue très bien la comédie.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un réalisateur', 'Personne qui dirige la réalisation d''un film.', 'Ce réalisateur a gagné plusieurs prix.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un chanteur', 'Personne qui chante.', 'Ce chanteur est très populaire en France.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un groupe de musique', 'Ensemble de musiciens jouant ensemble.', 'Ce groupe de musique donne un concert demain.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un festival', 'Événement culturel organisé sur plusieurs jours.', 'Le festival de musique attire des milliers de visiteurs.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une exposition', 'Présentation publique d''œuvres ou d''objets.', 'L''exposition sur l''art moderne se termine bientôt.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une galerie d''art', 'Lieu où l''on expose et vend des œuvres d''art.', 'Cette galerie d''art présente de jeunes artistes.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un abonnement à une plateforme de streaming', 'Service permettant d''accéder à des films et séries en ligne.', 'J''ai un abonnement à une plateforme de streaming.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une série télévisée', 'Programme télévisé diffusé en plusieurs épisodes.', 'Cette série télévisée est très suivie en France.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un épisode', 'Partie d''une série télévisée.', 'J''ai regardé trois épisodes hier soir.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un podcast', 'Programme audio disponible en ligne.', 'J''écoute un podcast pendant mes trajets.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une chaîne de télévision', 'Canal de diffusion de programmes télévisés.', 'Cette chaîne de télévision propose beaucoup de documentaires.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un présentateur', 'Personne qui anime une émission.', 'Le présentateur a interviewé plusieurs invités.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une émission de télévision', 'Programme diffusé à la télévision.', 'Cette émission de télévision passe tous les samedis soirs.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un jeu de société', 'Jeu pratiqué à plusieurs autour d''une table.', 'Nous jouons à un jeu de société chaque dimanche.', 'A2', 'Loisirs, Culture & Médias'),
  ('Les échecs', 'Jeu de stratégie à deux joueurs.', 'Il joue aux échecs avec son grand-père.', 'A2', 'Loisirs, Culture & Médias'),
  ('La randonnée', 'Activité de marche en pleine nature.', 'La randonnée en montagne est un loisir populaire.', 'A2', 'Loisirs, Culture & Médias'),
  ('La pêche', 'Activité consistant à attraper du poisson.', 'Mon père aime la pêche le dimanche matin.', 'A2', 'Loisirs, Culture & Médias'),
  ('Le jardinage', 'Activité de culture des plantes et du jardin.', 'Le jardinage est une activité relaxante.', 'A2', 'Loisirs, Culture & Médias'),
  ('La couture', 'Activité de fabrication ou réparation de vêtements.', 'Elle apprend la couture dans une association.', 'A2', 'Loisirs, Culture & Médias'),
  ('Le bricolage', 'Activité de réparation ou de fabrication manuelle.', 'Il fait du bricolage tous les week-ends.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un club de loisirs', 'Association organisant des activités de loisirs.', 'Elle est inscrite dans un club de loisirs.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un atelier créatif', 'Activité collective de création artistique.', 'L''atelier créatif propose de la poterie chaque semaine.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une bande dessinée', 'Récit raconté en images et en bulles de texte.', 'Il collectionne les bandes dessinées depuis son enfance.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un magazine', 'Publication périodique sur un sujet précis.', 'Elle lit un magazine de mode chaque mois.', 'A2', 'Loisirs, Culture & Médias'),
  ('La presse', 'Ensemble des journaux et magazines.', 'La presse a beaucoup parlé de cet événement.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un article de presse', 'Texte publié dans un journal ou un magazine.', 'J''ai lu un article de presse intéressant ce matin.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un critique', 'Personne qui donne son avis sur une œuvre.', 'Le critique a beaucoup aimé ce film.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une critique de film', 'Avis rédigé sur un film.', 'La critique de film était très positive.', 'A2', 'Loisirs, Culture & Médias'),
  ('Le patrimoine culturel', 'Ensemble des biens culturels d''un pays.', 'Le patrimoine culturel français est très riche.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un monument historique', 'Bâtiment protégé pour sa valeur historique.', 'Cette église est classée monument historique.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une visite guidée', 'Visite accompagnée d''un guide.', 'Nous avons participé à une visite guidée du château.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un billet de cinéma', 'Ticket permettant d''entrer au cinéma.', 'J''ai réservé mes billets de cinéma en ligne.', 'A2', 'Loisirs, Culture & Médias'),
  ('Une salle de spectacle', 'Lieu où sont présentés des spectacles.', 'Cette salle de spectacle accueille des concerts toute l''année.', 'A2', 'Loisirs, Culture & Médias'),
  ('Un temps libre', 'Moment où l''on n''a pas d''obligation.', 'Je lis pendant mon temps libre.', 'A2', 'Loisirs, Culture & Médias'),
  ('La culture populaire', 'Ensemble des pratiques culturelles partagées par le grand public.', 'La culture populaire française inclut la chanson et le cinéma.', 'B1', 'Loisirs, Culture & Médias'),
  ('L''industrie culturelle', 'Secteur économique lié à la production de biens culturels.', 'L''industrie culturelle emploie de nombreux professionnels en France.', 'B1', 'Loisirs, Culture & Médias'),
  ('Le cinéma d''auteur', 'Films réalisés selon une vision artistique personnelle plutôt que commerciale.', 'Ce réalisateur est connu pour son cinéma d''auteur.', 'B1', 'Loisirs, Culture & Médias'),
  ('Une critique littéraire', 'Analyse et évaluation d''une œuvre littéraire.', 'La critique littéraire a salué ce roman.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un prix littéraire', 'Distinction remise à un auteur pour son œuvre.', 'Ce roman a reçu un prix littéraire important.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un best-seller', 'Livre qui se vend en très grand nombre.', 'Ce roman est devenu un best-seller international.', 'B1', 'Loisirs, Culture & Médias'),
  ('La diffusion culturelle', 'Ensemble des moyens de faire connaître des œuvres culturelles.', 'La diffusion culturelle passe de plus en plus par internet.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un média', 'Moyen de communication permettant de diffuser de l''information.', 'La télévision reste un média influent.', 'B1', 'Loisirs, Culture & Médias'),
  ('L''audiovisuel', 'Ensemble des techniques de communication utilisant le son et l''image.', 'L''audiovisuel emploie de nombreux techniciens.', 'B1', 'Loisirs, Culture & Médias'),
  ('La liberté de la presse', 'Droit des médias à informer sans censure.', 'La liberté de la presse est un pilier de la démocratie.', 'B1', 'Loisirs, Culture & Médias'),
  ('La désinformation', 'Diffusion volontaire de fausses informations.', 'La désinformation se propage rapidement sur internet.', 'B1', 'Loisirs, Culture & Médias'),
  ('Les fausses informations', 'Contenus présentés comme vrais alors qu''ils sont faux.', 'Il faut vérifier les fausses informations avant de les partager.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un influenceur', 'Personne qui a une audience importante sur les réseaux sociaux.', 'Cet influenceur a des millions d''abonnés.', 'B1', 'Loisirs, Culture & Médias'),
  ('Une plateforme de streaming', 'Service diffusant des contenus audiovisuels en ligne.', 'Cette plateforme de streaming propose des films et des séries.', 'B1', 'Loisirs, Culture & Médias'),
  ('L''abonnement culturel', 'Formule permettant d''accéder régulièrement à des offres culturelles.', 'L''abonnement culturel donne accès à plusieurs musées.', 'B1', 'Loisirs, Culture & Médias'),
  ('La médiathèque', 'Établissement public prêtant livres, films et musique.', 'J''ai emprunté un DVD à la médiathèque.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un festival international', 'Événement culturel réunissant des participants de plusieurs pays.', 'Le festival international de cinéma attire des célébrités du monde entier.', 'B1', 'Loisirs, Culture & Médias'),
  ('Le patrimoine immatériel', 'Ensemble des traditions, savoir-faire et pratiques culturelles transmises.', 'La gastronomie française fait partie du patrimoine immatériel de l''UNESCO.', 'B1', 'Loisirs, Culture & Médias'),
  ('L''UNESCO', 'Organisation des Nations unies pour l''éducation, la science et la culture.', 'L''UNESCO protège de nombreux sites classés au patrimoine mondial.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un site classé', 'Lieu officiellement reconnu pour sa valeur culturelle ou historique.', 'Ce château est un site classé au patrimoine mondial.', 'B1', 'Loisirs, Culture & Médias'),
  ('La restauration d''œuvres d''art', 'Travail visant à réparer ou conserver une œuvre ancienne.', 'La restauration d''œuvres d''art demande une grande expertise.', 'B1', 'Loisirs, Culture & Médias'),
  ('Le mécénat culturel', 'Soutien financier apporté par des entreprises à des projets culturels.', 'Le mécénat culturel finance de nombreuses expositions.', 'B1', 'Loisirs, Culture & Médias'),
  ('La subvention culturelle', 'Aide financière publique destinée à un projet culturel.', 'Cette compagnie de théâtre reçoit une subvention culturelle.', 'B1', 'Loisirs, Culture & Médias'),
  ('La politique culturelle', 'Ensemble des décisions publiques favorisant l''accès à la culture.', 'La politique culturelle française soutient le cinéma national.', 'B1', 'Loisirs, Culture & Médias'),
  ('Le pass culture', 'Dispositif public offrant un budget culturel aux jeunes.', 'Les jeunes utilisent le pass culture pour aller au concert.', 'B1', 'Loisirs, Culture & Médias'),
  ('Une bibliothèque de quartier', 'Bibliothèque locale accessible à tous les habitants.', 'La bibliothèque de quartier propose des animations pour enfants.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un abonnement presse', 'Formule permettant de recevoir régulièrement un journal ou un magazine.', 'J''ai un abonnement presse au journal local.', 'B1', 'Loisirs, Culture & Médias'),
  ('La télévision publique', 'Chaînes de télévision financées par l''État.', 'La télévision publique diffuse des programmes éducatifs.', 'B1', 'Loisirs, Culture & Médias'),
  ('La télévision privée', 'Chaînes de télévision financées par la publicité.', 'La télévision privée dépend des recettes publicitaires.', 'B1', 'Loisirs, Culture & Médias'),
  ('La redevance audiovisuelle', 'Taxe qui finançait autrefois la télévision publique française.', 'La redevance audiovisuelle a été supprimée en France en 2022.', 'B1', 'Loisirs, Culture & Médias'),
  ('Les droits d''auteur', 'Ensemble des droits protégeant les créateurs d''une œuvre.', 'Les droits d''auteur protègent les musiciens et les écrivains.', 'B1', 'Loisirs, Culture & Médias'),
  ('Le piratage culturel', 'Reproduction ou diffusion illégale d''œuvres protégées.', 'Le piratage culturel nuit aux artistes et aux producteurs.', 'B1', 'Loisirs, Culture & Médias'),
  ('Une œuvre originale', 'Création unique et personnelle d''un artiste.', 'Ce tableau est une œuvre originale du dix-neuvième siècle.', 'B1', 'Loisirs, Culture & Médias'),
  ('Un artiste engagé', 'Créateur qui exprime des idées politiques ou sociales à travers son art.', 'Cet artiste engagé aborde souvent le thème de l''immigration.', 'B1', 'Loisirs, Culture & Médias'),
  ('La consommation culturelle', 'Habitudes de fréquentation ou d''usage des biens culturels.', 'La consommation culturelle des jeunes a beaucoup changé avec le numérique.', 'B1', 'Loisirs, Culture & Médias'),
  ('L''accès à la culture', 'Possibilité pour tous de participer à des activités culturelles.', 'L''accès à la culture est plus difficile en milieu rural.', 'B1', 'Loisirs, Culture & Médias'),
  ('La démocratisation culturelle', 'Élargissement de l''accès à la culture à toutes les catégories sociales.', 'La démocratisation culturelle est un objectif des politiques publiques françaises.', 'B1', 'Loisirs, Culture & Médias'),
  ('L''exception culturelle française', 'Politique visant à protéger la culture française de la concurrence internationale.', 'L''exception culturelle française justifie le soutien public au cinéma.', 'B2', 'Loisirs, Culture & Médias'),
  ('La souveraineté culturelle', 'Capacité d''un pays à préserver son identité culturelle face à la mondialisation.', 'La souveraineté culturelle est défendue par plusieurs politiques publiques.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''homogénéisation culturelle', 'Uniformisation des cultures sous l''influence de la mondialisation.', 'L''homogénéisation culturelle inquiète les défenseurs des cultures locales.', 'B2', 'Loisirs, Culture & Médias'),
  ('La mondialisation culturelle', 'Diffusion mondiale des produits et pratiques culturelles.', 'La mondialisation culturelle favorise la circulation des œuvres.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''hégémonie culturelle', 'Domination d''une culture sur les autres.', 'Certains critiquent l''hégémonie culturelle des productions américaines.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''appropriation culturelle', 'Usage controversé d''éléments d''une culture par des personnes extérieures à celle-ci.', 'Le débat sur l''appropriation culturelle divise souvent l''opinion publique.', 'B2', 'Loisirs, Culture & Médias'),
  ('La diversité culturelle', 'Coexistence de différentes cultures et expressions artistiques.', 'La diversité culturelle est protégée par une convention de l''UNESCO.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le pluralisme médiatique', 'Coexistence de plusieurs sources d''information indépendantes.', 'Le pluralisme médiatique garantit une information diversifiée.', 'B2', 'Loisirs, Culture & Médias'),
  ('La concentration des médias', 'Regroupement de plusieurs médias sous le contrôle d''un même propriétaire.', 'La concentration des médias inquiète les défenseurs de la liberté de la presse.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le conflit d''intérêts médiatique', 'Situation où un propriétaire de média a des intérêts pouvant influencer l''information.', 'Un conflit d''intérêts médiatique peut nuire à l''objectivité d''un journal.', 'B2', 'Loisirs, Culture & Médias'),
  ('La ligne éditoriale', 'Orientation générale adoptée par un média dans le traitement de l''information.', 'La ligne éditoriale de ce journal est plutôt progressiste.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le fact-checking', 'Vérification systématique des faits avancés dans une information.', 'Le fact-checking est devenu essentiel face à la désinformation.', 'B2', 'Loisirs, Culture & Médias'),
  ('Les algorithmes de recommandation culturelle', 'Systèmes qui suggèrent des contenus culturels selon les préférences de l''utilisateur.', 'Les algorithmes de recommandation culturelle influencent nos choix de films.', 'B2', 'Loisirs, Culture & Médias'),
  ('La bulle de filtre', 'Phénomène qui limite l''exposition à des points de vue différents des siens.', 'Les réseaux sociaux favorisent la bulle de filtre.', 'B2', 'Loisirs, Culture & Médias'),
  ('La viralité', 'Propagation rapide d''un contenu sur internet.', 'Cette vidéo a connu une grande viralité en quelques heures.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le contenu généré par les utilisateurs', 'Contenus créés et partagés par les internautes eux-mêmes.', 'Le contenu généré par les utilisateurs domine désormais les réseaux sociaux.', 'B2', 'Loisirs, Culture & Médias'),
  ('La création numérique', 'Production d''œuvres artistiques à l''aide d''outils numériques.', 'La création numérique regroupe le jeu vidéo et l''animation.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''intelligence artificielle générative', 'Technologie capable de créer des contenus artistiques automatiquement.', 'L''intelligence artificielle générative bouleverse la création artistique.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le droit à l''image', 'Droit d''une personne à contrôler l''utilisation de son image.', 'Le droit à l''image protège les personnes photographiées sans consentement.', 'B2', 'Loisirs, Culture & Médias'),
  ('La censure', 'Contrôle ou interdiction de la diffusion de certains contenus.', 'La censure limite la liberté d''expression artistique.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''autocensure', 'Renoncement volontaire à exprimer certaines idées par prudence.', 'L''autocensure touche parfois les artistes dans les régimes autoritaires.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le mécénat d''entreprise culturel', 'Soutien financier apporté par une entreprise à des projets artistiques.', 'Le mécénat d''entreprise culturel finance de nombreuses expositions.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''économie de la culture', 'Étude des aspects économiques liés à la production culturelle.', 'L''économie de la culture représente une part importante du PIB français.', 'B2', 'Loisirs, Culture & Médias'),
  ('Les industries créatives', 'Secteurs économiques fondés sur la création artistique et intellectuelle.', 'Les industries créatives regroupent la mode, le design et l''édition.', 'B2', 'Loisirs, Culture & Médias'),
  ('La propriété intellectuelle', 'Ensemble des droits protégeant les créations de l''esprit.', 'La propriété intellectuelle protège les œuvres artistiques et les inventions.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le rayonnement culturel', 'Influence et prestige culturel d''un pays à l''étranger.', 'Le rayonnement culturel français passe notamment par la langue et la gastronomie.', 'B2', 'Loisirs, Culture & Médias'),
  ('La francophonie', 'Ensemble des pays et populations utilisant le français.', 'La francophonie regroupe des pays sur plusieurs continents.', 'B2', 'Loisirs, Culture & Médias'),
  ('La diplomatie culturelle', 'Utilisation de la culture pour renforcer les relations entre pays.', 'La diplomatie culturelle française s''appuie sur les instituts français à l''étranger.', 'B2', 'Loisirs, Culture & Médias'),
  ('L''institut culturel', 'Organisme chargé de promouvoir la culture d''un pays à l''étranger.', 'L''institut culturel français organise des expositions dans le monde entier.', 'B2', 'Loisirs, Culture & Médias'),
  ('La coopération culturelle', 'Collaboration entre pays dans le domaine de la culture.', 'La coopération culturelle favorise les échanges artistiques internationaux.', 'B2', 'Loisirs, Culture & Médias'),
  ('Le patrimoine numérique', 'Ensemble des contenus culturels créés ou conservés sous forme numérique.', 'La numérisation des archives enrichit le patrimoine numérique.', 'B2', 'Loisirs, Culture & Médias'),
  ('La médiation culturelle', 'Ensemble des actions visant à rapprocher le public des œuvres culturelles.', 'La médiation culturelle facilite la compréhension des œuvres d''art.', 'B2', 'Loisirs, Culture & Médias');
