-- Item 7bis du plan vocabulaire 1500 mots : compléter la catégorie 'Logement'
-- 50 -> 125 mots (75 nouveaux mots, répartis A1:8 A2:20 B1:24 B2:23).
-- Vérifications effectuées avant livraison :
--  - dédup contre les 406 mots déjà en base (218 originaux + 116 Vie Sociale + 72 Administration)
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Une chambre', 'Pièce d''un logement où l''on dort.', 'Ma chambre donne sur la rue.', 'A1', 'Logement'),
  ('Une cuisine', 'Pièce où l''on prépare les repas.', 'La cuisine est petite mais bien équipée.', 'A1', 'Logement'),
  ('Une salle de bain', 'Pièce où l''on se lave.', 'La salle de bain a une douche et un lavabo.', 'A1', 'Logement'),
  ('Un salon', 'Pièce principale où l''on reçoit les invités.', 'Nous regardons la télévision dans le salon.', 'A1', 'Logement'),
  ('Une fenêtre', 'Ouverture dans un mur pour laisser entrer la lumière.', 'Ouvre la fenêtre, il fait chaud.', 'A1', 'Logement'),
  ('Une porte', 'Ouverture qui permet d''entrer ou de sortir d''une pièce.', 'Ferme la porte en sortant.', 'A1', 'Logement'),
  ('Un étage', 'Niveau d''un immeuble au-dessus du rez-de-chaussée.', 'J''habite au troisième étage.', 'A1', 'Logement'),
  ('Un ascenseur', 'Appareil qui monte et descend entre les étages.', 'L''ascenseur est en panne aujourd''hui.', 'A1', 'Logement'),
  ('Le chauffage', 'Système qui produit de la chaleur dans un logement.', 'Le chauffage est allumé depuis octobre.', 'A2', 'Logement'),
  ('L''électricité', 'Énergie utilisée pour l''éclairage et les appareils.', 'Il faut mettre l''électricité à votre nom avant d''emménager.', 'A2', 'Logement'),
  ('Le compteur', 'Appareil qui mesure la consommation d''eau, de gaz ou d''électricité.', 'Relevez le compteur avant de signer l''état des lieux.', 'A2', 'Logement'),
  ('Un déménagement', 'Action de changer de logement.', 'Notre déménagement est prévu le mois prochain.', 'A2', 'Logement'),
  ('Un carton de déménagement', 'Boîte utilisée pour transporter ses affaires.', 'J''ai rempli dix cartons de déménagement.', 'A2', 'Logement'),
  ('Le bail meublé', 'Contrat de location pour un logement équipé de meubles.', 'Le bail meublé dure généralement un an.', 'A2', 'Logement'),
  ('Un logement vacant', 'Logement inoccupé, disponible à la location.', 'L''agence a plusieurs logements vacants ce mois-ci.', 'A2', 'Logement'),
  ('La visite du logement', 'Rendez-vous pour découvrir un logement avant de le louer.', 'La visite du logement a duré vingt minutes.', 'A2', 'Logement'),
  ('Le dossier de location', 'Ensemble de documents nécessaires pour louer un logement.', 'Mon dossier de location comprend mes trois derniers bulletins de salaire.', 'A2', 'Logement'),
  ('Une résidence étudiante', 'Logement réservé aux étudiants.', 'Elle habite dans une résidence étudiante près de la fac.', 'A2', 'Logement'),
  ('Un logement de fonction', 'Logement fourni par l''employeur.', 'Le gardien de l''immeuble a un logement de fonction.', 'A2', 'Logement'),
  ('Le gardien d''immeuble', 'Personne chargée de l''entretien et de la sécurité d''un immeuble.', 'Le gardien d''immeuble s''occupe des poubelles et du courrier.', 'A2', 'Logement'),
  ('Une véranda', 'Pièce vitrée ajoutée à une maison.', 'Ils prennent le petit-déjeuner dans la véranda.', 'A2', 'Logement'),
  ('Le jardin', 'Espace extérieur planté autour d''une maison.', 'Les enfants jouent dans le jardin.', 'A2', 'Logement'),
  ('La terrasse', 'Espace extérieur plat où l''on peut s''asseoir.', 'Nous mangeons souvent sur la terrasse en été.', 'A2', 'Logement'),
  ('Un balcon', 'Petite plateforme extérieure attachée à un appartement.', 'J''ai mis des plantes sur mon balcon.', 'A2', 'Logement'),
  ('Le parking', 'Espace réservé pour garer une voiture.', 'Le parking est inclus dans le loyer.', 'A2', 'Logement'),
  ('Une place de parking', 'Emplacement individuel pour garer un véhicule.', 'J''ai une place de parking numérotée au sous-sol.', 'A2', 'Logement'),
  ('Un logement insalubre', 'Logement en mauvais état, dangereux pour la santé.', 'La mairie a signalé un logement insalubre dans cet immeuble.', 'A2', 'Logement'),
  ('Les nuisances sonores', 'Bruits gênants provenant du voisinage.', 'Le règlement intérieur interdit les nuisances sonores après 22 heures.', 'A2', 'Logement'),
  ('Le préavis réduit', 'Délai raccourci pour quitter un logement dans certains cas.', 'Le préavis réduit s''applique en zone tendue.', 'B1', 'Logement'),
  ('La zone tendue', 'Secteur où la demande de logements dépasse l''offre.', 'Paris est classée en zone tendue.', 'B1', 'Logement'),
  ('L''encadrement des loyers', 'Réglementation qui limite le montant des loyers.', 'L''encadrement des loyers s''applique dans plusieurs grandes villes.', 'B1', 'Logement'),
  ('Le loyer de référence', 'Montant maximal fixé pour un loyer dans une zone encadrée.', 'Le loyer proposé dépasse le loyer de référence majoré.', 'B1', 'Logement'),
  ('La sous-location', 'Fait de louer à son tour un logement que l''on loue déjà.', 'La sous-location est interdite sans l''accord du propriétaire.', 'B1', 'Logement'),
  ('Le bail solidaire', 'Contrat de location signé par plusieurs colocataires solidairement responsables.', 'Les colocataires ont signé un bail solidaire.', 'B1', 'Logement'),
  ('La clause de solidarité', 'Clause obligeant chaque colocataire à payer pour les autres en cas d''impayé.', 'La clause de solidarité protège le propriétaire en cas de départ d''un colocataire.', 'B1', 'Logement'),
  ('Le congé pour vente', 'Fin de bail décidée par le propriétaire pour vendre le logement.', 'Le propriétaire a délivré un congé pour vente.', 'B1', 'Logement'),
  ('Le congé pour reprise', 'Fin de bail décidée par le propriétaire pour habiter le logement.', 'Le congé pour reprise doit respecter un délai de six mois.', 'B1', 'Logement'),
  ('La procédure d''expulsion', 'Ensemble des étapes légales pour faire quitter un locataire.', 'La procédure d''expulsion peut durer plusieurs mois.', 'B1', 'Logement'),
  ('Les impayés de loyer', 'Loyers non payés par un locataire.', 'Les impayés de loyer ont conduit à une procédure judiciaire.', 'B1', 'Logement'),
  ('La commission de conciliation', 'Organisme qui aide à résoudre les litiges entre locataire et propriétaire.', 'Ils ont saisi la commission de conciliation avant d''aller au tribunal.', 'B1', 'Logement'),
  ('Le logement intermédiaire', 'Logement dont le loyer est entre le social et le marché libre.', 'Le logement intermédiaire cible les classes moyennes.', 'B1', 'Logement'),
  ('La demande de logement social', 'Dossier déposé pour obtenir un logement à loyer réduit.', 'Sa demande de logement social a été enregistrée en préfecture.', 'B1', 'Logement'),
  ('Le numéro unique d''enregistrement', 'Identifiant attribué à une demande de logement social.', 'Chaque demande de logement social reçoit un numéro unique d''enregistrement.', 'B1', 'Logement'),
  ('Les critères d''attribution', 'Règles utilisées pour choisir les bénéficiaires d''un logement social.', 'Les critères d''attribution prennent en compte les revenus du foyer.', 'B1', 'Logement'),
  ('La commission d''attribution', 'Groupe qui décide de l''attribution des logements sociaux.', 'La commission d''attribution se réunit chaque mois.', 'B1', 'Logement'),
  ('L''accession à la propriété', 'Fait de devenir propriétaire de son logement.', 'L''accession à la propriété reste difficile pour les jeunes ménages.', 'B1', 'Logement'),
  ('Le prêt immobilier', 'Emprunt bancaire destiné à financer l''achat d''un logement.', 'Ils ont obtenu un prêt immobilier sur vingt ans.', 'B1', 'Logement'),
  ('Le taux d''endettement', 'Part des revenus consacrée au remboursement d''un crédit.', 'La banque limite le taux d''endettement à 35%.', 'B1', 'Logement'),
  ('L''apport personnel', 'Somme d''argent que l''on investit soi-même dans un achat immobilier.', 'Un apport personnel de 10% facilite l''obtention du prêt.', 'B1', 'Logement'),
  ('Le compromis de vente', 'Accord préliminaire avant la signature définitive d''une vente immobilière.', 'Ils ont signé le compromis de vente hier.', 'B1', 'Logement'),
  ('L''acte de vente', 'Document officiel qui finalise la vente d''un bien immobilier.', 'La signature de l''acte de vente a eu lieu chez le notaire.', 'B1', 'Logement'),
  ('Le délai de rétractation', 'Période pendant laquelle un acheteur peut annuler un achat immobilier.', 'Le délai de rétractation est de dix jours après la signature.', 'B1', 'Logement'),
  ('La loi ALUR', 'Loi française qui encadre les rapports locatifs et l''urbanisme.', 'La loi ALUR a renforcé l''encadrement des loyers.', 'B2', 'Logement'),
  ('Le bail réel solidaire', 'Dispositif permettant d''acheter un logement en dissociant le foncier du bâti.', 'Le bail réel solidaire réduit le coût d''achat du logement.', 'B2', 'Logement'),
  ('La dissociation du foncier', 'Séparation entre la propriété du terrain et celle du bâtiment.', 'La dissociation du foncier permet de baisser le prix de vente.', 'B2', 'Logement'),
  ('L''organisme de foncier solidaire', 'Structure qui gère les terrains dans le cadre du bail réel solidaire.', 'L''organisme de foncier solidaire reste propriétaire du terrain.', 'B2', 'Logement'),
  ('Le plan local d''urbanisme', 'Document qui fixe les règles de construction dans une commune.', 'Le plan local d''urbanisme limite la hauteur des nouveaux bâtiments.', 'B2', 'Logement'),
  ('La zone constructible', 'Terrain sur lequel il est autorisé de construire.', 'Ce terrain n''est pas classé en zone constructible.', 'B2', 'Logement'),
  ('La densification urbaine', 'Augmentation du nombre de logements dans un espace urbain.', 'La densification urbaine vise à limiter l''étalement des villes.', 'B2', 'Logement'),
  ('La rénovation énergétique', 'Travaux visant à réduire la consommation d''énergie d''un bâtiment.', 'L''État finance une partie des travaux de rénovation énergétique.', 'B2', 'Logement'),
  ('La passoire thermique', 'Logement très mal isolé qui consomme beaucoup d''énergie.', 'Cette passoire thermique doit être rénovée avant d''être relouée.', 'B2', 'Logement'),
  ('L''interdiction de location', 'Mesure empêchant la location d''un logement trop énergivore.', 'L''interdiction de location vise les logements classés G au DPE.', 'B2', 'Logement'),
  ('Le bailleur institutionnel', 'Grande entreprise ou organisme propriétaire de nombreux logements.', 'Un bailleur institutionnel gère plusieurs milliers de logements en France.', 'B2', 'Logement'),
  ('La vacance locative', 'Période pendant laquelle un logement reste inoccupé entre deux locataires.', 'La vacance locative coûte cher aux propriétaires.', 'B2', 'Logement'),
  ('Le marché locatif', 'Ensemble de l''offre et de la demande de logements à louer.', 'Le marché locatif est tendu dans les grandes métropoles.', 'B2', 'Logement'),
  ('La spéculation immobilière', 'Achat de biens immobiliers dans le seul but de réaliser un profit rapide.', 'La spéculation immobilière fait grimper les prix dans certains quartiers.', 'B2', 'Logement'),
  ('La gentrification', 'Transformation d''un quartier populaire attirant des habitants plus aisés.', 'La gentrification a fait doubler les loyers dans ce quartier.', 'B2', 'Logement'),
  ('L''expropriation', 'Procédure permettant à l''État de racheter un bien pour un projet public.', 'L''expropriation a permis la construction de la nouvelle ligne de tramway.', 'B2', 'Logement'),
  ('L''indemnité d''expropriation', 'Compensation financière versée en cas d''expropriation.', 'L''indemnité d''expropriation doit correspondre à la valeur du bien.', 'B2', 'Logement'),
  ('La servitude d''urbanisme', 'Contrainte légale imposée à un terrain dans l''intérêt général.', 'Une servitude d''urbanisme interdit toute construction sur cette parcelle.', 'B2', 'Logement'),
  ('Le droit de préemption', 'Priorité donnée à une collectivité pour acheter un bien avant tout autre acquéreur.', 'La mairie a exercé son droit de préemption sur ce local commercial.', 'B2', 'Logement'),
  ('La réquisition de logement', 'Procédure permettant à l''État d''utiliser un logement vacant en cas d''urgence.', 'La réquisition de logement reste une mesure rare et exceptionnelle.', 'B2', 'Logement'),
  ('La colocation intergénérationnelle', 'Cohabitation entre un senior et un jeune, souvent à loyer réduit.', 'La colocation intergénérationnelle lutte contre l''isolement des personnes âgées.', 'B2', 'Logement'),
  ('L''habitat participatif', 'Projet de logement conçu et géré collectivement par ses habitants.', 'L''habitat participatif encourage l''entraide entre voisins.', 'B2', 'Logement'),
  ('La résidence principale fiscale', 'Notion fiscale désignant le logement où l''on réside la majeure partie de l''année.', 'La plus-value est exonérée pour la résidence principale fiscale.', 'B2', 'Logement');
