-- Examen Blanc 2 : thème "Vie professionnelle & recherche d'emploi", niveau B1.
-- Contenu 100% neuf (pas de réutilisation de l'examen 1).

DO $$
DECLARE
  v_exam_id uuid;
BEGIN
  INSERT INTO public.exams (label, slug, is_active, duration_co, duration_ce, duration_ee, duration_eo)
  VALUES ('Examen Blanc 2', 'exam-2', false, 20, 30, 30, 10)
  RETURNING id INTO v_exam_id;

  -- ===================== CO — 20 questions (order_index 0-19) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, transcription, question, options, correct_answer, audio_url, max_plays)
  VALUES
  (v_exam_id, 'CO', 0, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Bonjour, vous êtes bien chez Dupont et Associés. Nos bureaux sont ouverts du lundi au vendredi de 9h à 18h. Pour toute urgence, laissez un message après le bip.',
    'Quels sont les horaires d''ouverture ?',
    ARRAY['A) 9h-18h du lundi au vendredi','B) 8h-17h tous les jours','C) 9h-12h uniquement','D) 24h/24'], 'A', '/mock/audio-co-21.mp3', 2),
  (v_exam_id, 'CO', 1, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Merci d''être venu. Pouvez-vous me parler de votre expérience dans la vente ?',
    'Quel est le sujet de la question posée ?',
    ARRAY['A) Les études du candidat','B) L''expérience en vente','C) Les loisirs du candidat','D) Le salaire souhaité'], 'B', '/mock/audio-co-22.mp3', 2),
  (v_exam_id, 'CO', 2, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'La réunion de ce matin est annulée, elle est reportée à 14 heures dans la salle de conférence.',
    'À quelle heure aura lieu la réunion ?',
    ARRAY['A) Ce matin','B) 14 heures','C) Demain matin','D) Elle est annulée définitivement'], 'B', '/mock/audio-co-23.mp3', 2),
  (v_exam_id, 'CO', 3, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'L''entreprise recrute un(e) assistant(e) administratif(ve) à temps plein, à pourvoir dès le mois prochain.',
    'Quel poste est proposé ?',
    ARRAY['A) Assistant(e) administratif(ve)','B) Comptable','C) Commercial','D) Technicien'], 'A', '/mock/audio-co-24.mp3', 2),
  (v_exam_id, 'CO', 4, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Votre candidature a bien été reçue. Nous vous recontacterons dans les quinze jours si votre profil est retenu.',
    'Quand la personne sera-t-elle recontactée ?',
    ARRAY['A) Immédiatement','B) Dans les quinze jours si retenue','C) Jamais','D) Le jour même'], 'B', '/mock/audio-co-25.mp3', 2),
  (v_exam_id, 'CO', 5, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Tu as vu le nouvel horaire des pauses ? On peut prendre vingt minutes au lieu de quinze maintenant.',
    'Qu''est-ce qui a changé ?',
    ARRAY['A) La durée des pauses','B) Le lieu des pauses','C) Le nombre de pauses','D) Rien n''a changé'], 'A', '/mock/audio-co-26.mp3', 2),
  (v_exam_id, 'CO', 6, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le prochain module de formation en bureautique commence lundi à 9h, salle 12, merci d''apporter votre ordinateur portable.',
    'Que doivent apporter les participants ?',
    ARRAY['A) Un cahier','B) Un ordinateur portable','C) Une clé USB','D) Un dictionnaire'], 'B', '/mock/audio-co-27.mp3', 2),
  (v_exam_id, 'CO', 7, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Merci de baisser le son de vos appels téléphoniques, certains collègues se plaignent du bruit.',
    'Pourquoi fait-on cette annonce ?',
    ARRAY['A) Une panne informatique','B) Le bruit dérange des collègues','C) Une réunion va commencer','D) Le bureau ferme'], 'B', '/mock/audio-co-28.mp3', 2),
  (v_exam_id, 'CO', 8, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Je voudrais poser trois jours de congé la semaine du 10, c''est possible ?',
    'Que demande la personne ?',
    ARRAY['A) Une augmentation','B) Trois jours de congé','C) Un changement de poste','D) Une formation'], 'B', '/mock/audio-co-29.mp3', 2),
  (v_exam_id, 'CO', 9, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Bonjour, vous avez été sélectionné pour une mission de deux semaines chez notre client. Rappelez-nous pour confirmer votre disponibilité.',
    'Que doit faire la personne pour la mission ?',
    ARRAY['A) Rappeler pour confirmer','B) Se présenter directement','C) Envoyer un nouveau CV','D) Attendre un courrier'], 'A', '/mock/audio-co-30.mp3', 2),
  (v_exam_id, 'CO', 10, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Vos résultats sont bons, mais je pense que vous pourriez davantage prendre d''initiatives dans les projets d''équipe.',
    'Que suggère le manager ?',
    ARRAY['A) De changer de poste','B) De prendre plus d''initiatives','C) De travailler moins','D) De démissionner'], 'B', '/mock/audio-co-31.mp3', 1),
  (v_exam_id, 'CO', 11, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Il paraît que la direction va annoncer une réorganisation du service la semaine prochaine.',
    'Qu''est-ce qui va probablement être annoncé ?',
    ARRAY['A) Une réorganisation du service','B) Une augmentation générale','C) La fermeture de l''entreprise','D) Un déménagement'], 'A', '/mock/audio-co-32.mp3', 1),
  (v_exam_id, 'CO', 12, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Je vous appelle car la livraison prévue hier n''est toujours pas arrivée, c''est la deuxième fois ce mois-ci.',
    'Quel est le problème évoqué ?',
    ARRAY['A) Une erreur de facturation','B) Un retard de livraison répété','C) Un produit défectueux','D) Un mauvais accueil'], 'B', '/mock/audio-co-33.mp3', 1),
  (v_exam_id, 'CO', 13, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Je comprends votre demande, mais le budget de cette année ne permet pas d''augmentation immédiate. On peut en reparler en fin d''année.',
    'Que propose l''employeur ?',
    ARRAY['A) Une augmentation immédiate','B) D''en reparler en fin d''année','C) Un refus définitif','D) Une prime à la place'], 'B', '/mock/audio-co-34.mp3', 1),
  (v_exam_id, 'CO', 14, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'À partir de la semaine prochaine, certains d''entre vous seront amenés à travailler depuis le nouveau site, en fonction des besoins de leur service.',
    'Que va-t-il se passer pour certains employés ?',
    ARRAY['A) Ils seront licenciés','B) Ils travailleront sur un nouveau site','C) Ils changeront de métier','D) Ils partiront en formation'], 'B', '/mock/audio-co-35.mp3', 1),
  (v_exam_id, 'CO', 15, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'On m''a dit que le projet prendrait du retard à cause d''un problème avec le fournisseur.',
    'Pourquoi le projet est-il en retard ?',
    ARRAY['A) Un problème avec le fournisseur','B) Un manque de personnel','C) Une erreur de planning','D) Un problème informatique'], 'A', '/mock/audio-co-36.mp3', 1),
  (v_exam_id, 'CO', 16, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le poste que vous avez proposé en interne est bien ouvert, mais la direction souhaite d''abord recevoir les candidatures externes avant de statuer.',
    'Que doit-on comprendre sur le poste interne ?',
    ARRAY['A) Il est déjà attribué','B) La décision est retardée par les candidatures externes','C) Il est annulé','D) Il est réservé en priorité aux internes'], 'B', '/mock/audio-co-37.mp3', 1),
  (v_exam_id, 'CO', 17, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Le client a l''air satisfait, mais il a quand même demandé plusieurs modifications avant validation finale.',
    'Quelle est la situation exacte du projet ?',
    ARRAY['A) Le client a tout refusé','B) Le projet est validé sans réserve','C) Des modifications sont demandées avant validation','D) Le projet est annulé'], 'C', '/mock/audio-co-38.mp3', 1),
  (v_exam_id, 'CO', 18, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'On a beaucoup aimé votre profil, mais un autre candidat a plus d''expérience dans ce secteur précis.',
    'Que peut-on déduire de cette phrase ?',
    ARRAY['A) Le poste est accepté','B) Un autre candidat est peut-être privilégié','C) Le poste est annulé','D) Il faut repostuler plus tard'], 'B', '/mock/audio-co-39.mp3', 1),
  (v_exam_id, 'CO', 19, 'audio', 'Écoutez attentivement le document sonore et répondez à la question.',
    'Nous reviendrons vers vous d''ici la fin de la semaine, mais sachez que nous recevons encore quelques candidats en parallèle.',
    'Que signifie cette phrase pour le candidat ?',
    ARRAY['A) Le poste lui est acquis','B) D''autres candidats sont encore en lice','C) L''entretien s''est mal passé','D) Il doit repostuler'], 'B', '/mock/audio-co-40.mp3', 1);

  -- ===================== CE — 20 questions (order_index 20-39) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, texte, question, options, correct_answer)
  VALUES
  (v_exam_id, 'CE', 20, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La société TechNova recrute un développeur web junior en CDI, à pourvoir immédiatement. Télétravail possible deux jours par semaine. Envoyer CV et lettre de motivation à recrutement@technova.fr avant le 30 du mois.',
    'Quel type de contrat est proposé ?',
    ARRAY['A) CDD','B) CDI','C) Stage','D) Intérim'], 'B'),
  (v_exam_id, 'CE', 21, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La société TechNova recrute un développeur web junior en CDI, à pourvoir immédiatement. Télétravail possible deux jours par semaine. Envoyer CV et lettre de motivation à recrutement@technova.fr avant le 30 du mois.',
    'Combien de jours de télétravail sont possibles ?',
    ARRAY['A) Aucun','B) Un jour','C) Deux jours','D) Cinq jours'], 'C'),
  (v_exam_id, 'CE', 22, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Suite à votre candidature, nous avons le plaisir de vous convier à un entretien le mardi 14 à 10h dans nos locaux. Merci de vous munir d''une pièce d''identité et de votre CV.',
    'Que faut-il apporter à l''entretien ?',
    ARRAY['A) Une pièce d''identité et le CV','B) Un diplôme uniquement','C) Un chèque de caution','D) Rien de particulier'], 'A'),
  (v_exam_id, 'CE', 23, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Suite à votre candidature, nous avons le plaisir de vous convier à un entretien le mardi 14 à 10h dans nos locaux. Merci de vous munir d''une pièce d''identité et de votre CV.',
    'Quel jour a lieu l''entretien ?',
    ARRAY['A) Lundi','B) Mardi','C) Mercredi','D) Jeudi'], 'B'),
  (v_exam_id, 'CE', 24, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le règlement intérieur précise que les heures supplémentaires doivent être validées par le responsable de service avant d''être effectuées, sous peine de non-paiement.',
    'Que faut-il faire avant d''effectuer des heures supplémentaires ?',
    ARRAY['A) Rien de spécial','B) Obtenir la validation du responsable','C) Prévenir les collègues','D) Attendre la fin du mois'], 'B'),
  (v_exam_id, 'CE', 25, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le règlement intérieur précise que les heures supplémentaires doivent être validées par le responsable de service avant d''être effectuées, sous peine de non-paiement.',
    'Que risque-t-on si cette règle n''est pas respectée ?',
    ARRAY['A) Un avertissement écrit','B) Le non-paiement des heures','C) Un licenciement','D) Rien'], 'B'),
  (v_exam_id, 'CE', 26, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La direction rappelle que le télétravail est accordé sur demande écrite auprès du manager, avec un maximum de trois jours par semaine, sous réserve des impératifs du service.',
    'Combien de jours de télétravail maximum sont autorisés ?',
    ARRAY['A) Un jour','B) Deux jours','C) Trois jours','D) Cinq jours'], 'C'),
  (v_exam_id, 'CE', 27, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'La direction rappelle que le télétravail est accordé sur demande écrite auprès du manager, avec un maximum de trois jours par semaine, sous réserve des impératifs du service.',
    'Comment faut-il demander le télétravail ?',
    ARRAY['A) Oralement','B) Par demande écrite au manager','C) Automatiquement accordé','D) Via un formulaire papier envoyé aux RH'], 'B'),
  (v_exam_id, 'CE', 28, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Nous vous informons que Julie Martin quittera l''entreprise le 30 de ce mois pour un nouveau projet professionnel. Un pot de départ sera organisé le vendredi précédent.',
    'Pourquoi Julie Martin quitte-t-elle l''entreprise ?',
    ARRAY['A) Elle est licenciée','B) Pour un nouveau projet professionnel','C) Elle part à la retraite','D) L''entreprise ferme'], 'B'),
  (v_exam_id, 'CE', 29, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Nous vous informons que Julie Martin quittera l''entreprise le 30 de ce mois pour un nouveau projet professionnel. Un pot de départ sera organisé le vendredi précédent.',
    'Quand aura lieu le pot de départ ?',
    ARRAY['A) Le jour de son départ','B) Le vendredi précédent son départ','C) Le lendemain de son départ','D) Il n''y en a pas'], 'B'),
  (v_exam_id, 'CE', 30, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Tous les employés du service commercial doivent suivre une formation obligatoire sur le nouveau logiciel de gestion avant la fin du mois, sous peine de ne plus pouvoir traiter les commandes.',
    'Qui est concerné par cette formation ?',
    ARRAY['A) Tous les employés','B) Le service commercial uniquement','C) Les nouveaux employés','D) La direction uniquement'], 'B'),
  (v_exam_id, 'CE', 31, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Tous les employés du service commercial doivent suivre une formation obligatoire sur le nouveau logiciel de gestion avant la fin du mois, sous peine de ne plus pouvoir traiter les commandes.',
    'Que se passe-t-il si la formation n''est pas suivie ?',
    ARRAY['A) Rien','B) Impossibilité de traiter les commandes','C) Une prime est retirée','D) Un jour de congé en moins'], 'B'),
  (v_exam_id, 'CE', 32, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le contrat à durée déterminée proposé est d''une durée de six mois, renouvelable une fois, avec une période d''essai d''un mois.',
    'Quelle est la durée initiale du contrat ?',
    ARRAY['A) Un mois','B) Trois mois','C) Six mois','D) Un an'], 'C'),
  (v_exam_id, 'CE', 33, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Le contrat à durée déterminée proposé est d''une durée de six mois, renouvelable une fois, avec une période d''essai d''un mois.',
    'Le contrat peut-il être renouvelé ?',
    ARRAY['A) Non, jamais','B) Oui, une fois','C) Oui, indéfiniment','D) Seulement après deux ans'], 'B'),
  (v_exam_id, 'CE', 34, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Suite aux retours des équipes, la direction a décidé de maintenir l''open space actuel, tout en installant des cabines téléphoniques pour les appels nécessitant de la confidentialité.',
    'Qu''est-ce qui va changer dans les bureaux ?',
    ARRAY['A) L''open space sera supprimé','B) Des cabines téléphoniques seront installées','C) Tout le monde aura un bureau fermé','D) Rien ne va changer'], 'B'),
  (v_exam_id, 'CE', 35, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'Suite aux retours des équipes, la direction a décidé de maintenir l''open space actuel, tout en installant des cabines téléphoniques pour les appels nécessitant de la confidentialité.',
    'Pourquoi la direction a-t-elle pris cette décision ?',
    ARRAY['A) Suite aux retours des équipes','B) Pour réduire les coûts','C) À la demande d''un client','D) Pour une question de sécurité'], 'A'),
  (v_exam_id, 'CE', 36, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'De plus en plus d''entreprises proposent désormais des entretiens d''embauche en visioconférence, une pratique qui s''est généralisée et qui permet de réduire les délais de recrutement.',
    'Quelle pratique s''est généralisée selon l''article ?',
    ARRAY['A) Les entretiens en visioconférence','B) Les tests écrits','C) Les périodes d''essai plus longues','D) Le recrutement sans entretien'], 'A'),
  (v_exam_id, 'CE', 37, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'De plus en plus d''entreprises proposent désormais des entretiens d''embauche en visioconférence, une pratique qui s''est généralisée et qui permet de réduire les délais de recrutement.',
    'Quel est l''avantage mentionné de cette pratique ?',
    ARRAY['A) Elle coûte moins cher','B) Elle réduit les délais de recrutement','C) Elle est obligatoire','D) Elle remplace le CV'], 'B'),
  (v_exam_id, 'CE', 38, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'En raison des bons résultats du trimestre, la direction a décidé d''attribuer une prime exceptionnelle à l''ensemble des salariés, versée avec le salaire du mois prochain.',
    'Pourquoi cette prime est-elle attribuée ?',
    ARRAY['A) Pour compenser une baisse de salaire','B) En raison des bons résultats du trimestre','C) Pour remplacer les congés','D) À l''occasion d''une fête d''entreprise'], 'B'),
  (v_exam_id, 'CE', 39, 'text', 'Lisez attentivement le texte et répondez à la question.',
    'En raison des bons résultats du trimestre, la direction a décidé d''attribuer une prime exceptionnelle à l''ensemble des salariés, versée avec le salaire du mois prochain.',
    'Quand la prime sera-t-elle versée ?',
    ARRAY['A) Ce mois-ci','B) Le mois prochain avec le salaire','C) En fin d''année','D) Jamais, c''est symbolique'], 'B');

  -- ===================== EE — 2 questions (order_index 40-41) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, prompt, min_words, max_time)
  VALUES
  (v_exam_id, 'EE', 40, 'writing', 'Section A : Rédiger un message simple et clair.',
    'Vous êtes absent(e) au travail pour cause de maladie. Écrivez un message à votre manager pour l''informer de votre absence et de la durée prévue. (40 mots minimum)',
    40, 10),
  (v_exam_id, 'EE', 41, 'writing', 'Section B : Présenter et justifier votre candidature.',
    'Vous postulez pour un poste dans une entreprise. Écrivez une lettre de motivation expliquant votre parcours et pourquoi ce poste vous intéresse. (100 mots minimum)',
    100, 20);

  -- ===================== EO — 2 questions (order_index 42-43) =====================
  INSERT INTO public.exam_questions
    (exam_id, section, order_index, type, instructions, prompt, prep_time, speak_time)
  VALUES
  (v_exam_id, 'EO', 42, 'speaking', 'Section A : Poser des questions pour obtenir des informations.',
    'Vous appelez une entreprise pour vous renseigner sur un poste vacant : missions, horaires et démarches pour postuler.',
    1, 5),
  (v_exam_id, 'EO', 43, 'speaking', 'Section B : Exprimer et défendre un point de vue.',
    'Un collègue hésite à demander une augmentation à son responsable. Convainquez-le de faire cette demande en donnant des arguments.',
    1, 5);

END $$;
