-- Item 7 du plan vocabulaire 1500 mots : compléter la catégorie 'Administration'
-- 53 -> 125 mots (72 nouveaux mots, répartis A1:6 A2:20 B1:23 B2:23).
-- Vérifications effectuées avant livraison :
--  - dédup contre les 218 mots existants ET les 116 mots Vie Sociale (item 4, déjà livrés)
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Un timbre', 'Vignette collée sur une enveloppe pour l''envoyer par la poste.', 'J''achète un timbre pour envoyer cette lettre.', 'A1', 'Administration'),
  ('Une enveloppe', 'Pochette en papier pour envoyer une lettre.', 'Mets le formulaire dans une enveloppe.', 'A1', 'Administration'),
  ('Un agent d''accueil', 'Personne qui reçoit le public dans une administration.', 'L''agent d''accueil m''a expliqué la procédure.', 'A1', 'Administration'),
  ('Une file d''attente', 'Ligne de personnes qui attendent leur tour.', 'Il y avait une longue file d''attente à la préfecture.', 'A1', 'Administration'),
  ('Un ticket', 'Petit papier numéroté pour attendre son tour.', 'Prenez un ticket avant de vous asseoir.', 'A1', 'Administration'),
  ('Une administration', 'Ensemble des services publics qui gèrent les démarches officielles.', 'Cette administration est ouverte du lundi au vendredi.', 'A1', 'Administration'),
  ('Le service public', 'Organisme de l''État qui répond aux besoins des citoyens.', 'La mairie est un service public de proximité.', 'A2', 'Administration'),
  ('Un rendez-vous en ligne', 'Rendez-vous administratif pris via internet.', 'J''ai pris un rendez-vous en ligne pour mon passeport.', 'A2', 'Administration'),
  ('Un espace personnel', 'Compte en ligne sur un site administratif.', 'Connectez-vous à votre espace personnel pour suivre votre dossier.', 'A2', 'Administration'),
  ('Un identifiant', 'Code utilisé pour se connecter à un service en ligne.', 'Notez bien votre identifiant et votre mot de passe.', 'A2', 'Administration'),
  ('Un mot de passe', 'Suite de caractères secrète pour accéder à un compte.', 'N''oubliez pas votre mot de passe pour le site des impôts.', 'A2', 'Administration'),
  ('Une pièce jointe', 'Document ajouté à un email ou un dossier en ligne.', 'Ajoutez une pièce jointe avec la copie de votre passeport.', 'A2', 'Administration'),
  ('Un scan', 'Copie numérique d''un document papier.', 'Envoyez un scan de votre justificatif de domicile.', 'A2', 'Administration'),
  ('Une attestation', 'Document qui certifie un fait ou une situation.', 'Demandez une attestation de domicile à votre propriétaire.', 'A2', 'Administration'),
  ('Un certificat de scolarité', 'Document prouvant qu''un enfant est inscrit à l''école.', 'Le certificat de scolarité est demandé pour les allocations familiales.', 'A2', 'Administration'),
  ('Une carte grise', 'Document officiel prouvant qu''on est propriétaire d''un véhicule.', 'Il faut changer la carte grise après un déménagement.', 'A2', 'Administration'),
  ('Un permis de conduire', 'Document autorisant à conduire un véhicule.', 'Mon permis de conduire est valable quinze ans.', 'A2', 'Administration'),
  ('Une amende', 'Somme d''argent à payer en cas d''infraction.', 'J''ai reçu une amende pour stationnement interdit.', 'A2', 'Administration'),
  ('Le tribunal', 'Lieu où la justice est rendue.', 'Il doit se présenter au tribunal la semaine prochaine.', 'A2', 'Administration'),
  ('Un avocat', 'Personne qui défend une personne devant la justice.', 'Elle a pris un avocat pour son dossier de naturalisation.', 'A2', 'Administration'),
  ('Un notaire', 'Officier public qui authentifie certains actes juridiques.', 'Le notaire s''occupe de la vente de la maison.', 'A2', 'Administration'),
  ('Une déclaration de perte', 'Démarche pour signaler la perte d''un document officiel.', 'J''ai fait une déclaration de perte pour ma carte d''identité.', 'A2', 'Administration'),
  ('Un vol de papiers', 'Situation où des documents officiels sont volés.', 'En cas de vol de papiers, il faut porter plainte.', 'A2', 'Administration'),
  ('Le commissariat', 'Lieu où l''on porte plainte ou signale un problème.', 'Je suis allé au commissariat pour signaler le vol.', 'A2', 'Administration'),
  ('Une plainte', 'Déclaration officielle d''un délit auprès de la police.', 'Elle a déposé une plainte au commissariat.', 'A2', 'Administration'),
  ('Le service des impôts', 'Administration chargée de collecter les impôts.', 'J''ai appelé le service des impôts pour une question.', 'A2', 'Administration'),
  ('L''huissier de justice', 'Officier chargé de faire exécuter certaines décisions de justice.', 'L''huissier de justice a remis la convocation.', 'B1', 'Administration'),
  ('Le tribunal administratif', 'Juridiction qui juge les litiges avec l''administration.', 'Il a saisi le tribunal administratif après le refus de la préfecture.', 'B1', 'Administration'),
  ('La légalisation de signature', 'Procédure officielle qui certifie l''authenticité d''une signature.', 'La légalisation de signature se fait en mairie.', 'B1', 'Administration'),
  ('Un acte notarié', 'Document officiel rédigé et certifié par un notaire.', 'La vente du bien a été formalisée par un acte notarié.', 'B1', 'Administration'),
  ('Le silence de l''administration', 'Absence de réponse de l''administration dans un délai donné.', 'Le silence de l''administration vaut parfois acceptation.', 'B1', 'Administration'),
  ('Un dossier incomplet', 'Dossier administratif auquel il manque des documents.', 'Votre dossier incomplet ne peut pas être traité.', 'B1', 'Administration'),
  ('La régularisation', 'Procédure qui met une situation en conformité avec la loi.', 'Il a déposé une demande de régularisation de sa situation.', 'B1', 'Administration'),
  ('Une carte de résident', 'Titre de séjour de longue durée pour les étrangers.', 'La carte de résident est valable dix ans.', 'B1', 'Administration'),
  ('Le visa long séjour', 'Autorisation permettant de rester plus de trois mois en France.', 'Elle est arrivée avec un visa long séjour.', 'B1', 'Administration'),
  ('Le renouvellement', 'Action de prolonger la validité d''un document.', 'Le renouvellement du titre de séjour doit être demandé à temps.', 'B1', 'Administration'),
  ('Une carte professionnelle', 'Document officiel lié à l''exercice d''une profession.', 'Les artisans doivent avoir une carte professionnelle.', 'B1', 'Administration'),
  ('Le contentieux', 'Ensemble des litiges soumis à la justice.', 'Le contentieux administratif concerne les litiges avec l''État.', 'B1', 'Administration'),
  ('Une ordonnance de référé', 'Décision rapide d''un juge en cas d''urgence.', 'Le juge a rendu une ordonnance de référé.', 'B1', 'Administration'),
  ('Le médiateur', 'Personne chargée de faciliter le dialogue entre l''administration et le citoyen.', 'Le médiateur a réglé le litige avec la caisse d''allocations familiales.', 'B1', 'Administration'),
  ('La caisse d''allocations familiales', 'Organisme qui verse les aides sociales aux familles.', 'La caisse d''allocations familiales verse les allocations logement chaque mois.', 'B1', 'Administration'),
  ('Un numéro de sécurité sociale', 'Numéro unique attribué à chaque personne pour la protection sociale.', 'Votre numéro de sécurité sociale figure sur votre carte Vitale.', 'B1', 'Administration'),
  ('Le fichier national', 'Base de données administrative centralisée.', 'Ses informations sont enregistrées dans un fichier national.', 'B1', 'Administration'),
  ('La biométrie', 'Technique d''identification basée sur les empreintes ou le visage.', 'La biométrie est utilisée pour les passeports biométriques.', 'B1', 'Administration'),
  ('Le passeport biométrique', 'Passeport contenant une puce électronique avec les données du titulaire.', 'Le passeport biométrique facilite les contrôles aux frontières.', 'B1', 'Administration'),
  ('Une autorisation de travail', 'Document permettant à un étranger de travailler en France.', 'Il a besoin d''une autorisation de travail pour signer son contrat.', 'B1', 'Administration'),
  ('L''attestation d''accueil', 'Document nécessaire pour recevoir un visiteur étranger.', 'Il a demandé une attestation d''accueil à la mairie.', 'B1', 'Administration'),
  ('Le droit des étrangers', 'Ensemble des règles concernant le séjour des étrangers en France.', 'Cet avocat est spécialisé en droit des étrangers.', 'B1', 'Administration'),
  ('Une demande de naturalisation', 'Dossier déposé pour obtenir la nationalité française.', 'Sa demande de naturalisation est en cours d''instruction.', 'B1', 'Administration'),
  ('Le contentieux administratif', 'Litige opposant un citoyen à l''administration devant un tribunal.', 'Le contentieux administratif a duré plusieurs années.', 'B2', 'Administration'),
  ('La juridiction administrative', 'Ensemble des tribunaux compétents pour juger l''administration.', 'La juridiction administrative est distincte des tribunaux judiciaires.', 'B2', 'Administration'),
  ('Le référé-suspension', 'Procédure d''urgence pour suspendre une décision administrative.', 'Il a déposé un référé-suspension contre l''arrêté préfectoral.', 'B2', 'Administration'),
  ('La compétence liée', 'Situation où l''administration n''a pas de pouvoir d''appréciation.', 'Le préfet agit ici en compétence liée.', 'B2', 'Administration'),
  ('Le pouvoir discrétionnaire', 'Marge de décision laissée à l''administration par la loi.', 'Le préfet dispose d''un pouvoir discrétionnaire pour cette décision.', 'B2', 'Administration'),
  ('La motivation d''une décision', 'Obligation d''expliquer les raisons d''une décision administrative.', 'La motivation d''une décision de refus doit être écrite.', 'B2', 'Administration'),
  ('Le vice de procédure', 'Erreur dans la façon dont une décision a été prise.', 'Le recours invoque un vice de procédure.', 'B2', 'Administration'),
  ('L''excès de pouvoir', 'Décision administrative illégale car dépassant les compétences autorisées.', 'Le recours pour excès de pouvoir vise à annuler la décision.', 'B2', 'Administration'),
  ('La prescription administrative', 'Délai au-delà duquel une action administrative n''est plus possible.', 'La prescription administrative empêche toute nouvelle demande après ce délai.', 'B2', 'Administration'),
  ('Le principe de légalité', 'Obligation pour l''administration de respecter la loi.', 'Le principe de légalité encadre toutes les décisions publiques.', 'B2', 'Administration'),
  ('La dématérialisation', 'Remplacement des documents papier par des procédures numériques.', 'La dématérialisation des démarches a simplifié les demandes de titre de séjour.', 'B2', 'Administration'),
  ('Le guichet unique', 'Service centralisant plusieurs démarches administratives en un seul lieu.', 'Le guichet unique facilite les démarches des nouveaux arrivants.', 'B2', 'Administration'),
  ('L''interopérabilité des données', 'Capacité des administrations à échanger des informations entre elles.', 'L''interopérabilité des données évite de fournir plusieurs fois le même document.', 'B2', 'Administration'),
  ('La déconcentration', 'Répartition du pouvoir de l''État vers ses représentants locaux.', 'La déconcentration donne plus de pouvoir aux préfets.', 'B2', 'Administration'),
  ('La décentralisation', 'Transfert de compétences de l''État vers les collectivités locales.', 'La décentralisation a renforcé le rôle des régions.', 'B2', 'Administration'),
  ('Le contrôle de légalité', 'Vérification par le préfet de la conformité des actes locaux à la loi.', 'Le contrôle de légalité peut annuler une décision municipale.', 'B2', 'Administration'),
  ('La tutelle administrative', 'Ancien contrôle exercé par l''État sur les collectivités locales.', 'La tutelle administrative a été supprimée par les lois de décentralisation.', 'B2', 'Administration'),
  ('Le principe du contradictoire', 'Droit de connaître et de répondre aux arguments avant une décision.', 'Le principe du contradictoire garantit les droits de la défense.', 'B2', 'Administration'),
  ('La charge de la preuve', 'Obligation de prouver un fait dans une procédure.', 'La charge de la preuve incombe souvent à l''administration.', 'B2', 'Administration'),
  ('L''opposabilité', 'Caractère d''un acte qui peut être imposé à un tiers.', 'Ce document n''a pas d''opposabilité tant qu''il n''est pas publié.', 'B2', 'Administration'),
  ('La caducité', 'Fin de la validité d''un acte faute d''action dans les délais.', 'La demande est frappée de caducité après six mois sans réponse.', 'B2', 'Administration'),
  ('Le retrait d''un acte administratif', 'Suppression rétroactive d''une décision administrative.', 'Le retrait d''un acte administratif illégal est possible sous certaines conditions.', 'B2', 'Administration'),
  ('L''abrogation', 'Suppression d''un acte administratif pour l''avenir uniquement.', 'L''abrogation du décret prend effet immédiatement.', 'B2', 'Administration');
