-- Item 6.6 du plan vocabulaire 1500 mots : nouvelle catégorie 'Environnement, Météo & Nature'
-- 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 1250 mots déjà en base : aucune collision
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Le soleil', 'Étoile qui éclaire et réchauffe la Terre.', 'Le soleil brille aujourd''hui.', 'A1', 'Environnement, Météo & Nature'),
  ('La pluie', 'Eau qui tombe du ciel.', 'Il y a de la pluie ce matin.', 'A1', 'Environnement, Météo & Nature'),
  ('Le vent', 'Air qui se déplace.', 'Le vent souffle fort aujourd''hui.', 'A1', 'Environnement, Météo & Nature'),
  ('La neige', 'Précipitation blanche et froide.', 'La neige tombe en hiver.', 'A1', 'Environnement, Météo & Nature'),
  ('Le nuage', 'Masse blanche ou grise dans le ciel.', 'Le ciel est couvert de nuages.', 'A1', 'Environnement, Météo & Nature'),
  ('Le ciel', 'Espace visible au-dessus de la Terre.', 'Le ciel est bleu aujourd''hui.', 'A1', 'Environnement, Météo & Nature'),
  ('Un arbre', 'Grande plante avec un tronc et des branches.', 'Il y a un grand arbre devant la maison.', 'A1', 'Environnement, Météo & Nature'),
  ('Une fleur', 'Partie colorée d''une plante.', 'Elle a offert des fleurs à sa mère.', 'A1', 'Environnement, Météo & Nature'),
  ('L''herbe', 'Petite plante verte qui recouvre le sol.', 'Les enfants jouent dans l''herbe.', 'A1', 'Environnement, Météo & Nature'),
  ('Un animal', 'Être vivant qui n''est pas une plante.', 'Le chat est mon animal préféré.', 'A1', 'Environnement, Météo & Nature'),
  ('Un oiseau', 'Animal qui vole et a des plumes.', 'Un oiseau chante dans le jardin.', 'A1', 'Environnement, Météo & Nature'),
  ('La mer', 'Grande étendue d''eau salée.', 'Nous allons à la mer cet été.', 'A1', 'Environnement, Météo & Nature'),
  ('La montagne', 'Relief élevé du paysage.', 'Nous partons en montagne pour skier.', 'A1', 'Environnement, Météo & Nature'),
  ('La forêt', 'Grand espace couvert d''arbres.', 'Ils se promènent dans la forêt.', 'A1', 'Environnement, Météo & Nature'),
  ('Le froid', 'Basse température.', 'Il fait très froid ce matin.', 'A1', 'Environnement, Météo & Nature'),
  ('La chaleur', 'Haute température.', 'La chaleur est forte cet été.', 'A1', 'Environnement, Météo & Nature'),
  ('Une saison', 'Période de l''année (printemps, été, automne, hiver).', 'Le printemps est ma saison préférée.', 'A1', 'Environnement, Météo & Nature'),
  ('L''hiver', 'Saison la plus froide de l''année.', 'Il neige souvent en hiver.', 'A1', 'Environnement, Météo & Nature'),
  ('L''été', 'Saison la plus chaude de l''année.', 'Nous partons en vacances en été.', 'A1', 'Environnement, Météo & Nature'),
  ('Le printemps', 'Saison entre l''hiver et l''été.', 'Les fleurs poussent au printemps.', 'A2', 'Environnement, Météo & Nature'),
  ('L''automne', 'Saison entre l''été et l''hiver.', 'Les feuilles tombent en automne.', 'A2', 'Environnement, Météo & Nature'),
  ('Un orage', 'Phénomène météo avec pluie, vent et éclairs.', 'Un orage est prévu ce soir.', 'A2', 'Environnement, Météo & Nature'),
  ('Un éclair', 'Décharge électrique visible pendant un orage.', 'L''éclair a illuminé le ciel.', 'A2', 'Environnement, Météo & Nature'),
  ('Le tonnerre', 'Bruit qui suit un éclair.', 'Le tonnerre a réveillé les enfants.', 'A2', 'Environnement, Météo & Nature'),
  ('Le brouillard', 'Nuage bas qui réduit la visibilité.', 'Le brouillard rendait la route dangereuse.', 'A2', 'Environnement, Météo & Nature'),
  ('La température', 'Mesure du chaud ou du froid.', 'La température a baissé ce matin.', 'A2', 'Environnement, Météo & Nature'),
  ('Les prévisions météo', 'Informations sur le temps qu''il va faire.', 'J''ai consulté les prévisions météo avant de partir.', 'A2', 'Environnement, Météo & Nature'),
  ('Un parapluie', 'Objet pour se protéger de la pluie.', 'N''oublie pas ton parapluie.', 'A2', 'Environnement, Météo & Nature'),
  ('Le climat', 'Ensemble des conditions météorologiques d''une région.', 'Le climat méditerranéen est doux en hiver.', 'A2', 'Environnement, Météo & Nature'),
  ('La faune', 'Ensemble des animaux d''une région.', 'La faune de cette forêt est très variée.', 'A2', 'Environnement, Météo & Nature'),
  ('La flore', 'Ensemble des plantes d''une région.', 'La flore alpine s''adapte au froid.', 'A2', 'Environnement, Météo & Nature'),
  ('Un lac', 'Étendue d''eau douce entourée de terre.', 'Nous avons pique-niqué au bord du lac.', 'A2', 'Environnement, Météo & Nature'),
  ('Une rivière', 'Cours d''eau qui se jette dans un fleuve ou la mer.', 'Les enfants jouent près de la rivière.', 'A2', 'Environnement, Météo & Nature'),
  ('Un fleuve', 'Grand cours d''eau qui se jette dans la mer.', 'La Seine est un fleuve français.', 'A2', 'Environnement, Météo & Nature'),
  ('Une plage', 'Zone de sable ou de galets au bord de la mer.', 'Nous passons la journée à la plage.', 'A2', 'Environnement, Météo & Nature'),
  ('Un jardin public', 'Espace vert ouvert à tous.', 'Le jardin public est très fréquenté le week-end.', 'A2', 'Environnement, Météo & Nature'),
  ('Un parc naturel', 'Zone protégée pour préserver la nature.', 'Ce parc naturel abrite de nombreuses espèces.', 'A2', 'Environnement, Météo & Nature'),
  ('Une espèce', 'Groupe d''animaux ou de plantes similaires.', 'Cette espèce d''oiseau est protégée.', 'A2', 'Environnement, Météo & Nature'),
  ('Une espèce en voie de disparition', 'Espèce menacée d''extinction.', 'Le lynx est une espèce en voie de disparition en France.', 'A2', 'Environnement, Météo & Nature'),
  ('La pollution', 'Dégradation de l''environnement par des substances nocives.', 'La pollution de l''air touche les grandes villes.', 'A2', 'Environnement, Météo & Nature'),
  ('Le recyclage', 'Transformation des déchets en nouveaux produits.', 'Le recyclage du verre est facile à faire.', 'A2', 'Environnement, Météo & Nature'),
  ('Une poubelle de tri', 'Poubelle destinée à un type précis de déchet.', 'Mettez le carton dans la poubelle de tri.', 'A2', 'Environnement, Météo & Nature'),
  ('Les déchets', 'Matières inutilisées jetées après usage.', 'Les déchets sont ramassés chaque semaine.', 'A2', 'Environnement, Météo & Nature'),
  ('L''énergie renouvelable', 'Énergie produite à partir de sources naturelles inépuisables.', 'Le solaire est une énergie renouvelable.', 'A2', 'Environnement, Météo & Nature'),
  ('Un panneau solaire', 'Dispositif qui transforme la lumière du soleil en électricité.', 'Ils ont installé des panneaux solaires sur le toit.', 'A2', 'Environnement, Météo & Nature'),
  ('Une éolienne', 'Machine qui produit de l''électricité grâce au vent.', 'Les éoliennes tournent sur la colline.', 'A2', 'Environnement, Météo & Nature'),
  ('L''eau potable', 'Eau que l''on peut boire sans danger.', 'L''accès à l''eau potable n''est pas garanti partout.', 'A2', 'Environnement, Météo & Nature'),
  ('Une sécheresse', 'Longue période sans pluie.', 'La sécheresse a touché plusieurs régions cet été.', 'A2', 'Environnement, Météo & Nature'),
  ('Une inondation', 'Débordement d''eau qui recouvre un terrain.', 'L''inondation a endommagé plusieurs maisons.', 'A2', 'Environnement, Météo & Nature'),
  ('Une canicule', 'Période de chaleur intense et prolongée.', 'La canicule a duré une semaine.', 'A2', 'Environnement, Météo & Nature'),
  ('Le réchauffement climatique', 'Augmentation de la température moyenne de la Terre.', 'Le réchauffement climatique inquiète les scientifiques.', 'A2', 'Environnement, Météo & Nature'),
  ('Un incendie de forêt', 'Feu qui se propage dans une forêt.', 'Un incendie de forêt a ravagé la région.', 'A2', 'Environnement, Météo & Nature'),
  ('La biodiversité', 'Diversité des espèces vivantes dans un milieu.', 'La biodiversité diminue à cause de la déforestation.', 'A2', 'Environnement, Météo & Nature'),
  ('La déforestation', 'Destruction des forêts.', 'La déforestation menace de nombreuses espèces animales.', 'A2', 'Environnement, Météo & Nature'),
  ('Le compost', 'Matière organique décomposée utilisée comme engrais.', 'Nous faisons du compost avec les épluchures.', 'A2', 'Environnement, Météo & Nature'),
  ('Le gaspillage d''eau', 'Utilisation excessive et inutile de l''eau.', 'Il faut éviter le gaspillage d''eau à la maison.', 'A2', 'Environnement, Météo & Nature'),
  ('Le développement durable', 'Modèle de développement respectant l''environnement et les générations futures.', 'Le développement durable est enseigné dès le collège.', 'B1', 'Environnement, Météo & Nature'),
  ('La transition écologique', 'Passage vers un modèle économique plus respectueux de l''environnement.', 'La transition écologique implique tous les secteurs.', 'B1', 'Environnement, Météo & Nature'),
  ('L''empreinte carbone individuelle', 'Quantité de gaz à effet de serre produite par une personne.', 'Réduire son empreinte carbone individuelle passe par de petits gestes.', 'B1', 'Environnement, Météo & Nature'),
  ('Les gaz à effet de serre', 'Gaz qui retiennent la chaleur dans l''atmosphère.', 'Le CO2 est le principal gaz à effet de serre.', 'B1', 'Environnement, Météo & Nature'),
  ('La fonte des glaciers', 'Disparition progressive des glaces polaires ou montagnardes.', 'La fonte des glaciers accélère la montée du niveau des mers.', 'B1', 'Environnement, Météo & Nature'),
  ('La montée des eaux', 'Élévation du niveau des mers et océans.', 'La montée des eaux menace certaines îles.', 'B1', 'Environnement, Météo & Nature'),
  ('Un écosystème', 'Ensemble des êtres vivants et de leur environnement.', 'Cet écosystème abrite une grande diversité d''espèces.', 'B1', 'Environnement, Météo & Nature'),
  ('La chaîne alimentaire', 'Suite d''organismes qui se nourrissent les uns des autres.', 'La chaîne alimentaire marine est perturbée par la surpêche.', 'B1', 'Environnement, Météo & Nature'),
  ('La surpêche', 'Pêche excessive qui menace les populations de poissons.', 'La surpêche épuise certaines ressources marines.', 'B1', 'Environnement, Météo & Nature'),
  ('Une zone protégée', 'Territoire où la nature est préservée par la loi.', 'Cette zone protégée interdit la chasse.', 'B1', 'Environnement, Météo & Nature'),
  ('Un parc national', 'Grand territoire naturel protégé par l''État.', 'Le parc national des Écrins attire de nombreux randonneurs.', 'B1', 'Environnement, Météo & Nature'),
  ('La réserve naturelle', 'Espace naturel préservé pour protéger une biodiversité précise.', 'Cette réserve naturelle abrite des oiseaux migrateurs.', 'B1', 'Environnement, Météo & Nature'),
  ('Une espèce invasive', 'Espèce introduite qui menace l''équilibre d''un écosystème.', 'Cette espèce invasive concurrence les plantes locales.', 'B1', 'Environnement, Météo & Nature'),
  ('La pollution plastique', 'Contamination de l''environnement par les déchets plastiques.', 'La pollution plastique touche même les océans les plus reculés.', 'B1', 'Environnement, Météo & Nature'),
  ('Le microplastique', 'Petite particule de plastique polluant l''environnement.', 'Le microplastique se retrouve dans l''eau que nous buvons.', 'B1', 'Environnement, Météo & Nature'),
  ('Le tri sélectif', 'Séparation des déchets selon leur nature en vue du recyclage.', 'Le tri sélectif est obligatoire dans cette commune.', 'B1', 'Environnement, Météo & Nature'),
  ('L''agriculture durable', 'Méthode agricole qui préserve les ressources naturelles.', 'L''agriculture durable limite l''usage des produits chimiques.', 'B1', 'Environnement, Météo & Nature'),
  ('La permaculture', 'Méthode agricole qui imite les écosystèmes naturels.', 'La permaculture gagne en popularité chez les particuliers.', 'B1', 'Environnement, Météo & Nature'),
  ('Le label écologique', 'Certification garantissant le respect de critères environnementaux.', 'Ce produit porte un label écologique reconnu.', 'B1', 'Environnement, Météo & Nature'),
  ('La consommation d''énergie', 'Quantité d''énergie utilisée par un foyer ou une activité.', 'Réduire sa consommation d''énergie aide à limiter les émissions.', 'B1', 'Environnement, Météo & Nature'),
  ('Le mix énergétique', 'Répartition des différentes sources d''énergie utilisées par un pays.', 'Le mix énergétique français repose en partie sur le nucléaire.', 'B1', 'Environnement, Météo & Nature'),
  ('L''énergie nucléaire', 'Énergie produite par la fission de l''atome.', 'L''énergie nucléaire fournit une grande partie de l''électricité française.', 'B1', 'Environnement, Météo & Nature'),
  ('Les énergies fossiles', 'Sources d''énergie issues de matières organiques fossilisées, comme le pétrole.', 'La combustion des énergies fossiles produit du CO2.', 'B1', 'Environnement, Météo & Nature'),
  ('La qualité de l''air', 'Mesure de la pollution atmosphérique.', 'La qualité de l''air se dégrade lors des pics de pollution.', 'B1', 'Environnement, Météo & Nature'),
  ('Un pic de pollution', 'Épisode de forte pollution atmosphérique.', 'Un pic de pollution a été signalé dans la région parisienne.', 'B1', 'Environnement, Météo & Nature'),
  ('La circulation alternée', 'Mesure limitant la circulation des véhicules pour réduire la pollution.', 'La circulation alternée a été mise en place lors du pic de pollution.', 'B1', 'Environnement, Météo & Nature'),
  ('Le changement climatique', 'Modification durable des conditions climatiques de la planète.', 'Le changement climatique provoque des événements météorologiques extrêmes.', 'B1', 'Environnement, Météo & Nature'),
  ('Un événement climatique extrême', 'Phénomène météorologique inhabituel et intense.', 'Les inondations récentes sont un événement climatique extrême.', 'B1', 'Environnement, Météo & Nature'),
  ('La désertification', 'Transformation d''une région en désert.', 'La désertification progresse dans certaines zones sahéliennes.', 'B1', 'Environnement, Météo & Nature'),
  ('La déforestation illégale', 'Destruction de forêts sans autorisation légale.', 'La déforestation illégale menace la forêt amazonienne.', 'B1', 'Environnement, Météo & Nature'),
  ('Les accords internationaux sur le climat', 'Engagements pris par plusieurs pays pour lutter contre le changement climatique.', 'Les accords internationaux sur le climat fixent des objectifs de réduction d''émissions.', 'B1', 'Environnement, Météo & Nature'),
  ('L''Accord de Paris', 'Traité international sur le climat signé en 2015.', 'L''Accord de Paris vise à limiter le réchauffement climatique.', 'B1', 'Environnement, Météo & Nature'),
  ('La COP (Conférence des Parties)', 'Sommet international annuel sur le climat.', 'La COP réunit chaque année les représentants de nombreux pays.', 'B1', 'Environnement, Météo & Nature'),
  ('Une catastrophe naturelle', 'Événement naturel destructeur, comme un séisme ou un ouragan.', 'Cette catastrophe naturelle a fait de nombreuses victimes.', 'B1', 'Environnement, Météo & Nature'),
  ('Un séisme', 'Secousse de la surface terrestre.', 'Le séisme a été ressenti dans plusieurs régions.', 'B1', 'Environnement, Météo & Nature'),
  ('Une tempête', 'Vent violent souvent accompagné de pluie.', 'Une tempête a traversé la région cette nuit.', 'B1', 'Environnement, Météo & Nature'),
  ('Un ouragan', 'Tempête tropicale très violente.', 'L''ouragan a causé d''importants dégâts sur la côte.', 'B1', 'Environnement, Météo & Nature'),
  ('L''anthropocène', 'Époque géologique marquée par l''impact des activités humaines sur la planète.', 'Certains scientifiques parlent de l''anthropocène pour désigner notre époque.', 'B2', 'Environnement, Météo & Nature'),
  ('La résilience écologique', 'Capacité d''un écosystème à se rétablir après une perturbation.', 'La résilience écologique d''une forêt dépend de sa biodiversité.', 'B2', 'Environnement, Météo & Nature'),
  ('Le point de bascule climatique', 'Seuil au-delà duquel un changement climatique devient irréversible.', 'Les scientifiques redoutent d''atteindre un point de bascule climatique.', 'B2', 'Environnement, Météo & Nature'),
  ('La justice climatique', 'Principe selon lequel les responsabilités du changement climatique doivent être partagées équitablement.', 'La justice climatique met en avant les inégalités entre pays riches et pauvres.', 'B2', 'Environnement, Météo & Nature'),
  ('L''écoanxiété', 'Anxiété liée aux préoccupations environnementales.', 'L''écoanxiété touche particulièrement les jeunes générations.', 'B2', 'Environnement, Météo & Nature'),
  ('La sobriété énergétique', 'Réduction volontaire de la consommation d''énergie.', 'La sobriété énergétique est encouragée par les pouvoirs publics.', 'B2', 'Environnement, Météo & Nature'),
  ('La neutralité carbone', 'Équilibre entre les émissions de CO2 produites et celles absorbées.', 'La France vise la neutralité carbone d''ici 2050.', 'B2', 'Environnement, Météo & Nature'),
  ('La compensation carbone', 'Financement de projets écologiques pour compenser ses émissions de CO2.', 'Certaines entreprises pratiquent la compensation carbone.', 'B2', 'Environnement, Météo & Nature'),
  ('Le marché du carbone', 'Système d''échange de droits d''émission de CO2 entre entreprises.', 'Le marché du carbone européen fixe un prix sur les émissions.', 'B2', 'Environnement, Météo & Nature'),
  ('La taxe carbone', 'Impôt appliqué en fonction des émissions de CO2.', 'La taxe carbone incite les entreprises à réduire leurs émissions.', 'B2', 'Environnement, Météo & Nature'),
  ('L''écocide', 'Destruction grave et durable de l''environnement.', 'Certains juristes proposent de reconnaître l''écocide comme un crime international.', 'B2', 'Environnement, Météo & Nature'),
  ('Le droit de l''environnement', 'Ensemble des lois protégeant la nature et les ressources naturelles.', 'Le droit de l''environnement s''est renforcé ces dernières années.', 'B2', 'Environnement, Météo & Nature'),
  ('Le principe pollueur-payeur', 'Principe selon lequel celui qui pollue doit payer pour les dommages causés.', 'Le principe pollueur-payeur s''applique aux entreprises industrielles.', 'B2', 'Environnement, Météo & Nature'),
  ('L''évaluation d''impact environnemental', 'Étude des conséquences écologiques d''un projet avant sa réalisation.', 'Une évaluation d''impact environnemental est requise pour ce chantier.', 'B2', 'Environnement, Météo & Nature'),
  ('La sortie des énergies fossiles', 'Abandon progressif de l''usage du charbon, du pétrole et du gaz.', 'La sortie des énergies fossiles est un objectif à long terme.', 'B2', 'Environnement, Météo & Nature'),
  ('Les énergies marines renouvelables', 'Sources d''énergie produites grâce aux courants ou aux vagues.', 'Les énergies marines renouvelables se développent le long des côtes.', 'B2', 'Environnement, Météo & Nature'),
  ('L''hydrogène vert', 'Hydrogène produit à partir d''énergies renouvelables.', 'L''hydrogène vert est présenté comme une énergie d''avenir.', 'B2', 'Environnement, Météo & Nature'),
  ('La captation du carbone', 'Technique visant à capturer le CO2 émis pour limiter son impact.', 'La captation du carbone est encore une technologie coûteuse.', 'B2', 'Environnement, Météo & Nature'),
  ('La géo-ingénierie', 'Techniques visant à modifier volontairement le climat à grande échelle.', 'La géo-ingénierie divise la communauté scientifique.', 'B2', 'Environnement, Météo & Nature'),
  ('L''effondrement de la biodiversité', 'Diminution rapide et massive du nombre d''espèces vivantes.', 'L''effondrement de la biodiversité inquiète les écologues.', 'B2', 'Environnement, Météo & Nature'),
  ('La sixième extinction', 'Période actuelle de disparition massive d''espèces.', 'Certains scientifiques parlent d''une sixième extinction en cours.', 'B2', 'Environnement, Météo & Nature'),
  ('L''acidification des océans', 'Baisse du pH des océans due à l''absorption de CO2.', 'L''acidification des océans menace les récifs coralliens.', 'B2', 'Environnement, Météo & Nature'),
  ('Le blanchissement des coraux', 'Phénomène de dépérissement des coraux lié au réchauffement de l''eau.', 'Le blanchissement des coraux s''observe de plus en plus fréquemment.', 'B2', 'Environnement, Météo & Nature'),
  ('La déplétion des ressources', 'Épuisement progressif des ressources naturelles disponibles.', 'La déplétion des ressources menace certains secteurs industriels.', 'B2', 'Environnement, Météo & Nature'),
  ('L''économie verte', 'Modèle économique intégrant les enjeux environnementaux.', 'L''économie verte crée de nouveaux emplois qualifiés.', 'B2', 'Environnement, Météo & Nature'),
  ('La croissance verte', 'Développement économique conçu pour respecter l''environnement.', 'La croissance verte reste débattue parmi les économistes.', 'B2', 'Environnement, Météo & Nature'),
  ('Les migrations climatiques', 'Déplacements de populations causés par des changements environnementaux.', 'Les migrations climatiques devraient s''intensifier dans les décennies à venir.', 'B2', 'Environnement, Météo & Nature'),
  ('Un réfugié climatique', 'Personne contrainte de quitter son pays à cause de changements environnementaux.', 'Le statut de réfugié climatique n''est pas encore reconnu internationalement.', 'B2', 'Environnement, Météo & Nature'),
  ('La vulnérabilité environnementale', 'Sensibilité d''un territoire aux impacts du changement climatique.', 'Les zones côtières présentent une forte vulnérabilité environnementale.', 'B2', 'Environnement, Météo & Nature'),
  ('L''adaptation au changement climatique', 'Ensemble des mesures prises pour faire face aux effets du réchauffement.', 'L''adaptation au changement climatique concerne aussi les infrastructures urbaines.', 'B2', 'Environnement, Météo & Nature'),
  ('La résilience urbaine', 'Capacité d''une ville à faire face aux crises climatiques.', 'La résilience urbaine passe par la végétalisation des villes.', 'B2', 'Environnement, Météo & Nature'),
  ('La renaturation', 'Restauration d''espaces naturels dégradés par l''activité humaine.', 'La renaturation des berges améliore la qualité de l''eau.', 'B2', 'Environnement, Météo & Nature');
