-- Item 6.7 du plan vocabulaire 1500 mots : nouvelle catégorie 'Technologies & Numérique'
-- DERNIÈRE catégorie du plan. 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Une fois cette migration exécutée : 1375 -> 1500 mots, objectif du plan atteint.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 1375 mots déjà en base : aucune collision
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Un téléphone', 'Appareil pour appeler et communiquer.', 'J''appelle toujours avec mon téléphone.', 'A1', 'Technologies & Numérique'),
  ('Un smartphone', 'Téléphone intelligent connecté à internet.', 'Mon smartphone me sert aussi d''appareil photo.', 'A1', 'Technologies & Numérique'),
  ('Internet', 'Réseau mondial reliant les ordinateurs.', 'Je cherche des informations sur internet.', 'A1', 'Technologies & Numérique'),
  ('Un site internet', 'Ensemble de pages consultables en ligne.', 'J''ai trouvé cette recette sur un site internet.', 'A1', 'Technologies & Numérique'),
  ('Une application', 'Programme installé sur un smartphone ou un ordinateur.', 'J''utilise une application pour apprendre le français.', 'A1', 'Technologies & Numérique'),
  ('Un écran', 'Surface qui affiche des images ou du texte.', 'L''écran de mon téléphone est cassé.', 'A1', 'Technologies & Numérique'),
  ('Une tablette', 'Petit ordinateur tactile portable.', 'Les enfants regardent des vidéos sur la tablette.', 'A1', 'Technologies & Numérique'),
  ('Un clavier', 'Ensemble de touches pour écrire sur un ordinateur.', 'Le clavier de mon ordinateur est en panne.', 'A1', 'Technologies & Numérique'),
  ('Une souris', 'Appareil pour déplacer le curseur sur un écran.', 'J''ai besoin d''une nouvelle souris.', 'A1', 'Technologies & Numérique'),
  ('Un chargeur', 'Appareil pour recharger la batterie d''un appareil électronique.', 'J''ai oublié mon chargeur à la maison.', 'A1', 'Technologies & Numérique'),
  ('Une batterie', 'Source d''énergie d''un appareil électronique.', 'La batterie de mon téléphone est faible.', 'A1', 'Technologies & Numérique'),
  ('Le wifi', 'Connexion internet sans fil.', 'Le wifi ne fonctionne pas dans cette pièce.', 'A1', 'Technologies & Numérique'),
  ('Une photo numérique', 'Image enregistrée sous forme électronique.', 'J''ai pris une photo numérique du paysage.', 'A1', 'Technologies & Numérique'),
  ('Une vidéo', 'Contenu enregistré en images animées.', 'Cette vidéo a beaucoup de vues.', 'A1', 'Technologies & Numérique'),
  ('Un message', 'Texte envoyé à quelqu''un.', 'J''ai reçu un message de mon frère.', 'A1', 'Technologies & Numérique'),
  ('Envoyer', 'Faire parvenir quelque chose à quelqu''un.', 'J''envoie un message à ma sœur.', 'A1', 'Technologies & Numérique'),
  ('Télécharger', 'Enregistrer un fichier depuis internet.', 'Je télécharge une application sur mon téléphone.', 'A1', 'Technologies & Numérique'),
  ('Cliquer', 'Appuyer sur un élément avec la souris.', 'Cliquez ici pour continuer.', 'A1', 'Technologies & Numérique'),
  ('Se connecter', 'Accéder à un compte ou un service en ligne.', 'Je me connecte à mon compte tous les jours.', 'A1', 'Technologies & Numérique'),
  ('Un ordinateur portable', 'Ordinateur transportable et léger.', 'J''emmène mon ordinateur portable au travail.', 'A2', 'Technologies & Numérique'),
  ('Une adresse e-mail', 'Identifiant utilisé pour envoyer et recevoir des messages électroniques.', 'Donnez-moi votre adresse e-mail.', 'A2', 'Technologies & Numérique'),
  ('Un fichier', 'Ensemble de données enregistrées sous un nom.', 'J''ai envoyé le fichier par e-mail.', 'A2', 'Technologies & Numérique'),
  ('Un dossier', 'Espace numérique pour organiser des fichiers.', 'Range ce document dans le bon dossier.', 'A2', 'Technologies & Numérique'),
  ('Le stockage en ligne', 'Espace pour conserver ses fichiers sur internet.', 'J''utilise le stockage en ligne pour mes photos.', 'A2', 'Technologies & Numérique'),
  ('Le cloud', 'Ensemble de serveurs accessibles via internet pour stocker des données.', 'Mes documents sont sauvegardés dans le cloud.', 'A2', 'Technologies & Numérique'),
  ('Une mise à jour', 'Nouvelle version d''un logiciel ou d''une application.', 'Une mise à jour est disponible pour votre téléphone.', 'A2', 'Technologies & Numérique'),
  ('Un logiciel', 'Programme informatique.', 'Ce logiciel permet de modifier des photos.', 'A2', 'Technologies & Numérique'),
  ('Un navigateur', 'Programme utilisé pour naviguer sur internet.', 'Chrome est un navigateur très utilisé.', 'A2', 'Technologies & Numérique'),
  ('Un moteur de recherche', 'Outil pour trouver des informations sur internet.', 'Google est le moteur de recherche le plus utilisé.', 'A2', 'Technologies & Numérique'),
  ('Un compte en ligne', 'Espace personnel sur un site internet nécessitant une connexion.', 'J''ai créé un compte en ligne pour ce service.', 'A2', 'Technologies & Numérique'),
  ('La double authentification', 'Méthode de sécurité utilisant deux étapes de vérification.', 'La double authentification protège mieux votre compte.', 'A2', 'Technologies & Numérique'),
  ('Un antivirus', 'Logiciel qui protège contre les virus informatiques.', 'Installez un antivirus sur votre ordinateur.', 'A2', 'Technologies & Numérique'),
  ('Un virus informatique', 'Programme malveillant qui endommage un ordinateur.', 'Ce fichier contenait un virus informatique.', 'A2', 'Technologies & Numérique'),
  ('Le piratage informatique', 'Accès non autorisé à un système informatique.', 'Le piratage informatique peut coûter cher aux entreprises.', 'A2', 'Technologies & Numérique'),
  ('Une arnaque en ligne', 'Tentative de tromperie réalisée sur internet.', 'Méfiez-vous des arnaques en ligne.', 'A2', 'Technologies & Numérique'),
  ('Un hameçonnage', 'Technique frauduleuse visant à voler des informations personnelles.', 'Cet e-mail est une tentative d''hameçonnage.', 'A2', 'Technologies & Numérique'),
  ('La vie privée en ligne', 'Protection des informations personnelles sur internet.', 'La vie privée en ligne est un sujet sensible.', 'A2', 'Technologies & Numérique'),
  ('Un paramètre de confidentialité', 'Réglage permettant de contrôler la visibilité de ses informations.', 'Vérifiez vos paramètres de confidentialité sur les réseaux sociaux.', 'A2', 'Technologies & Numérique'),
  ('Un profil en ligne', 'Ensemble des informations personnelles publiées sur un service internet.', 'Elle a mis à jour son profil en ligne.', 'A2', 'Technologies & Numérique'),
  ('Une notification', 'Message d''alerte envoyé par une application.', 'J''ai reçu une notification sur mon téléphone.', 'A2', 'Technologies & Numérique'),
  ('Un forfait mobile', 'Offre incluant appels, SMS et internet sur un téléphone.', 'Mon forfait mobile inclut vingt gigaoctets de données.', 'A2', 'Technologies & Numérique'),
  ('La 4G et la 5G', 'Technologies de réseau mobile permettant l''accès à internet.', 'La 5G offre une connexion plus rapide.', 'A2', 'Technologies & Numérique'),
  ('Le débit internet', 'Vitesse de transfert des données sur internet.', 'Le débit internet est faible dans cette zone.', 'A2', 'Technologies & Numérique'),
  ('Une visioconférence', 'Réunion à distance avec image et son.', 'Nous organisons une visioconférence chaque lundi.', 'A2', 'Technologies & Numérique'),
  ('Un appel vidéo', 'Communication en direct avec image entre deux appareils.', 'J''ai fait un appel vidéo avec ma famille.', 'A2', 'Technologies & Numérique'),
  ('Une signature électronique', 'Signature numérique validant un document en ligne.', 'J''ai signé le contrat avec une signature électronique.', 'A2', 'Technologies & Numérique'),
  ('Un formulaire en ligne', 'Document à remplir directement sur internet.', 'J''ai rempli un formulaire en ligne pour ma demande.', 'A2', 'Technologies & Numérique'),
  ('Un objet connecté', 'Appareil relié à internet capable d''échanger des données.', 'La montre connectée est un objet connecté populaire.', 'A2', 'Technologies & Numérique'),
  ('Une montre connectée', 'Montre capable de se connecter à internet ou un téléphone.', 'Sa montre connectée compte ses pas.', 'A2', 'Technologies & Numérique'),
  ('Un haut-parleur connecté', 'Enceinte reliée à internet pouvant répondre à des commandes vocales.', 'Le haut-parleur connecté joue de la musique sur commande.', 'A2', 'Technologies & Numérique'),
  ('L''intelligence artificielle', 'Technologie permettant à une machine d''imiter certaines capacités humaines.', 'L''intelligence artificielle est utilisée dans de nombreuses applications.', 'A2', 'Technologies & Numérique'),
  ('Un assistant vocal', 'Programme qui répond à des commandes vocales.', 'J''utilise un assistant vocal pour régler une alarme.', 'A2', 'Technologies & Numérique'),
  ('La réalité virtuelle', 'Technologie simulant un environnement en trois dimensions.', 'La réalité virtuelle est utilisée dans certains jeux vidéo.', 'A2', 'Technologies & Numérique'),
  ('Le commerce en ligne', 'Achat et vente de produits via internet.', 'Le commerce en ligne a beaucoup progressé ces dernières années.', 'A2', 'Technologies & Numérique'),
  ('Un code QR', 'Code visuel scannable donnant accès à une information.', 'Scannez le code QR pour voir le menu.', 'A2', 'Technologies & Numérique'),
  ('Un service en ligne', 'Prestation accessible via internet.', 'Ce service en ligne facilite les démarches administratives.', 'A2', 'Technologies & Numérique'),
  ('La numérisation des services publics', 'Transformation des services administratifs en version numérique.', 'La numérisation des services publics facilite l''accès aux droits.', 'B1', 'Technologies & Numérique'),
  ('L''administration numérique', 'Ensemble des services publics accessibles en ligne.', 'L''administration numérique simplifie de nombreuses démarches.', 'B1', 'Technologies & Numérique'),
  ('France Connect', 'Système permettant de se connecter aux services publics avec un identifiant unique.', 'J''utilise France Connect pour accéder à mes impôts en ligne.', 'B1', 'Technologies & Numérique'),
  ('Un tiers de confiance numérique', 'Organisme habilité à authentifier une identité en ligne.', 'La banque agit comme tiers de confiance numérique.', 'B1', 'Technologies & Numérique'),
  ('La signature électronique qualifiée', 'Signature numérique ayant la même valeur légale qu''une signature manuscrite.', 'La signature électronique qualifiée est reconnue par la loi.', 'B1', 'Technologies & Numérique'),
  ('L''identité numérique', 'Ensemble des informations qui identifient une personne en ligne.', 'Protéger son identité numérique est essentiel.', 'B1', 'Technologies & Numérique'),
  ('L''usurpation d''identité', 'Utilisation frauduleuse de l''identité d''une autre personne.', 'L''usurpation d''identité peut avoir de graves conséquences.', 'B1', 'Technologies & Numérique'),
  ('La cybersécurité', 'Ensemble des mesures visant à protéger les systèmes informatiques.', 'La cybersécurité est devenue une priorité pour les entreprises.', 'B1', 'Technologies & Numérique'),
  ('Une cyberattaque', 'Attaque informatique visant un système ou un réseau.', 'Cette entreprise a subi une cyberattaque importante.', 'B1', 'Technologies & Numérique'),
  ('Un rançongiciel', 'Logiciel malveillant bloquant l''accès à des données contre une rançon.', 'L''hôpital a été victime d''un rançongiciel.', 'B1', 'Technologies & Numérique'),
  ('La fracture numérique', 'Inégalité d''accès aux outils numériques entre différentes populations.', 'La fracture numérique touche particulièrement les zones rurales.', 'B1', 'Technologies & Numérique'),
  ('L''illectronisme', 'Difficulté à utiliser les outils numériques.', 'L''illectronisme concerne encore une part importante de la population.', 'B1', 'Technologies & Numérique'),
  ('L''inclusion numérique', 'Ensemble des actions visant à réduire les inégalités d''accès au numérique.', 'Des ateliers d''inclusion numérique sont proposés en mairie.', 'B1', 'Technologies & Numérique'),
  ('Un médiateur numérique', 'Personne qui aide les publics en difficulté avec les outils numériques.', 'Le médiateur numérique aide les personnes âgées à utiliser internet.', 'B1', 'Technologies & Numérique'),
  ('Le travail à distance', 'Activité professionnelle exercée hors des locaux de l''entreprise grâce au numérique.', 'Le travail à distance s''est généralisé ces dernières années.', 'B1', 'Technologies & Numérique'),
  ('La dématérialisation bancaire', 'Remplacement des opérations bancaires physiques par des services numériques.', 'La dématérialisation bancaire réduit l''usage du chèque.', 'B1', 'Technologies & Numérique'),
  ('Le paiement mobile', 'Paiement effectué directement depuis un smartphone.', 'Le paiement mobile se développe rapidement en France.', 'B1', 'Technologies & Numérique'),
  ('La monnaie numérique', 'Forme de monnaie qui existe uniquement sous forme électronique.', 'La monnaie numérique attire de plus en plus d''investisseurs.', 'B1', 'Technologies & Numérique'),
  ('La cryptomonnaie', 'Monnaie numérique reposant sur une technologie décentralisée.', 'Le bitcoin est la cryptomonnaie la plus connue.', 'B1', 'Technologies & Numérique'),
  ('La blockchain', 'Technologie de stockage et de transmission d''informations sécurisée et décentralisée.', 'La blockchain sert de base à de nombreuses cryptomonnaies.', 'B1', 'Technologies & Numérique'),
  ('Les données personnelles', 'Informations permettant d''identifier une personne.', 'Les données personnelles sont protégées par la loi.', 'B1', 'Technologies & Numérique'),
  ('La protection des mineurs en ligne', 'Ensemble des mesures visant à protéger les enfants sur internet.', 'La protection des mineurs en ligne fait l''objet de nouvelles lois.', 'B1', 'Technologies & Numérique'),
  ('Le harcèlement en ligne', 'Violence répétée exercée via internet ou les réseaux sociaux.', 'Le harcèlement en ligne touche de nombreux adolescents.', 'B1', 'Technologies & Numérique'),
  ('La modération de contenu', 'Contrôle des publications sur une plateforme numérique.', 'La modération de contenu est un enjeu majeur des réseaux sociaux.', 'B1', 'Technologies & Numérique'),
  ('Un signalement en ligne', 'Action de signaler un contenu inapproprié sur internet.', 'Le signalement en ligne permet de retirer les contenus illégaux.', 'B1', 'Technologies & Numérique'),
  ('Le temps d''écran', 'Durée passée devant un appareil électronique.', 'Il est conseillé de limiter le temps d''écran des enfants.', 'B1', 'Technologies & Numérique'),
  ('L''addiction aux écrans', 'Dépendance excessive aux appareils numériques.', 'L''addiction aux écrans inquiète de nombreux parents.', 'B1', 'Technologies & Numérique'),
  ('La déconnexion numérique', 'Fait de se couper volontairement des outils numériques.', 'La déconnexion numérique aide à réduire le stress.', 'B1', 'Technologies & Numérique'),
  ('Le droit à la déconnexion', 'Droit des salariés à ne pas être sollicités en dehors du travail.', 'Le droit à la déconnexion est inscrit dans le droit du travail français.', 'B1', 'Technologies & Numérique'),
  ('Le secteur du numérique', 'Ensemble des activités économiques liées aux technologies numériques.', 'Le secteur du numérique recrute massivement en France.', 'B1', 'Technologies & Numérique'),
  ('Une start-up', 'Jeune entreprise innovante, souvent liée aux technologies.', 'Cette start-up développe une application de santé.', 'B1', 'Technologies & Numérique'),
  ('Un développeur informatique', 'Personne qui conçoit et programme des logiciels.', 'Elle travaille comme développeuse informatique.', 'B1', 'Technologies & Numérique'),
  ('Le code informatique', 'Ensemble d''instructions écrites pour faire fonctionner un programme.', 'Apprendre le code informatique devient une compétence recherchée.', 'B1', 'Technologies & Numérique'),
  ('Un algorithme', 'Suite d''instructions permettant de résoudre un problème.', 'Cet algorithme trie les résultats de recherche.', 'B1', 'Technologies & Numérique'),
  ('Les objets connectés domestiques', 'Appareils du foyer reliés à internet, comme un thermostat intelligent.', 'Les objets connectés domestiques facilitent la gestion de la maison.', 'B1', 'Technologies & Numérique'),
  ('La maison intelligente', 'Logement équipé de dispositifs connectés automatisés.', 'La maison intelligente permet de contrôler l''éclairage à distance.', 'B1', 'Technologies & Numérique'),
  ('La ville intelligente', 'Ville utilisant les technologies numériques pour améliorer ses services.', 'La ville intelligente optimise la gestion du trafic et de l''énergie.', 'B1', 'Technologies & Numérique'),
  ('La souveraineté numérique', 'Capacité d''un pays à maîtriser ses infrastructures et données numériques.', 'La souveraineté numérique est un enjeu stratégique pour l''Union européenne.', 'B2', 'Technologies & Numérique'),
  ('La régulation des plateformes numériques', 'Ensemble des règles encadrant l''activité des grandes plateformes en ligne.', 'La régulation des plateformes numériques s''est renforcée avec le Digital Services Act.', 'B2', 'Technologies & Numérique'),
  ('Le Digital Services Act', 'Règlement européen encadrant les services numériques et les contenus en ligne.', 'Le Digital Services Act impose de nouvelles obligations aux réseaux sociaux.', 'B2', 'Technologies & Numérique'),
  ('Le Digital Markets Act', 'Règlement européen visant à limiter la position dominante des grandes plateformes.', 'Le Digital Markets Act cible notamment les géants du numérique.', 'B2', 'Technologies & Numérique'),
  ('Les GAFAM', 'Acronyme désignant les grandes entreprises technologiques américaines (Google, Amazon, Facebook, Apple, Microsoft).', 'Les GAFAM dominent une grande partie de l''économie numérique mondiale.', 'B2', 'Technologies & Numérique'),
  ('La position dominante', 'Situation où une entreprise contrôle une large part d''un marché.', 'Certaines plateformes sont accusées d''abuser de leur position dominante.', 'B2', 'Technologies & Numérique'),
  ('La neutralité du net', 'Principe garantissant un traitement égal de toutes les données sur internet.', 'La neutralité du net protège l''égalité d''accès aux contenus en ligne.', 'B2', 'Technologies & Numérique'),
  ('L''apprentissage automatique', 'Technique permettant à une machine d''apprendre à partir de données.', 'L''apprentissage automatique est au cœur de nombreuses innovations technologiques.', 'B2', 'Technologies & Numérique'),
  ('Le biais algorithmique', 'Erreur systématique introduite par les données ou la conception d''un algorithme.', 'Le biais algorithmique peut reproduire des discriminations existantes.', 'B2', 'Technologies & Numérique'),
  ('L''éthique de l''intelligence artificielle', 'Réflexion sur les enjeux moraux liés au développement de l''IA.', 'L''éthique de l''intelligence artificielle interroge la responsabilité des concepteurs.', 'B2', 'Technologies & Numérique'),
  ('La reconnaissance faciale', 'Technologie identifiant une personne à partir de son visage.', 'La reconnaissance faciale soulève des questions de vie privée.', 'B2', 'Technologies & Numérique'),
  ('La surveillance de masse', 'Collecte systématique de données sur une large population.', 'La surveillance de masse est encadrée par la loi dans certains pays.', 'B2', 'Technologies & Numérique'),
  ('Le capitalisme de surveillance', 'Modèle économique fondé sur l''exploitation commerciale des données personnelles.', 'Le capitalisme de surveillance repose sur la collecte massive de données.', 'B2', 'Technologies & Numérique'),
  ('L''économie de l''attention', 'Modèle économique visant à capter le temps et l''attention des utilisateurs.', 'Les réseaux sociaux sont bâtis sur l''économie de l''attention.', 'B2', 'Technologies & Numérique'),
  ('L''addiction numérique', 'Dépendance problématique aux outils et contenus numériques.', 'L''addiction numérique touche particulièrement les jeunes générations.', 'B2', 'Technologies & Numérique'),
  ('La désinformation algorithmique', 'Diffusion de fausses informations amplifiée par les algorithmes de recommandation.', 'La désinformation algorithmique complique la lutte contre les fake news.', 'B2', 'Technologies & Numérique'),
  ('La cyberdépendance', 'Usage excessif et compulsif d''internet ou des jeux vidéo.', 'La cyberdépendance peut nécessiter un accompagnement psychologique.', 'B2', 'Technologies & Numérique'),
  ('La gouvernance de l''internet', 'Ensemble des règles et institutions qui régissent le fonctionnement d''internet.', 'La gouvernance de l''internet implique de nombreux acteurs internationaux.', 'B2', 'Technologies & Numérique'),
  ('La cyberdéfense', 'Ensemble des mesures militaires et stratégiques de protection contre les cyberattaques.', 'La cyberdéfense est devenue une composante essentielle de la sécurité nationale.', 'B2', 'Technologies & Numérique'),
  ('La guerre de l''information', 'Utilisation stratégique de l''information pour influencer un adversaire.', 'La guerre de l''information s''est intensifiée avec les réseaux sociaux.', 'B2', 'Technologies & Numérique'),
  ('L''ingérence numérique', 'Intervention étrangère utilisant les outils numériques pour influencer un pays.', 'L''ingérence numérique dans les élections inquiète de nombreux gouvernements.', 'B2', 'Technologies & Numérique'),
  ('La dépendance technologique', 'Situation où un pays dépend fortement de technologies étrangères.', 'La dépendance technologique aux semi-conducteurs asiatiques inquiète l''Europe.', 'B2', 'Technologies & Numérique'),
  ('La transformation numérique des entreprises', 'Adaptation des entreprises aux nouvelles technologies numériques.', 'La transformation numérique des entreprises s''est accélérée depuis la crise sanitaire.', 'B2', 'Technologies & Numérique'),
  ('L''automatisation des tâches', 'Remplacement du travail humain par des systèmes automatisés.', 'L''automatisation des tâches transforme le marché de l''emploi.', 'B2', 'Technologies & Numérique'),
  ('La robotisation', 'Introduction croissante de robots dans les processus de production.', 'La robotisation touche de plus en plus de secteurs industriels.', 'B2', 'Technologies & Numérique'),
  ('L''obsolescence technologique', 'Perte de valeur ou d''usage d''une technologie remplacée par une plus récente.', 'L''obsolescence technologique pousse à renouveler fréquemment les équipements.', 'B2', 'Technologies & Numérique'),
  ('Le recyclage des déchets électroniques', 'Traitement des appareils électroniques usagés pour en récupérer les matériaux.', 'Le recyclage des déchets électroniques limite la pollution liée au numérique.', 'B2', 'Technologies & Numérique'),
  ('L''empreinte numérique environnementale', 'Impact écologique lié à la production et à l''usage des technologies numériques.', 'L''empreinte numérique environnementale augmente avec le streaming vidéo.', 'B2', 'Technologies & Numérique'),
  ('Le numérique responsable', 'Démarche visant à limiter l''impact environnemental et social des technologies.', 'Le numérique responsable encourage la sobriété technologique.', 'B2', 'Technologies & Numérique'),
  ('La sobriété numérique', 'Réduction volontaire de l''usage des outils numériques pour limiter leur impact.', 'La sobriété numérique est encouragée dans les entreprises soucieuses d''écologie.', 'B2', 'Technologies & Numérique'),
  ('La fracture générationnelle numérique', 'Écart d''usage et de maîtrise des outils numériques entre générations.', 'La fracture générationnelle numérique complique certaines démarches pour les personnes âgées.', 'B2', 'Technologies & Numérique'),
  ('La citoyenneté numérique', 'Ensemble des droits et responsabilités liés à la participation à la vie en ligne.', 'L''éducation à la citoyenneté numérique est intégrée aux programmes scolaires.', 'B2', 'Technologies & Numérique');
