-- Item 6.1 du plan vocabulaire 1500 mots : nouvelle catégorie 'Vie Quotidienne & Consommation'
-- 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Première des 7 nouvelles catégories du plan (au-delà des 5 catégories immigration existantes).
-- Vérifications effectuées avant livraison :
--  - dédup contre les 625 mots déjà en base : aucune collision (1 conflit détecté et corrigé avant livraison)
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('L''argent', 'Monnaie utilisée pour payer.', 'J''ai besoin d''argent pour faire les courses.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un prix', 'Somme à payer pour un produit.', 'Quel est le prix de ce pain ?', 'A1', 'Vie Quotidienne & Consommation'),
  ('Une carte bancaire', 'Carte utilisée pour payer sans argent liquide.', 'Je paie toujours avec ma carte bancaire.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un billet', 'Papier-monnaie de valeur fixe.', 'J''ai payé avec un billet de vingt euros.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Une pièce', 'Petite monnaie en métal.', 'Il me manque une pièce d''un euro.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un sac', 'Objet pour transporter des achats.', 'J''ai oublié mon sac pour les courses.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un ticket de caisse', 'Reçu remis après un achat.', 'Gardez toujours votre ticket de caisse.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Une caisse', 'Endroit où l''on paie dans un magasin.', 'La queue à la caisse était longue.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un panier', 'Petit récipient pour porter ses achats.', 'Prenez un panier à l''entrée du magasin.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un chariot', 'Grand panier à roulettes pour faire les courses.', 'Le chariot est plein de courses.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Le supermarché', 'Grand magasin où l''on achète de la nourriture et d''autres produits.', 'Je vais au supermarché tous les samedis.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Une liste de courses', 'Liste des produits à acheter.', 'J''ai oublié ma liste de courses à la maison.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un vendeur', 'Personne qui vend des produits dans un magasin.', 'Le vendeur m''a bien conseillé.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Une caissière', 'Personne qui encaisse les paiements dans un magasin.', 'La caissière m''a rendu la monnaie.', 'A1', 'Vie Quotidienne & Consommation'),
  ('La monnaie', 'Argent rendu après un paiement.', 'N''oubliez pas votre monnaie.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un reçu', 'Document qui prouve un paiement.', 'Gardez le reçu en cas de problème.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Les soldes', 'Période où les prix sont réduits.', 'J''ai acheté ce manteau pendant les soldes.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Une réduction', 'Diminution du prix d''un produit.', 'J''ai eu une réduction de dix pour cent.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Un abonnement', 'Paiement régulier pour un service.', 'J''ai un abonnement de téléphone à vingt euros par mois.', 'A1', 'Vie Quotidienne & Consommation'),
  ('Le budget', 'Somme d''argent disponible pour dépenser.', 'Il faut respecter son budget chaque mois.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Les dépenses', 'Argent que l''on dépense.', 'Mes dépenses ont augmenté ce mois-ci.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Les économies', 'Argent mis de côté.', 'Elle fait des économies pour ses vacances.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un compte bancaire', 'Compte où l''on garde son argent à la banque.', 'J''ai ouvert un compte bancaire à mon arrivée.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un virement', 'Transfert d''argent d''un compte à un autre.', 'J''ai fait un virement pour payer mon loyer.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un prélèvement automatique', 'Paiement retiré automatiquement d''un compte.', 'Le prélèvement automatique paie mes factures chaque mois.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Une facture', 'Document indiquant le montant à payer pour un service.', 'J''ai reçu la facture d''électricité.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un paiement en plusieurs fois', 'Possibilité de payer un achat en plusieurs versements.', 'J''ai choisi le paiement en trois fois pour cet achat.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le paiement sans contact', 'Méthode de paiement rapide sans code.', 'Le paiement sans contact est limité à 50 euros.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un code secret', 'Suite de chiffres pour valider un paiement par carte.', 'N''oubliez pas votre code secret.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un distributeur automatique', 'Machine qui délivre de l''argent liquide.', 'Je retire de l''argent au distributeur automatique.', 'A2', 'Vie Quotidienne & Consommation'),
  ('La caisse automatique', 'Machine qui permet de payer ses courses soi-même.', 'J''utilise souvent la caisse automatique pour aller plus vite.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un centre commercial', 'Grand ensemble regroupant plusieurs magasins.', 'Le centre commercial ouvre à dix heures.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Une boutique', 'Petit magasin spécialisé.', 'Cette boutique vend des vêtements pour enfants.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un grand magasin', 'Magasin de grande taille avec plusieurs rayons.', 'Les grands magasins sont décorés pour Noël.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le rayon', 'Partie d''un magasin dédiée à un type de produit.', 'Le rayon fruits et légumes est au fond du magasin.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Une étiquette', 'Petit papier indiquant le prix ou les informations d''un produit.', 'Vérifiez toujours l''étiquette avant d''acheter.', 'A2', 'Vie Quotidienne & Consommation'),
  ('La date de péremption', 'Date limite jusqu''à laquelle un produit peut être consommé.', 'Vérifiez la date de péremption avant d''acheter.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un produit bio', 'Produit cultivé sans produits chimiques.', 'Les produits bio sont souvent plus chers.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le commerce équitable', 'Système commercial garantissant un prix juste aux producteurs.', 'Ce café vient du commerce équitable.', 'A2', 'Vie Quotidienne & Consommation'),
  ('La livraison à domicile', 'Service qui apporte les achats chez le client.', 'J''ai commandé avec livraison à domicile.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un achat en ligne', 'Achat réalisé via internet.', 'Les achats en ligne ont beaucoup augmenté.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le panier en ligne', 'Liste des produits sélectionnés sur un site avant l''achat.', 'J''ai ajouté trois articles à mon panier en ligne.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un colis', 'Paquet envoyé par la poste ou un transporteur.', 'J''attends un colis cette semaine.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le retour d''un produit', 'Action de renvoyer un article acheté.', 'Le retour d''un produit est gratuit sous quatorze jours.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le remboursement', 'Argent rendu après le retour d''un achat.', 'J''ai obtenu un remboursement après avoir renvoyé le colis.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Une garantie', 'Engagement du vendeur à réparer ou remplacer un produit défectueux.', 'Cet appareil est sous garantie pendant deux ans.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le service après-vente', 'Service qui aide les clients après un achat.', 'J''ai contacté le service après-vente pour un problème.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Une réclamation', 'Plainte faite auprès d''un vendeur en cas de problème.', 'J''ai fait une réclamation pour un produit cassé.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un consommateur', 'Personne qui achète des biens ou services.', 'Les consommateurs sont de plus en plus attentifs aux prix.', 'A2', 'Vie Quotidienne & Consommation'),
  ('La consommation responsable', 'Fait d''acheter en tenant compte de critères éthiques ou écologiques.', 'La consommation responsable se développe en France.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un produit local', 'Produit fabriqué ou cultivé près de chez soi.', 'Elle préfère acheter des produits locaux.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le marché aux puces', 'Marché où l''on vend des objets d''occasion.', 'On trouve de belles affaires au marché aux puces.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Une occasion', 'Produit déjà utilisé vendu à prix réduit.', 'J''ai acheté ce vélo d''occasion.', 'A2', 'Vie Quotidienne & Consommation'),
  ('La seconde main', 'Achat ou vente d''objets déjà utilisés.', 'La seconde main a beaucoup de succès chez les jeunes.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le troc', 'Échange de biens sans utiliser d''argent.', 'Ils ont fait du troc pour échanger leurs livres.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Un bon d''achat', 'Document permettant d''obtenir une réduction ou un cadeau.', 'J''ai reçu un bon d''achat de vingt euros.', 'A2', 'Vie Quotidienne & Consommation'),
  ('Le pouvoir d''achat', 'Capacité à acheter des biens avec ses revenus.', 'La hausse des prix réduit le pouvoir d''achat.', 'B1', 'Vie Quotidienne & Consommation'),
  ('L''inflation', 'Augmentation générale des prix.', 'L''inflation touche surtout les produits alimentaires.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le taux de TVA', 'Pourcentage de taxe ajouté au prix d''un produit.', 'Le taux de TVA sur les produits alimentaires est réduit.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le crédit à la consommation', 'Emprunt destiné à financer un achat personnel.', 'Il a pris un crédit à la consommation pour sa voiture.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le surendettement', 'Situation où une personne ne peut plus rembourser ses dettes.', 'La commission de surendettement peut aider les familles en difficulté.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Un découvert bancaire', 'Situation où le compte est négatif.', 'J''ai payé des frais à cause d''un découvert bancaire.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Les frais bancaires', 'Sommes prélevées par la banque pour ses services.', 'Les frais bancaires varient selon les banques.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La comparaison de prix', 'Action de comparer les prix avant d''acheter.', 'La comparaison de prix permet de faire des économies.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Un comparateur en ligne', 'Site qui compare les prix de plusieurs vendeurs.', 'J''utilise un comparateur en ligne pour réserver mes billets.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La publicité', 'Message destiné à faire connaître un produit.', 'La publicité influence beaucoup nos choix.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le marketing', 'Ensemble des techniques pour vendre un produit.', 'Le marketing digital cible les réseaux sociaux.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Une marque', 'Nom qui identifie les produits d''une entreprise.', 'Cette marque est connue pour sa qualité.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Un produit de marque distributeur', 'Produit vendu sous le nom du magasin.', 'Les produits de marque distributeur sont souvent moins chers.', 'B1', 'Vie Quotidienne & Consommation'),
  ('L''obsolescence programmée', 'Stratégie qui limite volontairement la durée de vie d''un produit.', 'L''obsolescence programmée est critiquée par les associations de consommateurs.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Une association de consommateurs', 'Organisation qui défend les droits des acheteurs.', 'Cette association de consommateurs publie des tests de produits.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La direction générale de la concurrence', 'Service de l''État qui contrôle les pratiques commerciales.', 'La direction générale de la concurrence sanctionne les pratiques abusives.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La clause abusive', 'Condition contractuelle défavorable et injuste pour le consommateur.', 'Cette clause abusive a été annulée par un tribunal.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le droit de rétractation', 'Droit légal d''annuler un achat sans justification dans un délai fixé.', 'Le droit de rétractation s''applique aux achats réalisés à distance.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La vente à distance', 'Achat réalisé sans présence physique du vendeur et de l''acheteur.', 'La vente à distance est très encadrée par la loi.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le démarchage commercial', 'Sollicitation d''un client par téléphone ou à domicile.', 'Le démarchage commercial est réglementé en France.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Une arnaque', 'Escroquerie destinée à tromper un consommateur.', 'Attention aux arnaques sur internet.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La contrefaçon', 'Copie illégale d''un produit original.', 'La vente de contrefaçons est interdite.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le label de qualité', 'Marque garantissant certaines caractéristiques d''un produit.', 'Ce fromage porte un label de qualité.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La traçabilité', 'Possibilité de suivre l''origine d''un produit.', 'La traçabilité des aliments rassure les consommateurs.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le circuit court', 'Système de vente directe entre producteur et consommateur.', 'Le circuit court réduit les intermédiaires.', 'B1', 'Vie Quotidienne & Consommation'),
  ('L''économie circulaire', 'Modèle économique qui limite le gaspillage des ressources.', 'L''économie circulaire encourage le recyclage et la réparation.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le gaspillage alimentaire', 'Perte de nourriture non consommée.', 'La loi française lutte contre le gaspillage alimentaire.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le suremballage', 'Emballage excessif d''un produit.', 'Le suremballage est critiqué pour son impact écologique.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La consigne', 'Somme remboursée en échange du retour d''un emballage.', 'Certaines bouteilles fonctionnent avec un système de consigne.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le vrac', 'Vente de produits sans emballage individuel.', 'J''achète mes céréales en vrac pour réduire les déchets.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Une AMAP', 'Association qui relie directement producteurs et consommateurs locaux.', 'Nous recevons un panier de légumes chaque semaine grâce à l''AMAP.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La grande distribution', 'Ensemble des grandes surfaces et supermarchés.', 'La grande distribution domine le marché alimentaire français.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le e-commerce', 'Commerce réalisé sur internet.', 'Le e-commerce a fortement progressé ces dernières années.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La fidélisation', 'Stratégie pour inciter un client à revenir.', 'La carte de fidélité fait partie de la stratégie de fidélisation.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Une carte de fidélité', 'Carte offrant des avantages aux clients réguliers.', 'J''accumule des points avec ma carte de fidélité.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le pouvoir de négociation', 'Capacité à obtenir de meilleures conditions dans une transaction.', 'Les grandes entreprises ont un fort pouvoir de négociation.', 'B1', 'Vie Quotidienne & Consommation'),
  ('Le comportement d''achat', 'Habitudes et choix des consommateurs lors d''un achat.', 'Le comportement d''achat évolue avec les nouvelles technologies.', 'B1', 'Vie Quotidienne & Consommation'),
  ('La société de consommation', 'Modèle social fondé sur la consommation de masse.', 'La société de consommation est souvent critiquée pour son impact écologique.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le consumérisme', 'Tendance à privilégier la consommation de biens matériels.', 'Le consumérisme est remis en question par certains mouvements écologistes.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La décroissance', 'Courant prônant la réduction volontaire de la production et de la consommation.', 'La décroissance propose un autre modèle économique.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La sobriété', 'Fait de limiter volontairement sa consommation.', 'La sobriété énergétique est encouragée par les pouvoirs publics.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''empreinte écologique', 'Mesure de l''impact d''une activité humaine sur l''environnement.', 'Réduire sa consommation diminue son empreinte écologique.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le greenwashing', 'Pratique consistant à donner une image écologique trompeuse à un produit.', 'Certaines marques sont accusées de greenwashing.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La transparence des prix', 'Obligation d''afficher clairement le prix réel d''un produit.', 'La transparence des prix protège les consommateurs.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''asymétrie d''information', 'Situation où une partie détient plus d''informations que l''autre dans une transaction.', 'L''asymétrie d''information favorise souvent le vendeur.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le pouvoir de marché', 'Capacité d''une entreprise à influencer les prix du marché.', 'Une entreprise dominante a un fort pouvoir de marché.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''oligopole', 'Marché dominé par un petit nombre d''entreprises.', 'Le secteur des télécommunications fonctionne souvent en oligopole.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La concurrence déloyale', 'Pratique commerciale qui enfreint les règles du marché.', 'L''entreprise a été condamnée pour concurrence déloyale.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La régulation économique', 'Ensemble des règles encadrant l''activité économique.', 'La régulation économique vise à protéger les consommateurs.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''autorité de la concurrence', 'Organisme chargé de contrôler la loyauté du marché.', 'L''autorité de la concurrence a sanctionné une entente sur les prix.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''entente sur les prix', 'Accord illégal entre entreprises pour fixer les prix ensemble.', 'L''entente sur les prix fausse la concurrence.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le dumping', 'Vente de produits à un prix anormalement bas pour éliminer la concurrence.', 'Le dumping est interdit par les règles du commerce international.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La protection du consommateur', 'Ensemble des lois qui défendent les droits des acheteurs.', 'La protection du consommateur s''est renforcée ces dernières années.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le code de la consommation', 'Ensemble des lois françaises régissant les relations commerciales.', 'Le code de la consommation encadre la publicité mensongère.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La publicité mensongère', 'Publicité qui donne de fausses informations sur un produit.', 'La publicité mensongère est sanctionnée par la loi.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La vente forcée', 'Pratique illégale imposant un achat non sollicité.', 'La vente forcée est strictement interdite.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le crédit renouvelable', 'Réserve d''argent utilisable plusieurs fois, avec intérêts.', 'Le crédit renouvelable peut entraîner un endettement rapide.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le taux d''intérêt', 'Pourcentage appliqué à un prêt ou une épargne.', 'Le taux d''intérêt du crédit a augmenté cette année.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le taux d''usure', 'Taux d''intérêt maximal légal pour un crédit.', 'Ce prêt dépasse le taux d''usure autorisé.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''endettement des ménages', 'Niveau global des dettes des foyers.', 'L''endettement des ménages inquiète les économistes.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La consommation collaborative', 'Modèle basé sur le partage ou la location entre particuliers.', 'Les plateformes de consommation collaborative se multiplient.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''économie de la fonctionnalité', 'Modèle qui privilégie l''usage d''un bien plutôt que sa possession.', 'L''économie de la fonctionnalité propose de louer plutôt que d''acheter.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La désintermédiation', 'Suppression des intermédiaires dans une transaction commerciale.', 'La désintermédiation profite parfois directement au consommateur.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''e-réputation', 'Image d''une marque ou d''un produit sur internet.', 'Les avis en ligne influencent fortement l''e-réputation d''une entreprise.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Les avis en ligne', 'Commentaires laissés par les clients sur un produit ou service.', 'Je consulte toujours les avis en ligne avant d''acheter.', 'B2', 'Vie Quotidienne & Consommation'),
  ('L''algorithme de recommandation', 'Système qui suggère des produits selon les préférences d''un utilisateur.', 'L''algorithme de recommandation influence nos choix d''achat.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le profilage commercial', 'Analyse des habitudes d''un client pour cibler des offres.', 'Le profilage commercial soulève des questions de vie privée.', 'B2', 'Vie Quotidienne & Consommation'),
  ('La protection des données personnelles', 'Ensemble des règles encadrant l''usage des informations privées.', 'La protection des données personnelles est renforcée par le RGPD.', 'B2', 'Vie Quotidienne & Consommation'),
  ('Le RGPD', 'Règlement européen sur la protection des données personnelles.', 'Le RGPD impose des règles strictes aux entreprises.', 'B2', 'Vie Quotidienne & Consommation');
