-- Item 6.3 du plan vocabulaire 1500 mots : nouvelle catégorie 'Transport & Mobilité'
-- 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 875 mots déjà en base : aucune collision
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('Le bus', 'Véhicule de transport en commun.', 'Je prends le bus pour aller au travail.', 'A1', 'Transport & Mobilité'),
  ('Le métro', 'Transport en commun souterrain.', 'Le métro est rapide pour se déplacer en ville.', 'A1', 'Transport & Mobilité'),
  ('Le train', 'Transport ferroviaire pour les longs trajets.', 'Le train part à huit heures.', 'A1', 'Transport & Mobilité'),
  ('La voiture', 'Véhicule individuel à quatre roues.', 'Nous avons pris la voiture pour partir en vacances.', 'A1', 'Transport & Mobilité'),
  ('Le vélo', 'Véhicule à deux roues actionné par les pédales.', 'Il va au travail en vélo.', 'A1', 'Transport & Mobilité'),
  ('La marche à pied', 'Déplacement en marchant.', 'Je préfère la marche à pied pour les courts trajets.', 'A1', 'Transport & Mobilité'),
  ('Un arrêt de bus', 'Endroit où le bus s''arrête pour prendre des passagers.', 'L''arrêt de bus est juste devant chez moi.', 'A1', 'Transport & Mobilité'),
  ('Une gare', 'Lieu de départ et d''arrivée des trains.', 'Rendez-vous à la gare à midi.', 'A1', 'Transport & Mobilité'),
  ('Une station de métro', 'Lieu d''arrêt du métro.', 'La station de métro est fermée pour travaux.', 'A1', 'Transport & Mobilité'),
  ('Un billet de train', 'Titre de transport pour prendre le train.', 'J''ai acheté mon billet de train en ligne.', 'A1', 'Transport & Mobilité'),
  ('Un ticket de bus', 'Titre de transport pour prendre le bus.', 'N''oubliez pas de valider votre ticket de bus.', 'A1', 'Transport & Mobilité'),
  ('Un taxi', 'Voiture avec chauffeur que l''on paie pour un trajet.', 'Nous avons pris un taxi pour aller à l''aéroport.', 'A1', 'Transport & Mobilité'),
  ('Un aéroport', 'Lieu de départ et d''arrivée des avions.', 'L''aéroport est à trente minutes du centre-ville.', 'A1', 'Transport & Mobilité'),
  ('Un avion', 'Moyen de transport aérien.', 'Nous prenons l''avion pour aller en vacances.', 'A1', 'Transport & Mobilité'),
  ('Une route', 'Voie destinée à la circulation des véhicules.', 'La route est fermée à cause des travaux.', 'A1', 'Transport & Mobilité'),
  ('Un feu rouge', 'Signal lumineux qui arrête la circulation.', 'Arrêtez-vous au feu rouge.', 'A1', 'Transport & Mobilité'),
  ('Un passage piéton', 'Zone réservée à la traversée des piétons.', 'Traversez toujours sur le passage piéton.', 'A1', 'Transport & Mobilité'),
  ('Un piéton', 'Personne qui se déplace à pied.', 'Les piétons doivent respecter les feux.', 'A1', 'Transport & Mobilité'),
  ('Le trajet', 'Distance parcourue pour aller d''un endroit à un autre.', 'Le trajet dure environ trente minutes.', 'A1', 'Transport & Mobilité'),
  ('Un abonnement de transport', 'Formule qui permet d''utiliser les transports en commun régulièrement.', 'J''ai un abonnement de transport mensuel.', 'A2', 'Transport & Mobilité'),
  ('La carte de transport', 'Carte permettant de payer ou d''accéder aux transports en commun.', 'Rechargez votre carte de transport avant de partir.', 'A2', 'Transport & Mobilité'),
  ('Le tramway', 'Transport en commun circulant sur des rails en surface.', 'Le tramway dessert tout le centre-ville.', 'A2', 'Transport & Mobilité'),
  ('Le RER', 'Réseau ferré rapide desservant Paris et sa banlieue.', 'Je prends le RER pour aller à l''aéroport.', 'A2', 'Transport & Mobilité'),
  ('Le TGV', 'Train à grande vitesse.', 'Le TGV relie Paris à Marseille en trois heures.', 'A2', 'Transport & Mobilité'),
  ('Un horaire de train', 'Programme des heures de départ et d''arrivée des trains.', 'Consultez l''horaire de train avant de partir.', 'A2', 'Transport & Mobilité'),
  ('Un quai', 'Endroit d''où l''on monte dans un train.', 'Le train part du quai numéro trois.', 'A2', 'Transport & Mobilité'),
  ('Une correspondance', 'Changement de moyen de transport pendant un trajet.', 'J''ai une correspondance à Lyon.', 'A2', 'Transport & Mobilité'),
  ('Un retard', 'Décalage par rapport à l''horaire prévu.', 'Le train a du retard à cause d''un incident.', 'A2', 'Transport & Mobilité'),
  ('Une annulation', 'Suppression d''un trajet prévu.', 'L''annulation du vol a retardé notre voyage.', 'A2', 'Transport & Mobilité'),
  ('Le permis de conduire', 'Document autorisant à conduire un véhicule.', 'J''ai passé mon permis de conduire l''année dernière.', 'A2', 'Transport & Mobilité'),
  ('Une auto-école', 'Établissement où l''on apprend à conduire.', 'Elle prend des cours dans une auto-école.', 'A2', 'Transport & Mobilité'),
  ('Le code de la route', 'Ensemble des règles de circulation.', 'Il faut connaître le code de la route pour passer l''examen.', 'A2', 'Transport & Mobilité'),
  ('Une station-service', 'Lieu où l''on achète du carburant.', 'Nous nous sommes arrêtés à une station-service.', 'A2', 'Transport & Mobilité'),
  ('Le carburant', 'Substance utilisée pour faire fonctionner un véhicule.', 'Le prix du carburant a augmenté.', 'A2', 'Transport & Mobilité'),
  ('Un parking', 'Lieu réservé au stationnement des véhicules.', 'Le parking de la gare est payant.', 'A2', 'Transport & Mobilité'),
  ('Le stationnement', 'Action de garer un véhicule.', 'Le stationnement est interdit ici.', 'A2', 'Transport & Mobilité'),
  ('Une amende de stationnement', 'Sanction financière pour un stationnement non autorisé.', 'J''ai eu une amende de stationnement hier.', 'A2', 'Transport & Mobilité'),
  ('Un embouteillage', 'Encombrement de la circulation.', 'Il y a un embouteillage sur l''autoroute.', 'A2', 'Transport & Mobilité'),
  ('L''autoroute', 'Route rapide à plusieurs voies.', 'Nous avons pris l''autoroute pour aller plus vite.', 'A2', 'Transport & Mobilité'),
  ('Le péage', 'Somme à payer pour emprunter certaines routes.', 'Le péage coûte quinze euros sur cette autoroute.', 'A2', 'Transport & Mobilité'),
  ('Un vélo en libre-service', 'Système de vélos partagés disponibles en ville.', 'J''utilise souvent le vélo en libre-service pour aller au travail.', 'A2', 'Transport & Mobilité'),
  ('La trottinette électrique', 'Petit véhicule électrique à deux roues.', 'La trottinette électrique est populaire dans les grandes villes.', 'A2', 'Transport & Mobilité'),
  ('Le covoiturage', 'Partage d''un trajet en voiture entre plusieurs personnes.', 'Nous faisons du covoiturage pour réduire les frais.', 'A2', 'Transport & Mobilité'),
  ('L''autopartage', 'Système de location de voitures en libre-service.', 'L''autopartage permet d''utiliser une voiture sans en posséder une.', 'A2', 'Transport & Mobilité'),
  ('Une compagnie aérienne', 'Entreprise qui organise des vols.', 'Cette compagnie aérienne propose des vols directs.', 'A2', 'Transport & Mobilité'),
  ('Un vol direct', 'Trajet en avion sans escale.', 'Nous avons trouvé un vol direct pour cette destination.', 'A2', 'Transport & Mobilité'),
  ('Une escale', 'Arrêt intermédiaire lors d''un voyage.', 'Notre vol a une escale de deux heures.', 'A2', 'Transport & Mobilité'),
  ('Les bagages', 'Ensemble des affaires transportées en voyage.', 'N''oubliez pas d''enregistrer vos bagages.', 'A2', 'Transport & Mobilité'),
  ('L''embarquement', 'Action de monter à bord d''un avion ou d''un bateau.', 'L''embarquement commence dans trente minutes.', 'A2', 'Transport & Mobilité'),
  ('Une carte d''embarquement', 'Document nécessaire pour monter à bord d''un avion.', 'Présentez votre carte d''embarquement au contrôle.', 'A2', 'Transport & Mobilité'),
  ('Le contrôle de sécurité', 'Vérification effectuée avant l''accès à un avion.', 'Le contrôle de sécurité peut prendre du temps.', 'A2', 'Transport & Mobilité'),
  ('La ceinture de sécurité', 'Dispositif qui maintient les passagers en cas de choc.', 'Attachez votre ceinture de sécurité avant de démarrer.', 'A2', 'Transport & Mobilité'),
  ('Un casque', 'Équipement de protection pour la tête.', 'Portez toujours un casque à vélo.', 'A2', 'Transport & Mobilité'),
  ('La circulation', 'Ensemble des déplacements de véhicules sur les routes.', 'La circulation est dense aux heures de pointe.', 'A2', 'Transport & Mobilité'),
  ('Les heures de pointe', 'Périodes de forte affluence dans les transports.', 'Évitez de voyager aux heures de pointe.', 'A2', 'Transport & Mobilité'),
  ('Un itinéraire', 'Chemin prévu pour se rendre d''un lieu à un autre.', 'L''application propose plusieurs itinéraires.', 'A2', 'Transport & Mobilité'),
  ('La mobilité durable', 'Ensemble des moyens de transport respectueux de l''environnement.', 'La mobilité durable est encouragée dans les grandes villes.', 'B1', 'Transport & Mobilité'),
  ('La transition écologique des transports', 'Passage progressif vers des modes de transport moins polluants.', 'La transition écologique des transports concerne aussi les entreprises.', 'B1', 'Transport & Mobilité'),
  ('Le véhicule électrique', 'Voiture fonctionnant grâce à une batterie électrique.', 'Les véhicules électriques se multiplient sur les routes françaises.', 'B1', 'Transport & Mobilité'),
  ('La borne de recharge', 'Équipement permettant de recharger un véhicule électrique.', 'Il a trouvé une borne de recharge près de chez lui.', 'B1', 'Transport & Mobilité'),
  ('L''autonomie d''un véhicule', 'Distance qu''un véhicule peut parcourir sans recharge ni ravitaillement.', 'L''autonomie de cette voiture électrique est de 400 kilomètres.', 'B1', 'Transport & Mobilité'),
  ('Les zones à faibles émissions', 'Zones urbaines limitant l''accès aux véhicules polluants.', 'Certaines villes ont instauré des zones à faibles émissions.', 'B1', 'Transport & Mobilité'),
  ('La vignette Crit''Air', 'Autocollant classant les véhicules selon leur niveau de pollution.', 'Il faut afficher la vignette Crit''Air pour circuler dans certaines zones.', 'B1', 'Transport & Mobilité'),
  ('La piste cyclable', 'Voie réservée aux vélos.', 'La ville a créé de nouvelles pistes cyclables.', 'B1', 'Transport & Mobilité'),
  ('Le plan de circulation', 'Organisation officielle des voies de circulation d''une ville.', 'Le plan de circulation a changé dans le centre-ville.', 'B1', 'Transport & Mobilité'),
  ('La sécurité routière', 'Ensemble des mesures visant à réduire les accidents de la route.', 'La sécurité routière fait l''objet de campagnes régulières.', 'B1', 'Transport & Mobilité'),
  ('Un accident de la route', 'Collision impliquant un ou plusieurs véhicules.', 'Un accident de la route a bloqué l''autoroute ce matin.', 'B1', 'Transport & Mobilité'),
  ('Le retrait de points', 'Sanction consistant à retirer des points du permis de conduire.', 'Un excès de vitesse entraîne un retrait de points.', 'B1', 'Transport & Mobilité'),
  ('Le permis à points', 'Système attribuant un capital de points au permis de conduire.', 'Le permis à points existe en France depuis 1992.', 'B1', 'Transport & Mobilité'),
  ('L''alcootest', 'Appareil qui mesure le taux d''alcool dans le sang.', 'Les gendarmes ont fait passer un alcootest aux automobilistes.', 'B1', 'Transport & Mobilité'),
  ('La conduite accompagnée', 'Formation permettant d''apprendre à conduire avant l''âge légal, avec un accompagnateur.', 'Il a appris à conduire en conduite accompagnée.', 'B1', 'Transport & Mobilité'),
  ('Le contrôle technique', 'Vérification obligatoire de l''état d''un véhicule.', 'La voiture doit passer le contrôle technique cette année.', 'B1', 'Transport & Mobilité'),
  ('L''assurance auto', 'Contrat couvrant les risques liés à un véhicule.', 'L''assurance auto est obligatoire en France.', 'B1', 'Transport & Mobilité'),
  ('La franchise', 'Somme restant à la charge de l''assuré en cas de sinistre.', 'La franchise de l''assurance est de trois cents euros.', 'B1', 'Transport & Mobilité'),
  ('Un constat amiable', 'Document rempli par les conducteurs après un accident.', 'Ils ont rempli un constat amiable après la collision.', 'B1', 'Transport & Mobilité'),
  ('Le transport ferroviaire', 'Ensemble des déplacements réalisés par train.', 'Le transport ferroviaire est privilégié pour les longs trajets.', 'B1', 'Transport & Mobilité'),
  ('La SNCF', 'Société nationale des chemins de fer français.', 'La SNCF gère la majorité du réseau ferroviaire français.', 'B1', 'Transport & Mobilité'),
  ('La grève des transports', 'Arrêt de travail des employés des transports en commun.', 'La grève des transports a perturbé la circulation des trains.', 'B1', 'Transport & Mobilité'),
  ('Le service minimum', 'Niveau de service maintenu pendant une grève.', 'Un service minimum est garanti pendant les grèves de transport.', 'B1', 'Transport & Mobilité'),
  ('Le réseau de transport', 'Ensemble des lignes et infrastructures de transport d''une région.', 'Le réseau de transport parisien est l''un des plus denses d''Europe.', 'B1', 'Transport & Mobilité'),
  ('L''accessibilité des transports', 'Capacité des transports à être utilisés par tous, y compris les personnes handicapées.', 'L''accessibilité des transports s''améliore progressivement.', 'B1', 'Transport & Mobilité'),
  ('Une personne à mobilité réduite', 'Personne ayant des difficultés à se déplacer.', 'Cette station est équipée pour les personnes à mobilité réduite.', 'B1', 'Transport & Mobilité'),
  ('Le transport scolaire', 'Service de transport destiné aux élèves.', 'Le transport scolaire est gratuit dans cette commune.', 'B1', 'Transport & Mobilité'),
  ('Le fret', 'Transport de marchandises.', 'Le fret ferroviaire est en développement en France.', 'B1', 'Transport & Mobilité'),
  ('La logistique', 'Organisation du transport et de la distribution des marchandises.', 'La logistique est essentielle pour le commerce en ligne.', 'B1', 'Transport & Mobilité'),
  ('Un chauffeur-livreur', 'Personne qui conduit un véhicule pour livrer des marchandises.', 'Le chauffeur-livreur a déposé le colis ce matin.', 'B1', 'Transport & Mobilité'),
  ('Le transport routier', 'Ensemble des déplacements de marchandises par la route.', 'Le transport routier représente une grande part des émissions de CO2.', 'B1', 'Transport & Mobilité'),
  ('Les émissions de CO2', 'Rejets de dioxyde de carbone liés aux transports.', 'Réduire les émissions de CO2 est un objectif prioritaire.', 'B1', 'Transport & Mobilité'),
  ('L''empreinte carbone des transports', 'Impact des transports sur le climat, mesuré en émissions de gaz à effet de serre.', 'L''avion a une empreinte carbone des transports plus élevée que le train.', 'B1', 'Transport & Mobilité'),
  ('Le développement des infrastructures', 'Construction et amélioration des équipements de transport.', 'Le développement des infrastructures ferroviaires est une priorité nationale.', 'B1', 'Transport & Mobilité'),
  ('Une ligne à grande vitesse', 'Voie ferrée conçue pour les trains rapides.', 'Une nouvelle ligne à grande vitesse relie ces deux villes.', 'B1', 'Transport & Mobilité'),
  ('La mobilité inter-régionale', 'Déplacements entre différentes régions d''un pays.', 'La mobilité inter-régionale dépend beaucoup du réseau ferroviaire.', 'B1', 'Transport & Mobilité'),
  ('Un titre de transport dématérialisé', 'Billet de transport disponible sous forme numérique.', 'Le titre de transport dématérialisé remplace peu à peu le billet papier.', 'B1', 'Transport & Mobilité'),
  ('La planification urbaine des transports', 'Organisation à long terme des infrastructures de transport d''une ville.', 'La planification urbaine des transports intègre désormais les mobilités douces.', 'B2', 'Transport & Mobilité'),
  ('L''intermodalité', 'Capacité à combiner plusieurs modes de transport pour un même trajet.', 'L''intermodalité facilite les déplacements entre le train et le vélo.', 'B2', 'Transport & Mobilité'),
  ('La multimodalité', 'Coexistence de plusieurs modes de transport pour se déplacer.', 'La multimodalité est encouragée dans les grandes agglomérations.', 'B2', 'Transport & Mobilité'),
  ('La congestion urbaine', 'Saturation de la circulation dans les villes.', 'La congestion urbaine coûte cher à l''économie.', 'B2', 'Transport & Mobilité'),
  ('L''étalement urbain', 'Extension progressive des villes vers leur périphérie.', 'L''étalement urbain augmente la dépendance à la voiture.', 'B2', 'Transport & Mobilité'),
  ('La politique des transports', 'Ensemble des décisions publiques encadrant les transports.', 'La politique des transports vise à réduire la pollution.', 'B2', 'Transport & Mobilité'),
  ('La régulation du trafic', 'Gestion et contrôle de la circulation.', 'La régulation du trafic utilise désormais des capteurs intelligents.', 'B2', 'Transport & Mobilité'),
  ('Le péage urbain', 'Redevance imposée aux véhicules circulant dans certaines zones urbaines.', 'Certaines capitales européennes ont instauré un péage urbain.', 'B2', 'Transport & Mobilité'),
  ('La décarbonation des transports', 'Réduction des émissions de carbone liées aux déplacements.', 'La décarbonation des transports est un enjeu majeur du changement climatique.', 'B2', 'Transport & Mobilité'),
  ('La transition énergétique', 'Passage vers des sources d''énergie moins polluantes, y compris dans les transports.', 'La transition énergétique transforme le secteur automobile.', 'B2', 'Transport & Mobilité'),
  ('Le véhicule autonome', 'Voiture capable de se conduire sans intervention humaine.', 'Les véhicules autonomes sont encore en phase d''expérimentation.', 'B2', 'Transport & Mobilité'),
  ('La mobilité partagée', 'Modèle de déplacement basé sur le partage de véhicules.', 'La mobilité partagée se développe dans les zones urbaines denses.', 'B2', 'Transport & Mobilité'),
  ('La gouvernance des mobilités', 'Organisation institutionnelle de la gestion des transports.', 'La gouvernance des mobilités implique plusieurs niveaux de collectivités.', 'B2', 'Transport & Mobilité'),
  ('L''aménagement du territoire', 'Organisation de l''espace, incluant les infrastructures de transport.', 'L''aménagement du territoire influence fortement l''offre de transport.', 'B2', 'Transport & Mobilité'),
  ('Le désenclavement rural', 'Amélioration de l''accès aux zones rurales isolées.', 'Le désenclavement rural passe par de nouvelles lignes de bus.', 'B2', 'Transport & Mobilité'),
  ('La fracture territoriale', 'Inégalité d''accès aux services entre différentes zones géographiques.', 'La fracture territoriale se traduit par un manque de transports en zone rurale.', 'B2', 'Transport & Mobilité'),
  ('L''inégalité d''accès à la mobilité', 'Différence de possibilités de déplacement selon les personnes ou les territoires.', 'L''inégalité d''accès à la mobilité pénalise les zones peu desservies.', 'B2', 'Transport & Mobilité'),
  ('La précarité énergétique liée aux déplacements', 'Difficulté financière causée par la dépendance à la voiture.', 'La précarité énergétique liée aux déplacements touche les ménages modestes.', 'B2', 'Transport & Mobilité'),
  ('L''externalité négative', 'Coût indirect supporté par la société, comme la pollution des transports.', 'La pollution routière est une externalité négative importante.', 'B2', 'Transport & Mobilité'),
  ('La taxation carbone', 'Impôt appliqué en fonction des émissions de carbone.', 'La taxation carbone pourrait s''appliquer davantage au secteur aérien.', 'B2', 'Transport & Mobilité'),
  ('Le transport aérien low-cost', 'Vols proposés à bas prix par certaines compagnies.', 'Le transport aérien low-cost a démocratisé les voyages en avion.', 'B2', 'Transport & Mobilité'),
  ('La régulation aérienne', 'Ensemble des règles encadrant le trafic aérien.', 'La régulation aérienne garantit la sécurité des vols.', 'B2', 'Transport & Mobilité'),
  ('L''espace Schengen', 'Zone européenne permettant la libre circulation sans contrôle aux frontières internes.', 'La France fait partie de l''espace Schengen.', 'B2', 'Transport & Mobilité'),
  ('Le transport transfrontalier', 'Déplacement entre deux pays voisins.', 'Le transport transfrontalier facilite les échanges économiques.', 'B2', 'Transport & Mobilité'),
  ('La libre circulation des personnes', 'Principe permettant de se déplacer librement au sein de l''Union européenne.', 'La libre circulation des personnes est un pilier de l''Union européenne.', 'B2', 'Transport & Mobilité'),
  ('L''harmonisation des normes de transport', 'Alignement des règles de transport entre plusieurs pays.', 'L''harmonisation des normes de transport facilite le commerce européen.', 'B2', 'Transport & Mobilité'),
  ('La résilience des infrastructures', 'Capacité des réseaux de transport à résister aux crises.', 'La résilience des infrastructures est testée lors des catastrophes naturelles.', 'B2', 'Transport & Mobilité'),
  ('La saturation du réseau ferroviaire', 'Situation où le réseau ferré ne peut plus absorber le trafic.', 'La saturation du réseau ferroviaire complique les extensions de lignes.', 'B2', 'Transport & Mobilité'),
  ('Le report modal', 'Transfert du trafic d''un mode de transport vers un autre plus durable.', 'Le report modal vers le train est encouragé par les pouvoirs publics.', 'B2', 'Transport & Mobilité'),
  ('L''investissement dans les transports publics', 'Financement destiné à développer les réseaux de transport collectif.', 'L''investissement dans les transports publics a augmenté ces dernières années.', 'B2', 'Transport & Mobilité'),
  ('La privatisation des transports', 'Transfert de la gestion des transports du public vers le privé.', 'La privatisation des transports reste un sujet de débat politique.', 'B2', 'Transport & Mobilité'),
  ('Le service public de transport', 'Offre de transport assurée ou garantie par l''État ou les collectivités.', 'Le service public de transport doit garantir un accès équitable à tous.', 'B2', 'Transport & Mobilité');
