-- Item 6.4 du plan vocabulaire 1500 mots : nouvelle catégorie 'Éducation & Formation'
-- 0 -> 125 mots, répartis A1:19 A2:37 B1:37 B2:32.
-- Vérifications effectuées avant livraison :
--  - dédup contre les 1000 mots déjà en base : 2 collisions détectées (Un apprentissage, Un stage,
--    déjà utilisés en A2 pour la catégorie Travail) et corrigées avant livraison
--  - dédup interne au lot (aucun doublon)
--  - protégé par la contrainte vocabulary_word_level_unique (migration 20260821000001)
-- audio_url volontairement NULL : pipeline TTS Gemini locale, à lancer par Olivier selon son quota.

INSERT INTO public.vocabulary (word, definition, example, level, category) VALUES
  ('L''école', 'Lieu où les enfants apprennent.', 'Mon fils va à l''école tous les matins.', 'A1', 'Éducation & Formation'),
  ('Un élève', 'Personne qui apprend à l''école.', 'Les élèves écoutent la maîtresse.', 'A1', 'Éducation & Formation'),
  ('Un professeur', 'Personne qui enseigne.', 'Le professeur explique la leçon.', 'A1', 'Éducation & Formation'),
  ('Une classe', 'Groupe d''élèves qui étudient ensemble.', 'Ma fille est dans la classe de CP.', 'A1', 'Éducation & Formation'),
  ('Un cahier', 'Carnet où l''on écrit ses cours.', 'N''oublie pas ton cahier de français.', 'A1', 'Éducation & Formation'),
  ('Un livre', 'Objet contenant un texte à lire.', 'Il lit un livre chaque soir.', 'A1', 'Éducation & Formation'),
  ('Un stylo', 'Objet pour écrire.', 'J''ai perdu mon stylo bleu.', 'A1', 'Éducation & Formation'),
  ('Un crayon', 'Objet en bois pour écrire ou dessiner.', 'L''enfant dessine avec un crayon.', 'A1', 'Éducation & Formation'),
  ('Un devoir', 'Travail scolaire à faire à la maison.', 'Les devoirs sont pour demain.', 'A1', 'Éducation & Formation'),
  ('Une leçon', 'Contenu enseigné pendant un cours.', 'La leçon de maths était difficile.', 'A1', 'Éducation & Formation'),
  ('Un examen', 'Épreuve pour évaluer les connaissances.', 'L''examen a lieu la semaine prochaine.', 'A1', 'Éducation & Formation'),
  ('Une note', 'Évaluation chiffrée d''un travail scolaire.', 'J''ai eu une bonne note en français.', 'A1', 'Éducation & Formation'),
  ('La récréation', 'Moment de pause entre les cours.', 'Les enfants jouent pendant la récréation.', 'A1', 'Éducation & Formation'),
  ('Le tableau', 'Surface où le professeur écrit.', 'Le professeur écrit au tableau.', 'A1', 'Éducation & Formation'),
  ('Un cartable', 'Sac pour transporter ses affaires scolaires.', 'Range tes livres dans ton cartable.', 'A1', 'Éducation & Formation'),
  ('Une inscription', 'Démarche pour s''inscrire à une école.', 'L''inscription à l''école se fait en mairie.', 'A1', 'Éducation & Formation'),
  ('Un diplôme', 'Document qui atteste la réussite d''une formation.', 'Elle a obtenu son diplôme l''année dernière.', 'A1', 'Éducation & Formation'),
  ('Étudier', 'Apprendre une matière en profondeur.', 'Il étudie chaque soir après l''école.', 'A1', 'Éducation & Formation'),
  ('Apprendre', 'Acquérir de nouvelles connaissances.', 'J''apprends le français depuis six mois.', 'A1', 'Éducation & Formation'),
  ('Le collège', 'Établissement scolaire après l''école primaire.', 'Mon fils entre au collège en septembre.', 'A2', 'Éducation & Formation'),
  ('Le lycée', 'Établissement scolaire après le collège.', 'Elle est au lycée en classe de première.', 'A2', 'Éducation & Formation'),
  ('L''université', 'Établissement d''enseignement supérieur.', 'Il étudie à l''université de Toulouse.', 'A2', 'Éducation & Formation'),
  ('Un emploi du temps', 'Répartition des cours dans la semaine.', 'Mon emploi du temps change chaque trimestre.', 'A2', 'Éducation & Formation'),
  ('Une matière scolaire', 'Discipline enseignée à l''école.', 'Les mathématiques sont ma matière préférée.', 'A2', 'Éducation & Formation'),
  ('Le directeur d''école', 'Personne responsable d''une école.', 'Le directeur d''école a organisé une réunion.', 'A2', 'Éducation & Formation'),
  ('Le proviseur', 'Personne responsable d''un lycée.', 'Le proviseur a annoncé les résultats du bac.', 'A2', 'Éducation & Formation'),
  ('La cantine scolaire', 'Restaurant collectif d''un établissement scolaire.', 'Mon fils mange à la cantine scolaire le midi.', 'A2', 'Éducation & Formation'),
  ('La rentrée scolaire', 'Reprise des cours après les vacances.', 'La rentrée scolaire a lieu début septembre.', 'A2', 'Éducation & Formation'),
  ('Les vacances scolaires', 'Périodes de congé pendant l''année scolaire.', 'Les vacances scolaires durent deux semaines.', 'A2', 'Éducation & Formation'),
  ('Un bulletin scolaire', 'Document présentant les notes et appréciations d''un élève.', 'J''ai reçu le bulletin scolaire de ma fille.', 'A2', 'Éducation & Formation'),
  ('Une appréciation', 'Commentaire du professeur sur le travail d''un élève.', 'L''appréciation était très positive ce trimestre.', 'A2', 'Éducation & Formation'),
  ('Le redoublement', 'Fait de refaire une année scolaire.', 'Le redoublement est de moins en moins fréquent.', 'A2', 'Éducation & Formation'),
  ('Un cours particulier', 'Cours donné individuellement à un élève.', 'Il prend des cours particuliers de mathématiques.', 'A2', 'Éducation & Formation'),
  ('Le soutien scolaire', 'Aide apportée à un élève en difficulté.', 'Elle bénéficie d''un soutien scolaire en français.', 'A2', 'Éducation & Formation'),
  ('Un contrôle', 'Évaluation courte sur une partie du programme.', 'Nous avons un contrôle de grammaire vendredi.', 'A2', 'Éducation & Formation'),
  ('Le programme scolaire', 'Ensemble des connaissances à enseigner sur une année.', 'Le programme scolaire a changé cette année.', 'A2', 'Éducation & Formation'),
  ('Un diplôme national', 'Diplôme délivré et reconnu par l''État.', 'Le baccalauréat est un diplôme national.', 'A2', 'Éducation & Formation'),
  ('Le baccalauréat', 'Diplôme obtenu à la fin du lycée.', 'Elle a réussi son baccalauréat avec mention.', 'A2', 'Éducation & Formation'),
  ('Une filière', 'Parcours d''études spécialisé.', 'Il a choisi une filière scientifique.', 'A2', 'Éducation & Formation'),
  ('Une orientation scolaire', 'Choix du parcours éducatif d''un élève.', 'L''orientation scolaire se décide en fin de troisième.', 'A2', 'Éducation & Formation'),
  ('Un conseiller d''orientation', 'Professionnel qui aide à choisir un parcours d''études.', 'J''ai rencontré le conseiller d''orientation pour mon fils.', 'A2', 'Éducation & Formation'),
  ('Une formation professionnelle', 'Ensemble de cours visant à acquérir un métier.', 'Il suit une formation professionnelle en plomberie.', 'A2', 'Éducation & Formation'),
  ('L''alternance', 'Formation combinant cours à l''école et travail en entreprise.', 'Elle fait sa formation en alternance chez un boulanger.', 'A2', 'Éducation & Formation'),
  ('Un stage d''observation', 'Courte période passée en entreprise pour découvrir un métier.', 'Il a fait un stage d''observation dans une entreprise informatique.', 'A2', 'Éducation & Formation'),
  ('Un maître de stage', 'Personne qui encadre un stagiaire en entreprise.', 'Mon maître de stage m''a beaucoup appris.', 'A2', 'Éducation & Formation'),
  ('Une bourse d''études', 'Aide financière accordée à un étudiant.', 'Elle a obtenu une bourse d''études pour ses études.', 'A2', 'Éducation & Formation'),
  ('Les frais de scolarité', 'Somme à payer pour être inscrit dans un établissement.', 'Les frais de scolarité varient selon les universités.', 'A2', 'Éducation & Formation'),
  ('Un amphithéâtre', 'Grande salle de cours à l''université.', 'Le cours a lieu dans un grand amphithéâtre.', 'A2', 'Éducation & Formation'),
  ('Un campus', 'Ensemble des bâtiments d''une université.', 'Le campus est très animé le midi.', 'A2', 'Éducation & Formation'),
  ('Une bibliothèque universitaire', 'Bibliothèque réservée aux étudiants d''une université.', 'J''étudie souvent à la bibliothèque universitaire.', 'A2', 'Éducation & Formation'),
  ('Un mémoire', 'Travail écrit réalisé à la fin d''un cursus universitaire.', 'Elle rédige son mémoire de master.', 'A2', 'Éducation & Formation'),
  ('Une thèse', 'Travail de recherche approfondi pour un doctorat.', 'Il prépare sa thèse depuis trois ans.', 'A2', 'Éducation & Formation'),
  ('Un cursus', 'Ensemble des études suivies par une personne.', 'Son cursus universitaire a duré cinq ans.', 'A2', 'Éducation & Formation'),
  ('L''apprentissage à distance', 'Formation suivie sans présence physique.', 'L''apprentissage à distance s''est développé récemment.', 'A2', 'Éducation & Formation'),
  ('Un cours en ligne', 'Formation dispensée via internet.', 'J''ai suivi un cours en ligne de comptabilité.', 'A2', 'Éducation & Formation'),
  ('L''illettrisme', 'Difficulté à lire et écrire malgré une scolarisation.', 'La lutte contre l''illettrisme est une priorité nationale.', 'A2', 'Éducation & Formation'),
  ('L''enseignement supérieur', 'Ensemble des études après le baccalauréat.', 'L''enseignement supérieur regroupe les universités et les grandes écoles.', 'B1', 'Éducation & Formation'),
  ('Une grande école', 'Établissement d''enseignement supérieur sélectif.', 'Il a intégré une grande école de commerce.', 'B1', 'Éducation & Formation'),
  ('Un concours d''entrée', 'Épreuve sélective pour intégrer un établissement.', 'Elle prépare le concours d''entrée à Sciences Po.', 'B1', 'Éducation & Formation'),
  ('Une classe préparatoire', 'Formation intensive préparant aux concours des grandes écoles.', 'Il est en classe préparatoire scientifique.', 'B1', 'Éducation & Formation'),
  ('Le système éducatif', 'Ensemble des institutions et règles organisant l''éducation.', 'Le système éducatif français est centralisé.', 'B1', 'Éducation & Formation'),
  ('Le ministère de l''Éducation nationale', 'Institution qui gère l''école publique en France.', 'Le ministère de l''Éducation nationale fixe les programmes scolaires.', 'B1', 'Éducation & Formation'),
  ('La scolarité obligatoire', 'Période durant laquelle l''école est obligatoire.', 'La scolarité obligatoire va de trois à seize ans en France.', 'B1', 'Éducation & Formation'),
  ('L''école publique', 'Établissement scolaire gratuit géré par l''État.', 'L''école publique est gratuite et laïque.', 'B1', 'Éducation & Formation'),
  ('L''école privée', 'Établissement scolaire payant, souvent sous contrat avec l''État.', 'L''école privée demande des frais de scolarité.', 'B1', 'Éducation & Formation'),
  ('Un établissement sous contrat', 'École privée liée à l''État par un accord de financement.', 'Cet établissement sous contrat suit le programme national.', 'B1', 'Éducation & Formation'),
  ('L''égalité des chances à l''école', 'Principe garantissant les mêmes possibilités de réussite à tous les élèves.', 'L''égalité des chances à l''école reste un objectif difficile à atteindre.', 'B1', 'Éducation & Formation'),
  ('Le décrochage scolaire', 'Abandon progressif de la scolarité par un élève.', 'Le décrochage scolaire touche surtout les adolescents en difficulté.', 'B1', 'Éducation & Formation'),
  ('L''échec scolaire', 'Difficulté durable d''un élève à réussir ses études.', 'L''échec scolaire peut avoir plusieurs origines.', 'B1', 'Éducation & Formation'),
  ('Le harcèlement scolaire', 'Violence répétée exercée entre élèves.', 'Le harcèlement scolaire fait l''objet de nombreuses campagnes de prévention.', 'B1', 'Éducation & Formation'),
  ('L''inclusion scolaire', 'Intégration des élèves en situation de handicap dans les classes ordinaires.', 'L''inclusion scolaire s''est développée ces dernières années.', 'B1', 'Éducation & Formation'),
  ('Un AESH', 'Accompagnant qui aide un élève en situation de handicap.', 'L''AESH accompagne l''élève pendant les cours.', 'B1', 'Éducation & Formation'),
  ('La mixité sociale à l''école', 'Présence d''élèves de milieux sociaux différents dans un même établissement.', 'La mixité sociale à l''école favorise la réussite de tous.', 'B1', 'Éducation & Formation'),
  ('La carte scolaire', 'Zonage déterminant l''établissement scolaire d''un élève selon son domicile.', 'La carte scolaire détermine le collège de secteur.', 'B1', 'Éducation & Formation'),
  ('La validation des compétences', 'Reconnaissance officielle des savoir-faire acquis.', 'La validation des compétences se fait par un contrôle continu.', 'B1', 'Éducation & Formation'),
  ('Le contrôle continu', 'Évaluation régulière tout au long de l''année.', 'Le contrôle continu compte désormais pour le baccalauréat.', 'B1', 'Éducation & Formation'),
  ('Un jury d''examen', 'Groupe de personnes chargées d''évaluer un examen.', 'Le jury d''examen a délibéré pendant deux heures.', 'B1', 'Éducation & Formation'),
  ('La reconnaissance des diplômes étrangers', 'Procédure permettant de faire valider un diplôme obtenu à l''étranger.', 'La reconnaissance des diplômes étrangers facilite l''accès à l''emploi.', 'B1', 'Éducation & Formation'),
  ('L''équivalence de diplôme', 'Correspondance officielle entre un diplôme étranger et un diplôme français.', 'Elle a demandé une équivalence de diplôme pour son diplôme d''infirmière.', 'B1', 'Éducation & Formation'),
  ('La formation continue', 'Formation suivie par un adulte déjà en activité professionnelle.', 'La formation continue permet d''évoluer dans sa carrière.', 'B1', 'Éducation & Formation'),
  ('L''alphabétisation', 'Apprentissage de la lecture et de l''écriture.', 'Des cours d''alphabétisation sont proposés aux adultes.', 'B1', 'Éducation & Formation'),
  ('Les cours de français langue étrangère', 'Cours destinés aux personnes apprenant le français comme langue étrangère.', 'Elle suit des cours de français langue étrangère depuis un an.', 'B1', 'Éducation & Formation'),
  ('Un centre de formation', 'Établissement proposant des formations professionnelles.', 'Le centre de formation propose des cours du soir.', 'B1', 'Éducation & Formation'),
  ('L''enseignement à distance', 'Formation dispensée sans présence physique en classe.', 'L''enseignement à distance s''est développé pendant la crise sanitaire.', 'B1', 'Éducation & Formation'),
  ('Un tuteur pédagogique', 'Personne qui accompagne un apprenant dans son parcours de formation.', 'Mon tuteur pédagogique me suit tout au long de l''année.', 'B1', 'Éducation & Formation'),
  ('La certification professionnelle', 'Reconnaissance officielle d''une compétence liée à un métier.', 'Cette certification professionnelle est reconnue par l''État.', 'B1', 'Éducation & Formation'),
  ('Le niveau de qualification', 'Degré de compétence atteint par une formation.', 'Le niveau de qualification influence le salaire d''embauche.', 'B1', 'Éducation & Formation'),
  ('L''insertion professionnelle', 'Processus d''accès à un emploi après une formation.', 'L''insertion professionnelle des jeunes diplômés reste difficile.', 'B1', 'Éducation & Formation'),
  ('Un partenariat école-entreprise', 'Collaboration entre un établissement scolaire et une entreprise.', 'Ce lycée a mis en place un partenariat école-entreprise.', 'B1', 'Éducation & Formation'),
  ('La pédagogie différenciée', 'Méthode d''enseignement adaptée aux besoins de chaque élève.', 'La pédagogie différenciée aide les élèves en difficulté.', 'B1', 'Éducation & Formation'),
  ('L''évaluation par compétences', 'Méthode d''évaluation basée sur les capacités acquises plutôt que sur des notes.', 'L''évaluation par compétences se développe dans le primaire.', 'B1', 'Éducation & Formation'),
  ('La réforme du lycée', 'Ensemble des changements récents apportés à l''organisation du lycée.', 'La réforme du lycée a modifié les épreuves du baccalauréat.', 'B1', 'Éducation & Formation'),
  ('L''autonomie des établissements', 'Liberté accordée aux écoles pour organiser certains aspects de leur fonctionnement.', 'L''autonomie des établissements varie selon les pays.', 'B1', 'Éducation & Formation'),
  ('La démocratisation scolaire', 'Élargissement de l''accès à l''éducation à toutes les catégories sociales.', 'La démocratisation scolaire a permis l''essor du baccalauréat.', 'B2', 'Éducation & Formation'),
  ('La reproduction sociale', 'Transmission des inégalités sociales d''une génération à l''autre via l''école.', 'Bourdieu a étudié la reproduction sociale à travers le système scolaire.', 'B2', 'Éducation & Formation'),
  ('Le capital culturel', 'Ensemble des connaissances et références culturelles transmises par le milieu familial.', 'Le capital culturel influence la réussite scolaire des enfants.', 'B2', 'Éducation & Formation'),
  ('La sociologie de l''éducation', 'Discipline qui étudie les inégalités et mécanismes du système éducatif.', 'La sociologie de l''éducation analyse les parcours scolaires.', 'B2', 'Éducation & Formation'),
  ('Le déterminisme scolaire', 'Idée selon laquelle l''origine sociale détermine fortement la réussite scolaire.', 'Le déterminisme scolaire reste débattu parmi les chercheurs.', 'B2', 'Éducation & Formation'),
  ('La méritocratie', 'Système où la réussite dépend du mérite individuel plutôt que de l''origine sociale.', 'L''école républicaine se veut fondée sur la méritocratie.', 'B2', 'Éducation & Formation'),
  ('L''autonomisation des élèves', 'Développement de la capacité des élèves à apprendre par eux-mêmes.', 'L''autonomisation des élèves est un objectif pédagogique récent.', 'B2', 'Éducation & Formation'),
  ('La pédagogie inversée', 'Méthode où les élèves étudient la théorie chez eux et pratiquent en classe.', 'La pédagogie inversée change le rôle traditionnel du professeur.', 'B2', 'Éducation & Formation'),
  ('Les neurosciences cognitives appliquées à l''éducation', 'Discipline étudiant le fonctionnement du cerveau pour améliorer l''apprentissage.', 'Les neurosciences cognitives appliquées à l''éducation influencent les nouvelles méthodes pédagogiques.', 'B2', 'Éducation & Formation'),
  ('L''évaluation internationale PISA', 'Enquête internationale comparant les systèmes éducatifs.', 'Les résultats de l''évaluation internationale PISA sont publiés tous les trois ans.', 'B2', 'Éducation & Formation'),
  ('Le classement international des universités', 'Palmarès comparant les universités du monde entier.', 'Le classement international des universités influence le choix des étudiants.', 'B2', 'Éducation & Formation'),
  ('L''internationalisation de l''enseignement supérieur', 'Développement des échanges et collaborations entre universités de différents pays.', 'L''internationalisation de l''enseignement supérieur favorise la mobilité étudiante.', 'B2', 'Éducation & Formation'),
  ('Le programme Erasmus', 'Programme européen d''échange universitaire.', 'Elle a effectué un semestre à l''étranger grâce au programme Erasmus.', 'B2', 'Éducation & Formation'),
  ('La mobilité étudiante', 'Déplacement d''étudiants pour suivre une formation dans un autre pays.', 'La mobilité étudiante s''est fortement développée en Europe.', 'B2', 'Éducation & Formation'),
  ('La fuite des cerveaux', 'Départ des personnes qualifiées vers d''autres pays offrant de meilleures opportunités.', 'La fuite des cerveaux prive certains pays de leurs meilleurs talents.', 'B2', 'Éducation & Formation'),
  ('La privatisation de l''éducation', 'Développement d''établissements éducatifs financés par le secteur privé.', 'La privatisation de l''éducation suscite des débats dans plusieurs pays.', 'B2', 'Éducation & Formation'),
  ('La marchandisation du savoir', 'Transformation de l''éducation en produit commercial.', 'La marchandisation du savoir inquiète certains défenseurs de l''école publique.', 'B2', 'Éducation & Formation'),
  ('L''obsolescence des compétences', 'Perte de valeur d''une compétence en raison de l''évolution technologique.', 'L''obsolescence des compétences oblige à se former tout au long de la vie.', 'B2', 'Éducation & Formation'),
  ('L''apprentissage tout au long de la vie', 'Principe selon lequel la formation continue au-delà des études initiales.', 'L''apprentissage tout au long de la vie devient une nécessité professionnelle.', 'B2', 'Éducation & Formation'),
  ('La reconversion par la formation', 'Changement de métier rendu possible grâce à une nouvelle formation.', 'Sa reconversion par la formation lui a permis de changer de secteur.', 'B2', 'Éducation & Formation'),
  ('Les compétences transversales', 'Aptitudes utiles dans plusieurs domaines professionnels, comme la communication.', 'Les compétences transversales sont de plus en plus recherchées par les employeurs.', 'B2', 'Éducation & Formation'),
  ('L''intelligence artificielle dans l''éducation', 'Utilisation de technologies d''IA pour personnaliser l''apprentissage.', 'L''intelligence artificielle dans l''éducation permet d''adapter les exercices au niveau de chaque élève.', 'B2', 'Éducation & Formation'),
  ('La fracture numérique éducative', 'Inégalité d''accès aux outils numériques dans l''apprentissage.', 'La fracture numérique éducative s''est révélée pendant les confinements.', 'B2', 'Éducation & Formation'),
  ('L''enseignement hybride', 'Combinaison de cours en présentiel et à distance.', 'L''enseignement hybride s''est généralisé après la crise sanitaire.', 'B2', 'Éducation & Formation'),
  ('La gouvernance universitaire', 'Organisation et gestion des établissements d''enseignement supérieur.', 'La gouvernance universitaire varie fortement selon les pays.', 'B2', 'Éducation & Formation'),
  ('L''autonomie financière des universités', 'Capacité des universités à gérer leur propre budget.', 'L''autonomie financière des universités a été renforcée par la loi.', 'B2', 'Éducation & Formation'),
  ('La sélection à l''université', 'Processus de choix des candidats selon certains critères.', 'La sélection à l''université reste un sujet controversé en France.', 'B2', 'Éducation & Formation'),
  ('La professionnalisation des études', 'Orientation des formations vers l''insertion directe dans l''emploi.', 'La professionnalisation des études universitaires s''accélère.', 'B2', 'Éducation & Formation'),
  ('L''employabilité des diplômés', 'Capacité des diplômés à trouver un emploi correspondant à leur formation.', 'L''employabilité des diplômés varie selon les filières choisies.', 'B2', 'Éducation & Formation'),
  ('La validation des acquis professionnels', 'Reconnaissance des compétences acquises par l''expérience professionnelle.', 'La validation des acquis professionnels permet d''obtenir un diplôme sans repasser par la formation initiale.', 'B2', 'Éducation & Formation'),
  ('L''ingénierie pédagogique', 'Conception et organisation de dispositifs de formation.', 'L''ingénierie pédagogique est essentielle pour créer des formations efficaces.', 'B2', 'Éducation & Formation'),
  ('La gouvernance des politiques éducatives', 'Ensemble des décisions et institutions qui orientent les choix éducatifs d''un pays.', 'La gouvernance des politiques éducatives implique de nombreux acteurs.', 'B2', 'Éducation & Formation');
